### ISSUE TITLE
tokens repetidos na tabela de formas

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#1]
@juliana-gurgel, no momento, alguns tokens estão repetidos na tabela do arquivo `sn-yrl-dict.txt`:

> iepé iepé NUM
> iepé iepé QUANT
> iepé INDF
> iepé NUM

> pu N
> pu pu NUM

Não entendi a duplicação de categorias `NUM` e `QUANT`: não seria a mesma coisa usando terminologia diferente? Por outro lado, existe mesmo _pu pu_ como numeral?

**Comment by juliana-gurgel** [comment]
Professor, a distinção entre quantificador e numeral foi feita com base na distinção que Cruz faz sobre quantificação contínua e quantificação discreta. No PIBIC fizemos essa escolha, mas na minha pesquisa de mestrado optei pela etiqueta NUM para as duas categorias (utilizando a terminologia do UD tagset). Compartilhei agora com o senhor por e-mail um arquivo que elaborei na época do PIBIC, que serviu também para a minha pesquisa.
No Vocabulário de Navarro consta a entra "mukũipú (ou pu pu) (num.) - dez", mas de fato não encontrei ocorrência dessa forma nas sentenças do livro. Mesmo assim deixei "pu pu" no nosso dicionário para caso essa forma apareça posteriormente em outros textos que adicionarmos ao nosso corpus.

**Comment by leoalenc** [comment]
> Professor, a distinção entre quantificador e numeral foi feita com base na distinção que Cruz faz sobre quantificação contínua e quantificação discreta. No PIBIC fizemos essa escolha, mas na minha pesquisa de mestrado optei pela etiqueta NUM para as duas categorias (utilizando a terminologia do UD tagset). Compartilhei agora com o senhor por e-mail um arquivo que elaborei na época do PIBIC, que serviu também para a minha pesquisa. No Vocabulário de Navarro consta a entra "mukũipú (ou pu pu) (num.) - dez", mas de fato não encontrei ocorrência dessa forma nas sentenças do livro. Mesmo assim deixei "pu pu" no nosso dicionário para caso essa forma apareça posteriormente em outros textos que adicionarmos ao nosso corpus.

Obrigado, @juliana-gurgel. Certo, então mantemos _pu pu_. 
Por enquanto, para não nos distanciarmos muito do que foi feito no Nheentiquetador (na conversa de quinta, explico o motivo), podemos manter QUANT e NUM como categorias distintas, seguindo Cruz (2011).  Nesse caso, _todos_ é QUANT, _três_ é NUM, por exemplo.
Desse modo, _iepé iepé_ seria QUANT ou NUM? Ou INDF?

**Comment by leoalenc** [comment]
@juliana-gurgel , para justificar duas *tags* para _iepé iepé_, precisaríamos de duas sentenças com essa expressão, uma com QUANT (INDF?), outra com NUM. Tem exemplos disso?

**Comment by juliana-gurgel** [comment]
Professor, abaixo estão os exemplos de _iepé iepé_ tal qual aparecem no arquivo que lhe enviei. Entretanto, percebo agora que cometi um equívoco na classificação como numeral. O senhor concorda?
Agora, classificaria como INDF. Se fosse utilizar a terminologia das Dependências Universais, classificaria como PRON. Está correto?

**Numeral:**
_Nhaã pituna suí, paá, iepé iepé kunhãmuku-itá usasá akiti_.
Contam que, desde aquela noite, as moças, uma a uma, passaram para lá.

**Pronome quantificador:** 
_Aikué iepé iepé ukuau uaá upinaitika_.
Há alguns que sabem pescar.

**O link para o arquivo mencionado:** https://docs.google.com/document/d/11cgXUgDEG_wHG6fbE-FPt_O_NE9VIZfN6k81gTLZBlM/edit

**Comment by leoalenc** [comment]
> Contam que, desde aquela noite, as moças, uma a uma, passaram para lá.

Concordo, apenas INDF.
