### ISSUE TITLE
a palavra 'xukuí' sempre será traduzida como 'aqui está'

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#24]
Xukúi xirura.
Aqui está a calça.

**Comment by leoalenc** [comment]
@juliana-gurgel , no glossário de Navarro (2016), são dadas mais duas outras possibilidades de tradução para essa expressão, classificada como verbo pelo autor: "eis", "olha aqui". Eu não entendi exatamente a natureza da questão que você abriu. Toda questão deve estar relacionada a uma tarefa. O que devemos fazer em relação a isso? Não acho que a tradução dos exemplos deva constituir nosso foco na construção do corpus a partir de textos bilíngues. Podemos nos contentar com as traduções dadas pelos respectivos autores. Claro que podemos nos deparar com algum erro, mas devemos seguir o procedimento a ser ainda especificado nesse caso. Na linguística de corpus, devemos reproduzir, via de regra, os textos originais, no caso, tanto a versão em língua geral amazônica quanto a tradução para o português. No caso de problemas apontados, devemos reformular ou corrigir o exemplo numa outra linha, deixando claro que se trata de uma intervenção nossa. Aqui está uma possibilidade de como fazer isso: https://quod.lib.umich.edu/cgi/t/tei/tei-idx?type=pointer&value=COEDCOR

**Comment by leoalenc** [comment]
@dominickmaia, pode dar uma olhada nesta _issue_?

**Comment by leoalenc** [comment]
Fechando a *issue* porque nenhuma tarefa foi adicionada. O meu comentário acima dirime a dúvida.
