### ISSUE TITLE
Desvio ortográfico no meta-atributo "aknowledge"

### ISSUE THREAD

**Issue by heliolbs** [CompLin/nheengatu#406]
No arquivo `yrl_complin-ud-test.conllu`, todas as 31 ocorrências de "aknowledge" estão com um caractere "c" faltante. 

- [x] Todas devem ser corrigidas para "acknowledge".

**Comment by leoalenc** [comment]
@heliolbs , obrigado por apontar esse erro, corrigido com este [commit](https://github.com/CompLin/nheengatu/commit/5843007252fcc32ac81f72ddccc27c2e0cc45548).
