### ISSUE TITLE
como lidar com palavras em português no texto nheengatu?

### ISSUE THREAD

**Issue by dominickmaia** [CompLin/nheengatu#410]
- [x] como lidar com sentenças em nheengatu que contêm palavras em português não consignadas em Avila (2021)?
- [x] anotar exemplo n° 847 de Hartt (1938) exibido na imagem abaixo

![sent-847](https://github.com/CompLin/nheengatu/assets/70032806/8b2fbc6c-57b7-4502-9af5-83f24e624ea1)

**Comment by leoalenc** [comment]
@dominickmaia , em [Alencar (2023)](https://doi.org/10.5753/stil.2023.234131) explico como lidar com esse tipo de exemplo, que configura uma situação de [code-switching](https://universaldependencies.org/misc.html#origlang), diferentemente do empréstimo, em que uma língua incorpora uma palavra de outra, passando a figurar no dicionário.
O Yauti sabe lidar com esse tipo de situação por meio de etiquetas especiais precedidas de `=` (Alencar, 2023), como neste exemplo:

> s='''Rerikú será urusakã purã ne "vizinho"**/=n:o|por** suí? (p. 380, No. 847) - Tens o bonito paneiro do teu vizinho? - rerekó será urusakána purána né «vizinho» suí?'''

```
>>> AnnotateConllu.parseExample(s,'Hartt1938',0,0,847)
# sent_id = Hartt1938:0:0:847
# text = Rerikú será urusakã purã ne "vizinho" suí?
# text_eng = Do you have your neighbor's beautiful pannier?
# text_por = Tens o bonito paneiro do teu vizinho?
# text_source = p. 380, No. 847
# text_orig = rerekó será urusakána purána né «vizinho» suí?
# text_annotator = LFdeA
1	Rerikú	rikú	VERB	V	Number=Sing|Person=2|VerbForm=Fin	0	root	_	TokenRange=0:6
2	será	será	PART	PQ	PartType=Int	1	advmod	_	TokenRange=7:11
3	urusakã	urusakã	NOUN	N	Number=Sing	1	obj	_	TokenRange=12:19
4	purã	purã	ADJ	A	_	3	amod	_	TokenRange=20:24
5	ne	ne	PRON	PRON2	Case=Gen|Number=Sing|Person=2|PronType=Prs	1	_	_	TokenRange=25:27
6	"	"	PUNCT	PUNCT	_	7	punct	_	SpaceAfter=No|TokenRange=27:28
7	vizinho	vizinho	NOUN	N	Number=Sing	1	obl	_	OrigLang=por|SpaceAfter=No|TokenRange=29:36
8	"	"	PUNCT	PUNCT	_	7	punct	_	TokenRange=36:37
9	suí	suí	ADP	ADP	AdpType=Post	7	case	_	SpaceAfter=No|TokenRange=38:41
10	?	?	PUNCT	PUNCT	_	1	punct	_	SpaceAfter=No|TokenRange=41:42
```
