### ISSUE TITLE
implementar função parseExampleHartt

### ISSUE THREAD

**Issue by heliolbs** [CompLin/nheengatu#433]
Com base na sugestão deste [comentário](https://github.com/CompLin/nheengatu/issues/424#issuecomment-2166391697) de @leoalenc na issue #424, uma função `parseExampleHartt` deve ser criada para facilitar a anotação de sentenças de Hartt (1938):

- [x]  analisar com @dominickmaia e @juliana-gurgel os dois exemplos de uso de `HandleSentsHartt` [deste comentário](https://github.com/CompLin/nheengatu/issues/424#issuecomment-2166224550);
- [x] analisar com @dominickmaia e @juliana-gurgel o atual fluxo de anotação dos exemplos de Hartt, que usa `handleSentsHartt` seguido de `mkSecTextAvila` e de `parseExample`, exemplificado [neste comentário](https://github.com/CompLin/nheengatu/issues/424#issuecomment-2166391697)
- [x]  comparar o funcionamento de `parseExample` e `_parseExample`;
- [x]  analisar o funcionamento de `handleSentsAmorim` e `parseExampleAmorim`;
- [x]  comparar o funcionamento de `handleSentsAmorim` e `handleSentsHartt`;
- [x]  implementar primeira versão da função `parseExampleHartt`;
- [x]  redigir _docstring_ da função `parseExampleHartt`;
- [x]  validar nova função.
- [x] usar módulo `Metadata` para inserir transcritor, modernizador etc.

**Comment by heliolbs** [comment]
@leoalenc , como devo entregar a nova função `parseExampleHartt`?

1. Posto o código diretamente aqui como comentário?
2. Faço o upload de um arquivo .py com a função dentro?
3. Deixo disponível no repositório privado?

**Comment by leoalenc** [comment]
> @leoalenc , como devo entregar a nova função `parseExampleHartt`?
> 
> 1. Posto o código diretamente aqui como comentário?
> 2. Faço o upload de um arquivo .py com a função dentro?
> 3. Deixo disponível no repositório privado?

@heliolbs , por enquanto, pode colocar aqui como comentário, usando a marcação de código de markdown.

**Comment by heliolbs** [comment]
@leoalenc , foram testados três cenários diferentes no desenvolvimento dessa primeira versão da função `parseExampleHartt`, todos cumprindo a exigência de quatro linhas de `handleSentsHartt`:

1. Exemplo **com** referência cruzada em Ávila (2021) (exemplo 40 citado no comentário da issue #424): código **PASSOU**
2. Exemplo **sem** referência cruzada em Ávila (2021) (exemplo 91): código **PASSOU**
3. Exemplo **com** referência cruzada em Ávila (2021) e comentário inline (#) (exemplo 36): código **FALHOU**

Acredito que esse cenário 3 possa ser resolvido dentro da função `handleSentsHartt` por meio de RegEx e `replace` de string para remoção do comentário.

Segue abaixo o código sugerido para a função `parseExampleHartt`:

```
def parseExampleHartt(example,page,copyboard=True,annotator=ANNOTATOR,check=True,outfile=False,overwrite=False,metadata={}, translate=False):
    sents={}
    person="Antônio Levy Melo Nogueira"
    transcriber={'text_orig_transcriber': person,
    'text_por_modernizer': person}
    handled=handleSentsHartt(example)

    metadata={}
    # Checking the existence of cross reference
    if handled['avila'] != 'NA':
        sec=mkSecTextAvila(handled['avila'])
        metadata.update(sec)
    
    metadata.update(transcriber)

    # Organizing main attributes
    prefix="Hartt1928"
    sent_nr=handled['index'][0]
    sents['sent_id']=mkSentId(prefix,sentid=sent_nr)
    sents['text']=handled['text']
    sents['text_por']=handled['text_por']
    sents['text_source']=f"p. {page}, No. {sent_nr}"
    sents['text_orig']=handled['text_orig']

    return _parseExample(sents,copyboard=copyboard,annotator=annotator,check=check,outfile=outfile, overwrite=overwrite,metadata=metadata,translate=translate)
```

**Comment by leoalenc** [comment]
@heliolbs , poderia preparar _docstring_ dessa sua função com os dois tipos de situações que testou? Veja, por exemplo, as _docstrings_ dessas funções mais recentes que implementei no módulo `AnnotateConllu`. Por outro lado, seria interessante revisar os exemplos anotados para incluir logo no treebank. @dominickmaia ?

**Comment by heliolbs** [comment]
> heliolbs , poderia preparar _docstring_ dessa sua função com os dois tipos de situações que testou?

Posso sim, @leoalenc . Vou editar em breve meu último comentário acima inserindo a _docstring_.

> Veja, por exemplo, as _docstrings_ dessas funções mais recentes que implementei no módulo `AnnotateConllu`.

Vou seguir os exemplos das funções `handleSentsHartt`, `parseSingleLineExample` e `parseExampleAmorim` para compor a _docstring_ da nova função.

> Por outro lado, seria interessante revisar os exemplos anotados para incluir logo no treebank. dominickmaia ?

Pode elaborar um pouco essa instrução, @leoalenc ? Não me aprofundei na anotação dos exemplos que usei no teste da função, pois os valores de teste **PASSOU** e **FALHOU** dependeram apenas dos metadados dos exemplos e da ausência de erro de execução da função.

**Comment by heliolbs** [comment]
@leoalenc , o meu penúltimo comentário foi editado com a inserção da _docstring_ da função `parseExampleHartt`.

**Comment by leoalenc** [comment]
> @leoalenc , foram testados três cenários diferentes no desenvolvimento dessa primeira versão da função `parseExampleHartt`, todos cumprindo a exigência de quatro linhas de `handleSentsHartt`:
> 
> 1. Exemplo **com** referência cruzada em Ávila (2021) (exemplo 40 citado no comentário da issue [implementar função para facilitar anotação dos exemplos de Hartt (1938) #424](https://github.com/CompLin/nheengatu/issues/424)): código **PASSOU**
> 2. Exemplo **sem** referência cruzada em Ávila (2021) (exemplo 91): código **PASSOU**
> 3. Exemplo **com** referência cruzada em Ávila (2021) e comentário inline (#) (exemplo 36): código **FALHOU**
> 
> Acredito que esse cenário 3 possa ser resolvido dentro da função `handleSentsHartt` por meio de RegEx e `replace` de string para remoção do comentário.
> 
@dominickmaia , esse problema detectado pelo @heliolbs  foi resolvido no _commit_ abaixo.

**Comment by leoalenc** [comment]
@dominickmaia e @heliolbs , vejam que agora a função admite comentários nas mesmas linhas dos dados de entrada, precedidos de `#`, como no exemplo 36:

```python
>>> example='''36 - ñaá kuñán omukuatiar kuáu kúya.
36 - Nhaã kunhã umukwatiári-kwáu kuya. # repetimos nheengatu de Avila quando coincidimos na adaptação
36 - Nhaã kunhã umukwatiári-kwáu kuya. (Hartt, 321, adap.) - Aquela mulher sabe pintar cuias.
36 - Aquela mulher sabe pintar cuias.'''

>>> AnnotateConllu.parseExampleHartt(example,321)

```
```conllu
# sent_id = Hartt1938:0:0:36
# text = Nhaã kunhã umukwatiári-kwáu kuya.
# text_por = Aquela mulher sabe pintar cuias.
# text_source = p. 321, No. 36
# text_orig = ñaá kuñán omukuatiar kuáu kúya.
# text_eng = TODO
# text_sec = Nhaã kunhã umukwatiári-kwáu kuya.
# text_por_sec = Aquela mulher sabe pintar cuias.
# text_sec_source = Avila (2021)
# text_por_sec_source = Avila (2021)
# text_orig_transcriber = Antônio Levy Melo Nogueira
# text_por_modernizer = Antônio Levy Melo Nogueira
# inputline = Nhaã kunhã umukwatiári-kwáu kuya.
# text_annotator = Leonel Figueiredo de Alencar
1	Nhaã	nhaã	DET	DEMS	Deixis=Remt|Number=Sing|PronType=Dem	2	det	_	TokenRange=0:4
2	kunhã	kunhã	NOUN	N	Number=Sing	3	nsubj	_	TokenRange=5:10
3-4	umukwatiári-kwáu	_	_	_	_	_	_	_	TokenRange=11:27
3	umukwatiári	mukwatiári	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	_
4	kwáu	kwáu	AUX	AUXN	Compound=Yes|VerbForm=Inf	3	aux	_	_
5	kuya	kuya	NOUN	N	Number=Sing	3	obj	_	SpaceAfter=No|TokenRange=28:32
6	.	.	PUNCT	PUNCT	_	3	punct	_	SpaceAfter=No|TokenRange=32:33

```

**Comment by leoalenc** [comment]
```python
>>> AnnotateConllu.parseExampleHartt(example,321)
```
```conllu
# sent_id = Hartt1938:0:0:36
# text = Nhaã kunhã umukwatiári-kwáu kuya.
# text_por = Aquela mulher sabe pintar cuias.
# text_source = p. 321, No. 36
# text_orig = ñaá kuñán omukuatiar kuáu kúya.
# text_eng = TODO
# text_sec = Nhaã kunhã umukwatiári-kwáu kuya.
# text_por_sec = Aquela mulher sabe pintar cuias.
# text_sec_source = Avila (2021)
# text_por_sec_source = Avila (2021)
# text_orig_transcriber = Antônio Levy Melo Nogueira
# text_por_modernizer = Antônio Levy Melo Nogueira
# inputline = Nhaã kunhã umukwatiári-kwáu kuya.
# text_annotator = Leonel Figueiredo de Alencar
1	Nhaã	nhaã	DET	DEMS	Deixis=Remt|Number=Sing|PronType=Dem	2	det	_	TokenRange=0:4
2	kunhã	kunhã	NOUN	N	Number=Sing	3	nsubj	_	TokenRange=5:10
3-4	umukwatiári-kwáu	_	_	_	_	_	_	_	TokenRange=11:27
3	umukwatiári	mukwatiári	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	_
4	kwáu	kwáu	AUX	AUXN	Compound=Yes|VerbForm=Inf	3	aux	_	_
5	kuya	kuya	NOUN	N	Number=Sing	3	obj	_	SpaceAfter=No|TokenRange=28:32
6	.	.	PUNCT	PUNCT	_	3	punct	_	SpaceAfter=No|TokenRange=32:33
```
```python
>>> AnnotateConllu.parseExampleHartt(example,321,transcriber='')
```
```conllu
# sent_id = Hartt1938:0:0:36
# text = Nhaã kunhã umukwatiári-kwáu kuya.
# text_por = Aquela mulher sabe pintar cuias.
# text_source = p. 321, No. 36
# text_orig = ñaá kuñán omukuatiar kuáu kúya.
# text_eng = TODO
# text_sec = Nhaã kunhã umukwatiári-kwáu kuya.
# text_por_sec = Aquela mulher sabe pintar cuias.
# text_sec_source = Avila (2021)
# text_por_sec_source = Avila (2021)
# inputline = Nhaã kunhã umukwatiári-kwáu kuya.
# text_annotator = Leonel Figueiredo de Alencar
1	Nhaã	nhaã	DET	DEMS	Deixis=Remt|Number=Sing|PronType=Dem	2	det	_	TokenRange=0:4
2	kunhã	kunhã	NOUN	N	Number=Sing	3	nsubj	_	TokenRange=5:10
3-4	umukwatiári-kwáu	_	_	_	_	_	_	_	TokenRange=11:27
3	umukwatiári	mukwatiári	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	_
4	kwáu	kwáu	AUX	AUXN	Compound=Yes|VerbForm=Inf	3	aux	_	_
5	kuya	kuya	NOUN	N	Number=Sing	3	obj	_	SpaceAfter=No|TokenRange=28:32
6	.	.	PUNCT	PUNCT	_	3	punct	_	SpaceAfter=No|TokenRange=32:33
```
