### ISSUE TITLE
incluir prefixo pronominal de 3a pessoa do singular e plural

### ISSUE THREAD

**Issue by dominickmaia** [CompLin/nheengatu#442]
- [x]  Incluir variantes de verbos em terceira pessoa com prefixo o?

Stradelli (2014, p. 443) afirma:

> o: prefixo pronominal da terceira pessoa do singular e plural dos verbos. O-recô - tem e têm; o-sô - vai e vão. Em alguns lugares dizem u.

Incluir `o-`, variação regional documentada por Hartt corrobora nossa intenção de representar variantes históricas e aproximar-se o máximo possível das descrições feitas por Hartt.

**Comment by leoalenc** [comment]
> * [ ]   Incluir variantes de verbos em terceira pessoa com prefixo o?
> 
> Stradelli (2014, p. 443) afirma:
> 
> > o: prefixo pronominal da terceira pessoa do singular e plural dos verbos. O-recô - tem e têm; o-sô - vai e vão. Em alguns lugares dizem u.
> 
> Incluir `o-`, variação regional documentada por Hartt corrobora nossa intenção de representar variantes históricas e aproximar-se o máximo possível das descrições feitas por Hartt.

@dominickmaia , Avila (2021) não consigna um prefixo número-pessoal _o-_, diferentemente de _xa-_ e _ha-_, tratados em #404. Esse dicionário não possui nenhum lema (seja de palavra, seja de morfema) começando com _o_. Na verdade, na ortografia de Avila (2021), que se pauta, nesse quesito, no padrão rio-negrino (Cruz, 2011, p. 34), o grafema <u> corresponde ao fonema /o/ da língua antiga. Nesta havia uma oposição entre /o/ e /u/ que se neutralizou na língua moderna.
Então concluo que incluir um prefixo _o-_ nos afastaria da orientação de seguir a ortografia de Avila (2021), algo conveniente em termos de processamento computacional da língua (ver Alencar 2023, 2024). Em última análise, uma fidelidade total à grafia dos textos antigos nos levaria a não fazer qualquer adaptação, o que dificultaria enormemente a construção e posterior processamento do treebank. Caso concorde, peço que feche a questão. Se tiver algum argumento ou dúvida, poste aqui.

**Comment by dominickmaia** [comment]
Entendi e concordo
