### ISSUE TITLE
aspas duplas sobrando ou faltando em "text_eng"

### ISSUE THREAD

**Issue by heliolbs** [CompLin/nheengatu#448]
As quinze sentenças abaixo têm erros relativos às aspas duplas no atributo `text_eng`, provavelmente oriundos da tradução automática. Todas as ocorrências parecem entrar em um destes três casos:
1. Aspas duplas abertas que devem ser fechadas;
2. Aspas duplas fechadas que devem ser abertas;
3. Aspas duplas incompletas que deveriam ser eliminadas.

- [ ] corrigir as aspas duplas das quinze sentenças

```
# sent_id = Avila2021:29:3:332
# text = Eré, se ruayara.
# text_eng = "All right, my brother-in-law.
# text_por = ― Está bem, meu cunhado.

# sent_id = Avila2021:29:4:333
# text = Ayuri ne piri karuka ramé.
# text_eng = I'll come to you in the afternoon."
# text_por = Eu venho ter contigo de tarde.

# sent_id = Avila2021:34:2:427
# text = — Yá!
# text_eng = "Yes!
# text_por = Sim!

# sent_id = Avila2021:34:3:427
# text = Yawasemu tẽ.
# text_eng = We always find it."
# text_por = Encontramos sempre.

# sent_id = Avila2021:55:3:702
# text = Uwitá será sembiiwa kití?
# text_eng = Did he swim to shore?"
# text_por = Ele nadou para a margem?

# sent_id = Casasnovas2006:7:1:1
# text = Yepé ara paá taína-itá taunheẽ ta ramunha tamakwarí tuyué supé: — Abú, puxiwera paá marandua yandé.
# text_eng = One day, they say, children said to their grandfather, old Tamaquari: "Grandpa, we have bad news.
# text_por = Um dia, contam, crianças disseram para o seu avô, o velho Tamaquari: — Vovô, temos uma má notícia. [Adapt. transl.]

# sent_id = Casasnovas2006:7:2:2
# text = Kwá iwí paá yepé ara ukái arã yané irumu!
# text_eng = The world, they say, will one day burn with us!"
# text_por = O mundo, dizem, um dia queimará conosco! [Avila 2021]

# sent_id = Rodrigues1890:2-9:2:102
# text = — Ah!
# text_eng = "Oh!
# text_por = — Ah!

# sent_id = Rodrigues1890:2-9:4:104
# text = Yasú yayusaã?
# text_eng = Let's bet?"
# text_por = Vamos apostar?

# sent_id = Rodrigues1890:2-9:5:105
# text = — Yasú.
# text_eng = "Let's do it.
# text_por = — Vamos.

# sent_id = Rodrigues1890:2-9:6:106
# text = Iné kirimbawa, será, rewewé?
# text_eng = Is it possible that you have the strength to fly?"
# text_por = É possível que tenhas força de voar?

# sent_id = Magalhaes1876:1:30:30
# text = Kunhamukú, suka upé, unheẽ i mena supé: — Aintá upirari pituna.
# text_eng = The girl, at her house, said to her husband: "They opened the night.
# text_por = A moça, em sua casa, disse a seu marido: — Eles abriram a noite. [Marcel Twardowsky Avila]

# sent_id = Magalhaes1876:1:31:31
# text = Kuíri yasú yasarú kuẽma.
# text_eng = Now we'll wait for the morning."
# text_por = Agora nós vamos esperar a manhã. [Marcel Twardowsky Avila]

# sent_id = Magalhaes1876:1:41:41
# text = Musapiri miasúa usika ramé kurumiwasú unheẽ aintá supé: — Penhẽ ti pe supí wana!
# text_eng = When the three vassals arrived, the young man said to them: "You were not faithful!
# text_por = Quando os três vassalos chegaram, o moço disse-lhes: — Vós não fostes fiéis! [Marcel Twardowsky Avila]

# sent_id = Magalhaes1876:1:42:42
# text = Penhẽ pepirari pituna!
# text_eng = You released the night!"
# text_por = Vós soltastes a noite! [Marcel Twardowsky Avila]
```

**Comment by leoalenc** [comment]
@heliolbs , obrigado por levantar esta questão. na verdade, não se trata de erro. É que as sentenças em questão constituem partes de falas ou turnos conversacionais de personagens. Não se trata de sentenças isoladas, como se pode depreender da numeração no atributo `sent_id`. Por exemplo, em `Avila2021:29:3:332`, temos o início da fala, assinalado pelo travessão em português, concluída em `Avila2021:29:4:333`. 


Sobre esse sistema de numeração, consultar:

https://aclanthology.org/2024.propor-2.8/

Você poderia verificar se os exemplos que apontou seguem essa lógica? Caso afirmativo, você poderia fechar a questão.

**Comment by leoalenc** [comment]
| Attribute         | Explanation                                                                                              |
|-------------------|----------------------------------------------------------------------------------------------------------|
| **Source**        | The prefix `Casasnovas2006` indicates the source of the sentence, which is a reference to a work by Casasnovas from 2006. |
| **Text Number**   | The number `7` specifies the text number in the source document where the sentence can be found.         |
| **Sentence Number**| The numbers `1` and `2` indicate the position of the sentence within the specified text. |
| **Collection Number** | The final number in the `sent_id` (e.g., `1` or `2`) indicate the position of the sentence within the specified collection.  |

@heliolbs , veja se está claro agora.

**Comment by heliolbs** [comment]
Entendo, @leoalenc . Posso sim verificar se a lógica está sendo seguida nos quinze exemplos. Dou retorno em breve.

**Comment by heliolbs** [comment]
@leoalenc , analisei cuidadosamente cada uma das 15 sentenças que achei que continham erro. De fato, todas seguem os princípios que você descreveu com relação às aspas duplas nos valores do atributo `text_eng`. Tenho apenas dois questionamentos antes de fechar a _issue_:

1. A primeira sentença da minha lista (`Avila2021:29:3:332`) de quinze sentenças deveria conter o travessão no início do valor do atributo `text`? Ou seja, deveria ser assim `# text = ― Eré, se ruayara.` sendo que atualmente temos `# text = Eré, se ruayara.`?

2. Há algum motivo para os valores do atributo `text_eng` não usarem também o travessão como temos em `text`, `text_por` etc.?

**Comment by leoalenc** [comment]
> @leoalenc , analisei cuidadosamente cada uma das 15 sentenças que achei que continham erro. De fato, todas seguem os princípios que você descreveu com relação às aspas duplas nos valores do atributo `text_eng`. Tenho apenas dois questionamentos antes de fechar a _issue_:
> 
> 1. A primeira sentença da minha lista (`Avila2021:29:3:332`) de quinze sentenças deveria conter o travessão no início do valor do atributo `text`? Ou seja, deveria ser assim `# text = ― Eré, se ruayara.` sendo que atualmente temos `# text = Eré, se ruayara.`?

Corrigido com https://github.com/CompLin/nheengatu/commit/2ad905946b8600f0a1c7b8f448f8372318fe4c7d. Obrigado, @heliolbs .

> 2. Há algum motivo para os valores do atributo `text_eng` não usarem também o travessão como temos em `text`, `text_por` etc.?

https://dictionary.cambridge.org/grammar/british-grammar/reported-speech-direct-speech

https://www.bbc.co.uk/bitesize/articles/zqmwg7h#:~:text=Punctuation%20is%20used%20in%20direct,inverted%20commas%20or%20quotation%20marks.
