### ISSUE TITLE
redigir diretrizes de registro de exemplos de Studart (1926)

### ISSUE THREAD

**Issue by heliolbs** [CompLin/nheengatu#449]
Síntese da _issue_ postada originalmente em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)

- [x] 1. Ignorar itens lexicais por não serem sentenças?
- [x] 2. Ignorar sintagmas nominais por não serem sentenças?
- [x] 3. O que fazer quando houver duas versões em nheengatu?
- [x] 4. O que fazer quando houver duas traduções para o português?
- [x] 5. Usar o mesmo raciocínio dos casos 1 e 2 para ignorar sintagmas preposicionais e adverbiais?
- [x] 6. Ignorar o travessão inicial uma vez que seu uso é extremamente inconsistente?
- [x] 7. Ignorar ou aproveitar glosas de Studart (1926)?
- [x] 8. Como registrar exemplos escritos para ilustrar uma fala mais natural em nheengatu?

**Comment by heliolbs** [comment]
Originalmente postado em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)

1. Ignorar itens lexicais por não serem sentenças?
(STUDART, p. 35)
> _Egai_ (kerosene)

Resposta de @leoalenc :
> @heliolbs, por enquanto, sim. [...]

**Comment by heliolbs** [comment]
Originalmente postado em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)

2. Ignorar sintagmas nominais por não serem sentenças?
(STUDART, p. 35)
> — _Ce reneúa_ (Minha barba)

Resposta de @leoalenc :
> @heliolbs, por enquanto, sim. Ver resposta anterior.

**Comment by heliolbs** [comment]
Originalmente postado em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)

3. O que fazer quando houver duas versões em nheengatu?
(STUDART, p. 36)
> — _Inti rain_ ou _intimahã rain_ (Ainda não)

Resposta de @leoalenc :
> @heliolbs , cada variante constituirá exemplo próprio, por exemplo, Studart1926:0:0:3, Studart1926:0:0:4 etc.

**Comment by heliolbs** [comment]
Originalmente postado em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)

4. O que fazer quando houver duas traduções para o português (ambas do próprio autor)?
(STUDART, p. 36)
> _Mairamê re cika?_ (Quando chegaste ou a que horas chegaste?)

**Comment by heliolbs** [comment]
Originalmente postado em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)

5. Usar o mesmo raciocínio dos casos 1 e 2 para ignorar sintagmas preposicionais e adverbiais?
Embora haja alguns poucos exemplos de sentenças apenas com Eré e uma pontuação no corpus, ao menos elas foram extraídas de dentro de diálogos em suas respectivas fontes. O exemplo com Eré abaixo não faz parte de um diálogo em Studart (1926).
(p. 36)

> — Eré (Sim)

Resposta de @leoalenc :

> @heliolbs , pela formatação e pelo próprio contexto (o autor parece exemplificar nessa página apenas frases ou elementos da conversação em nheengatu), trata-se de fragmento de (um possível) diálogo, fragmento esse que constitui uma sentença (ver noção de mot-phrase na linguística francesa).

(p. 27)

> O logar para onde é exprimido pela palavra keté

Resposta de @leoalenc :

> @heliolbs , está claro que se tem aqui apenas menção , mas não uso da palavra (ver esses conceitos em filosofia da linguagem). Não entra no treebank.

**Comment by heliolbs** [comment]
Originalmente postado em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)

6. Ignorar o travessão inicial uma vez que seu uso é extremamente inconsistente?

Há poucas instâncias em que o contexto dos exemplos nos permite inferir que são diálogos, como os dois abaixo (p. 36):

> — Re piire ana oca será? (Você já varreu a casa?)
> — Xa piire ana (Já varri)

> — Auátá re çaiçú? (A quem amas?)
> — Xa çaiçú ce manha (Eu amo minha mãe)

Entretanto, esse travessão inicial também é muito usado para introduzir desde itens lexicais de um só token até sentença completas passando por simples sintagmas, como mostram os três exemplos abaixo (p. 35):

a.

> — Camutî (pote)

b.

> — Ne re cama (Seu peito)

c.

> — (Elle está fallando à tôa) Ahé onheen oikô teente.

Equivalentes aos cenários a e c imediatamente acima ocorrem sem o travessão (p. 35):

a.

> Ituma (sujo)

c.

> Omunhã oicô irucanga (Está fazendo frio)

**Comment by heliolbs** [comment]
Originalmente postado em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)

7. Ignorar ou aproveitar glosas de Studart (1926)?

Há alguns poucos exemplos nessa fonte em que o autor insere a versão em nheengatu seguida de uma espécie de glosa em português para ilustrar a ordem das palavras na sentença em nheengatu, com ou sem uma tradução subsequente para o português. Seguem dois exemplos sem tradução e um com tradução (p. 31) :

> Ex. : Xa çô putari Ceará keté (Eu ir quero Ceará para) Xa menara patari. Eu casar quero.

> Ex. : Tem vcê a caixa que minha irmã me mandou? [...] Você tem caixa minha irmã mandou mim para ? Re rekô será patuá ce rendera omondó uahá ixê arama?

**Comment by leoalenc** [comment]
> Originalmente postado em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)
> 
> 7. Ignorar ou aproveitar glosas de Studart (1926)?
> 
> Há alguns poucos exemplos nessa fonte em que o autor insere a versão em nheengatu seguida de uma espécie de glosa em português para ilustrar a ordem das palavras na sentença em nheengatu, com ou sem uma tradução subsequente para o português. Seguem dois exemplos sem tradução e um com tradução (p. 31) :
> 
> > Ex. : Xa çô putari Ceará keté (Eu ir quero Ceará para) Xa menara patari. Eu casar quero.
> 
> > Ex. : Tem vcê a caixa que minha irmã me mandou? [...] Você tem caixa minha irmã mandou mim para ? Re rekô será patuá ce rendera omondó uahá ixê arama?

@heliolbs , seria bom aproveitar isso, embora não seja algo prioritário no momento. O objetivo maior seria a expansão no número de sentenças e a revisão do treebank (inclusive resolvendo os erros de #402 ), o que exige uma documentação clara, de modo a garantir coerência nas anotações. Essa questão que você levanta diz respeito mais à tradução, podendo ajudar a construir automaticamente pares de equivalências, o que, por sua vez, pode contribuir para enriquecer o dicionário de Avila (2021). Veja que já temos o atributo `text_por_gloss`. Uma questão que talvez fosse relevante para um experimento seria incluir essa glosa no campo `MISC` seguindo https://universaldependencies.org/misc.html#gloss.
De uma maneira geral, incluo coisas facultativas no design do treebank como forma de validar certas análises ou como ideias para _papers_ futuros etc.

**Comment by leoalenc** [comment]
@heliolbs , então o melhor é seguir o bom senso para determinar o que é uma sentença, procurando responder a pergunta: Isso ocorreria num texto como sentença? Na dúvida, é melhor não incluir. Como muitas questões, temos (i) casos claros, (ii) casos menos claros e (iii) casos em decrescente possibilidade de constituir uma sentença. Não acho que se vá resolver isso a priori. O melhor é ir anotando e checando casos a caso. Veja abaixo minhas clasificações.

> Originalmente postado em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)
> 
> 6. Ignorar o travessão inicial uma vez que seu uso é extremamente inconsistente?
Sim, parece seer mesmo mero separador.
> 
> Há poucas instâncias em que o contexto dos exemplos nos permite inferir que são diálogos, como os dois abaixo (p. 36):
> 
> > — Re piire ana oca será? (Você já varreu a casa?)
> > — Xa piire ana (Já varri)
> 
> > — Auátá re çaiçú? (A quem amas?)
> > — Xa çaiçú ce manha (Eu amo minha mãe)

Tratar como minitextos, por exemplo, `Studart1926:2:1:22` e `Studart1926:12:2:23`, onde `Studart1926:2` é o segundo minitexto dessa fonte.
> 
> Entretanto, esse travessão inicial também é muito usado para introduzir desde itens lexicais de um só token até sentença completas passando por simples sintagmas, como mostram os três exemplos abaixo (p. 35):
> 
> a.
> 
> > — Camutî (pote)

Não é sentença.
> 
> b.
> 
> > — Ne re cama (Seu peito)
> 

Não é sentença.
> c.
> 
> > — (Elle está fallando à tôa) Ahé onheen oikô teente.

É sentença.
> 
> Equivalentes aos cenários a e c imediatamente acima ocorrem sem o travessão (p. 35):
> 
> a.
> 
> > Ituma (sujo)

Não é sentença.
> 
> c.
> 
> > Omunhã oicô irucanga (Está fazendo frio)

É sentença.

**Comment by leoalenc** [comment]
> Síntese da _issue_ postada originalmente em: [heliolbs/nheengatu#5](https://github.com/heliolbs/nheengatu/issues/5)
> 
> * [x]  1. Ignorar itens lexicais por não serem sentenças?
> * [x]  2. Ignorar sintagmas nominais por não serem sentenças?
> * [x]  3. O que fazer quando houver duas versões em nheengatu?
> * [ ]  4. O que fazer quando houver duas traduções para o português?

@heliolbs , `text_por` e `text_por_alt`

> * [ ]  5. Usar o mesmo raciocínio dos casos 1 e 2 para ignorar sintagmas preposicionais e adverbiais?

Sim.

> * [ ]  6. Ignorar o travessão inicial uma vez que seu uso é extremamente inconsistente?

Sim. 

> * [ ]  7. Ignorar ou aproveitar glosas de Studart (1926)?

Sim, se não representar muito trabalho.

> * [ ]  8. Como registrar exemplos escritos para ilustrar uma fala mais natural em nheengatu?

@heliolbs , não entendi isso.

**Comment by heliolbs** [comment]
>> 8. Como registrar exemplos escritos para ilustrar uma fala mais natural em nheengatu?

> @heliolbs , não entendi isso.

@leoalenc , eu havia deixado esse oitavo cenário registrado no meu rascunho antes de transferir a issue do outro repositório para cá. Durante a transferência, acabei esquecendo de prover os exemplos. A situação a que me refiro nessa pergunta ocorre, por exemplo, no segundo parágrafo da página 28 de Studart (1926):

> _Auá tahá ikê ape?_ (Quem entra ahi), _Mahã tahá re munhã re ikô_ ? (Que está fazendo). Conversando, supprimimos a segunda syllaba da partícula _tahá_ e assim dizemos: _Auá-tá ikê ape?_ _Mahã-tá re munhã rikô_?

Entendo que temos duas opções para tratar desses pares de sentenças:
- desconsiderar a variante oral/informal e incluir no banco de árvores apenas a sem abreviações
- incluir no banco de árvores ambas as versões das sentenças

**Comment by leoalenc** [comment]
> > > 8. Como registrar exemplos escritos para ilustrar uma fala mais natural em nheengatu?
> 
> > @heliolbs , não entendi isso.
> 
> @leoalenc , eu havia deixado esse oitavo cenário registrado no meu rascunho antes de transferir a issue do outro repositório para cá. Durante a transferência, acabei esquecendo de prover os exemplos. A situação a que me refiro nessa pergunta ocorre, por exemplo, no segundo parágrafo da página 28 de Studart (1926):
> 

@heliolbs , incluir tudo! São exemplos diferentes. Podemos incluir um atributo de registro etc. (_colloquial_) para caracterizar melhor os exemplos  _Auá-tá ikê ape?_ _Mahã-tá re munhã rikô_?

> > _Auá tahá ikê ape?_ (Quem entra ahi), _Mahã tahá re munhã re ikô_ ? (Que está fazendo). Conversando, supprimimos a segunda syllaba da partícula _tahá_ e assim dizemos: _Auá-tá ikê ape?_ _Mahã-tá re munhã rikô_?
> 
> Entendo que temos duas opções para tratar desses pares de sentenças:
> 
> * desconsiderar a variante oral/informal e incluir no banco de árvores apenas a sem abreviações
> * incluir no banco de árvores ambas as versões das sentenças

**Comment by heliolbs** [comment]
> @heliolbs , incluir tudo! São exemplos diferentes. Podemos incluir um atributo de registro etc. (colloquial) para caracterizar melhor os exemplos _Auá-tá ikê ape_? _Mahã-tá re munhã rikô_?

Entendido, @leoalenc . Incluamos então ambas as versões fazendo uso do atributo de registro. Como não tenho mais nenhuma dúvida no momento, vou encerrar a _issue_ agora. Caso surja algum cenário importante, reabro.
