### ISSUE TITLE
`ccomp` ou `xcomp` em `MooreFP1994:0:0:16`?

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#459]
- [x] `ccomp` ou `xcomp` em `MooreFP1994:0:0:16`?
- [x] anotar exemplo de Costa (1909, p. 165) citado por Avila (2021) no verbete de _yururé_

>@leoalenc , nos últimos três dias, tenho analisado as 15 sentenças marcadas como contendo erro de `multi-obj`. A questão [#8](https://github.com/heliolbs/nheengatu/issues/8) do meu repositório privado lista uma tabela (ainda em construção) com o que tem sido feito. Este [_commit_](https://github.com/heliolbs/nheengatu/commit/250d15aeb658a3024b3b780684974ff8cdfdc6c0) apresenta a revisão de `MooreFP1994:0:0:16`, em que apresento minha revisão da sentença propondo que a `deprel` do `id` 3 passe de `obj` para `iobj` para evitar o erro acusado pelo Udapi por já haver um `ccomp` regido pelo verbo _yururé_. Acredito inclusive que essa estratégia pode funcionar para várias outras sentenças. Segue minha anotação para conferência:

```
# sent_id = MooreFP1994:0:0:16
# text = Ayururé se manha upitá arama yané rendawa upé se ratiwa uxari waá yandé arã.
# text_eng = I asked my mother to stay in our farm that my grandfather left for us.
# text_por = Pedi para minha mãe ficar na nossa fazenda que meu avô deixou para nós.
# text_source = p. 108
# text_orig = a-yururé se-mẫỹã u-pitá arãma iane-rẽndá upé [se-ratíwa u-šári waʔá yãndé arã]S'Rel
# text_annotator = Leonel Figueiredo de Alencar
# reviewer1 = Hélio Leonam Barroso Silva
1	Ayururé	yururé	VERB	V	Number=Sing|Person=1|VerbForm=Fin	0	root	_	TokenRange=0:7
2	se	se	PRON	PRON2	Case=Gen|Number=Sing|Person=1|Poss=Yes|PronType=Prs	3	nmod:poss	_	TokenRange=8:10
3	manha	manha	NOUN	N	Number=Sing	1	iobj	_	TokenRange=11:16
4	upitá	pitá	VERB	V	Person=3|VerbForm=Fin	1	ccomp	_	TokenRange=17:22
5	arama	arama	ADP	ADP	AdpType=Post	4	mark	_	TokenRange=23:28
6	yané	yané	PRON	PRON2	Case=Gen|Number=Plur|Person=1|Poss=Yes|PronType=Prs	7	nmod:poss	_	TokenRange=29:33
7	rendawa	tendawa	NOUN	N	Number=Sing|Rel=Cont	4	obl	_	TokenRange=34:41
8	upé	upé	ADP	ADP	AdpType=Post	7	case	_	TokenRange=42:45
9	se	se	PRON	PRON2	Case=Gen|Number=Sing|Person=1|Poss=Yes|PronType=Prs	10	nmod:poss	_	TokenRange=46:48
10	ratiwa	tatiwa	NOUN	N	Number=Sing|Rel=Cont	11	nsubj	_	TokenRange=49:55
11	uxari	xari	VERB	V	Person=3|VerbForm=Fin	7	acl:relcl	_	TokenRange=56:61
12	waá	waá	PRON	REL	Number=Sing|PronType=Rel	11	obj	_	TokenRange=62:65
13	yandé	yandé	PRON	PRON	Number=Plur|Person=1|PronType=Prs	11	iobj	_	TokenRange=66:71
14	arã	arã	ADP	ADP	AdpType=Post	13	case	_	SpaceAfter=No|TokenRange=72:75
15	.	.	PUNCT	PUNCT	_	1	punct	_	SpaceAfter=No|TokenRange=75:76
```

_Originally posted by @heliolbs in https://github.com/CompLin/nheengatu/issues/402#issuecomment-2243835777_

**Comment by leoalenc** [comment]
@heliolbs , estou achando que o verbo _yururé_ 'pedir' em  `MooreFP1994:0:0:16` rege um `obj` expressando a pessoa a quem se pede algo e um `xcomp` que expressa aquilo que se pede. Acredito que há controle do objeto nesse caso: o sujeito não expresso de upitá o objeto direto de _yururé_. Quer fazer uma pesquisa sobre o assunto para decidir essa questão? Consultar, por exemplo:

```bibtext

@Book{falk2001,
 author = {Falk, Yehuda},
 title = {Lexical-Functional Grammar: an introduction to parallel constraint-based syntax},
 publisher = {CSLI},
 year = {2001},
 address = {Stanford, California},
 isbn = {1-57586-341-3}
 }

```

**Comment by leoalenc** [comment]
@heliolbs , apliquei vários modelos do [Udpipe](https://lindat.mff.cuni.cz/services/udpipe/) sobre a tradução simplificada _I asked my mother to stay in our farm._  Estou achando agora que não parece haver controle funcional no nheengatu porque parece que o sujeito de _upitá_ tanto pode ser a pessoa que enuncia a frase quanto a sua mãe.  Nesse caso, teríamos mesmo `iobj` e `ccomp`.

**Comment by heliolbs** [comment]
> @heliolbs , estou achando que o verbo _yururé_ 'pedir' em `MooreFP1994:0:0:16` rege um `obj` expressando a pessoa a quem se pede algo e um `xcomp` que expressa aquilo que se pede. Acredito que há controle funcional do objeto nesse caso: o sujeito não expresso de _upitá_ é o objeto direto de _yururé_. Quer fazer uma pesquisa sobre o assunto para decidir essa questão? Consultar, por exemplo estas obras (p. 377 da primeira): [...]

Sim, @leoalenc . Quero e preciso pesquisar sobre o assunto. Venho consultando constantemente a [documentação de relações UD](https://universaldependencies.org/u/dep/index.html), pois ainda me perco um pouco na oposição `ccomp` e `xcomp`.

> @heliolbs , apliquei vários modelos do [Udpipe](https://lindat.mff.cuni.cz/services/udpipe/) sobre a tradução simplificada I asked my mother to stay in our farm. Estou achando agora que não parece haver controle funcional no nheengatu porque parece que o sujeito de upitá tanto pode ser a pessoa que enuncia a frase quanto a sua mãe. Nesse caso, teríamos mesmo iobj e ccomp.

De fato, @leoalenc , eu não tinha percebido que o sujeito de _upitá_ poderia ser o sujeito de _ayururé_. Eu só tinha enxergado como sendo o `obj`.

> Estou achando agora que não parece haver controle funcional no nheengatu [...]

@leoalenc , você se refere de modo geral ou apenas à sentença em questão? Se for de modo geral, precisamos rever as 118 ocorrências de `xcomp` do banco de árvores.

**Comment by leoalenc** [comment]
A mesma dúvida aqui:

> \# sent_id = Avila2021:0:0:287
> \# text = _Aí kuité **uyururé** i tupana suí **umeẽ arama** amanawasú pirantá, umuapú arama sinimú marika._
> \# text_eng = The sloth then asked his god to give him heavy rain to fill the chameleon's belly.
> \# text_por = A preguiça então pediu a seu deus para dar chuvona forte, para encher a barriga do camaleão.
> \# text_source = Rodrigues, 161, adap.
> \# text_orig = Aí kuité uyururé i tupana suí umeẽ arama amanawasú pirantá, umuapú arama sinimú marika
> \# text_annotator = LFdeA

**Comment by heliolbs** [comment]
> A mesma dúvida aqui:
> 
> > # sent_id = Avila2021:0:0:287
> > # text = _Aí kuité **uyururé** i tupana suí **umeẽ arama** amanawasú pirantá, umuapú arama sinimú marika._
> > # text_eng = The sloth then asked his god to give him heavy rain to fill the chameleon's belly.
> > # text_por = A preguiça então pediu a seu deus para dar chuvona forte, para encher a barriga do camaleão.
> > # text_source = Rodrigues, 161, adap.
> > # text_orig = Aí kuité uyururé i tupana suí umeẽ arama amanawasú pirantá, umuapú arama sinimú marika
> > # text_annotator = LFdeA

De fato, a moldura de _yururé_ nas duas sentenças é praticamente a mesma. A única diferença que noto é que, em `MooreFP1994:0:0:16` o `iobj` não está adposicionado enquanto que, em `Avila2021:0:0:287`, o `iobj` está adposicionado por `suí`. Essa aparente opcionalidade da posposição merece atenção, @leoalenc ?

**Comment by leoalenc** [comment]
> Avila2021:0:0:287

@heliolbs , seguindo o tratamento de Cruz (2011) para o dativo intralocutivo e extralocutivo em nheengatu, consideramos normalmente como `iobj` apenas o argumento que realiza o papel semântico destinatário, recipiente ou beneficiário por meio das posposições _supé_ _(xupé)_ (terceira pessoa) e _arama_ (primeira  e segunda pessoa). A realização desse papel por meio de sintagma nominal nu é extremamente interessante. Lembra a sintaxe do inglês: _I told Mary a story. I told Mary that her father was fired. She gave the child a bike._ Vamos analisar esses casos em nheengatu como `iobj` também.

**Comment by leoalenc** [comment]
> > A mesma dúvida aqui:
> > > # sent_id = Avila2021:0:0:287
> > > # text = _Aí kuité **uyururé** i tupana suí **umeẽ arama** amanawasú pirantá, umuapú arama sinimú marika._
> > > # text_eng = The sloth then asked his god to give him heavy rain to fill the chameleon's belly.
> > > # text_por = A preguiça então pediu a seu deus para dar chuvona forte, para encher a barriga do camaleão.
> > > # text_source = Rodrigues, 161, adap.
> > > # text_orig = Aí kuité uyururé i tupana suí umeẽ arama amanawasú pirantá, umuapú arama sinimú marika
> > > # text_annotator = LFdeA
> 
> De fato, a moldura de _yururé_ nas duas sentenças é praticamente a mesma. A única diferença que noto é que, em `MooreFP1994:0:0:16`, o `iobj` não está adposicionado enquanto que, em `Avila2021:0:0:287`, o `iobj` está adposicionado por `suí`. Essa aparente opcionalidade da posposição merece atenção, @leoalenc ?

@heliolbs , é algo interessante, sim. Valeria a pena no futuro um estudo visando a alguma publicação sobre o fenômeno das alternâncias verbais em nheengatu. A posposição _suí_ expressa origem. Se A pede algo a B, B é conceptualizado como origem do que é pedido. Por outro lado, B também é recipiente do pedido, pois se trata também de verbo de comunicação. Daí, _pedir algo a alguém_. Em _ayururé se manha_, a origem (ou recipiente) assume a posição de objeto (secundário ou OBJ2 na LFG). Em alemão temos acusativo nesse caso: _Ich bat meine Mutter_ ...
