### ISSUE TITLE
erros de `det-upos` apontados pelo Udapi

### ISSUE THREAD

**Issue by heliolbs** [CompLin/nheengatu#462]
Dentre os seis tipos de erro apontados pela ferramenta Udapi, levantados em #402 , houve apenas **quatro** ocorrências de `det-upos`. A situação de erro é a mesma nas quatro sentenças: o nó _mayé_, etiquetado com `upos` = `ADV` e `xpos` = `ADVRA`, é governado por uma relação `det`:

- [x] `Navarro2016:0:0:85`
- [x] `Avila2021:0:0:105`
- [x] `Avila2021:0:0:107`
- [x] `Avila2021:0:0:112`

No banco de árvores, só há ocorrências de _mayé_ etiquetado com o par `ADV` `ADVRA` (oito ocorrências) ou com o par `SCONJ` `SCONR` (59 ocorrências). Todas as ocorrências com `SCONJ` são governadas pela relação `mark`. Já as com `ADV` são apresentadas na tabela abaixo:

deprel | ocorrências
-- | --
advmod | 46
det | 4
root | 4
nsubj | 2
fixed | 1
obl | 1
parataxis | 1

Vou revisar as quatro sentenças levando em conta as informações acima procurando a `deprel` que melhor substitui cada caso de _mayé_  governado por `det`.

**Comment by leoalenc** [comment]
> Dentre os seis tipos de erro apontados pela ferramenta Udapi, levantados em #402 , houve apenas **quatro** ocorrências de `det-upos`. A situação de erro é a mesma nas quatro sentenças: o nó _mayé_, etiquetado com `upos` = `ADV` e `xpos` = `ADVRA`, é governado por uma relação `det`:
> 
> 
> 
> - [ ] `Navarro2016:0:0:85`
> 
> - [ ] `Avila2021:0:0:105`
> 
> - [ ] `Avila2021:0:0:107`
> 
> - [ ] `Avila2021:0:0:112`
> 
> 
> 
> No banco de árvores, só há ocorrências de _mayé_ etiquetado com o par `ADV` `ADVRA` (oito ocorrências) ou com o par `SCONJ` `SCONR` (59 ocorrências). Todas as ocorrências com `SCONJ` são governadas pela relação `mark`. Já as com `ADV` são apresentadas na tabela abaixo:
> 
> 
> 
> deprel | ocorrências
> 
> -- | --
> 
> advmod | 46
> 
> det | 4
> 
> root | 4
> 
> nsubj | 2
> 
> fixed | 1
> 
> obl | 1
> 
> parataxis | 1
> 
> 
> 
> Vou revisar as quatro sentenças levando em conta as informações acima procurando a `deprel` que melhor substitui cada caso de _mayé_  governado por `det`.

@heliolbs , obrigado pela exposição clara do problema. Parece de fato haver um choque entre a documentação e o validador. Sim, acho que é o caso de abrir uma questão no repositório da ferramenta. Você faria isso? É uma boa oportunidade de começar a atuar no cenário internacional e se entrosar na comunidade de dependências universais. Você pode só verificar se não haveria um repositório de dependências universais onde seria melhor levantar a questão? Talvez o tools ou mesmo o do nheengatu de UF. Você pode começar pelo repositório do udapi e eventualmente transferir a questão para um outro repositório. É importante fazer menção nessa nova questão em inglês a este comentário seu no nosso repositório.

**Comment by heliolbs** [comment]
> @heliolbs , obrigado pela exposição clara do problema.

Disponha, @leoalenc !

> Parece de fato haver um choque entre a documentação e o validador.

Acho que não entendi essa parte. A documentação da UD diz que a `upos` DET costuma co-ocorrer com a relação `det` e que os determinantes possessivos do inglês são a exceção conhecida por receberem `upos` DET e relação `nmod`. Já o validador (trecho de código abaixo) acusa erro de `det-upos` caso o nó que governa `det` seja etiquetado com uma `upos` diferente de DET ou PRON:

```
if udeprel == 'det' and upos not in ('DET', 'PRON'):
            self.log(node, 'det-upos', 'deprel=det upos!=DET|PRON (but %s)' % upos)
```

O choque seria esse?

> Sim, acho que é o caso de abrir uma questão no repositório da ferramenta. Você faria isso? É uma boa oportunidade de começar a atuar no cenário internacional e se entrosar na comunidade de dependências universais. Você pode só verificar se não haveria um repositório de dependências universais onde seria melhor levantar a questão? Talvez o tools ou mesmo o do nheengatu de UD. Você pode começar pelo repositório do udapi e eventualmente transferir a questão para um outro repositório. É importante fazer menção nessa nova questão em inglês a este comentário seu no nosso repositório.

Faria sim, @leoalenc . Vou verificar qual o melhor diretório onde levantar a questão. Escrevei em inglês e mencionarei meu comentário.

**Comment by leoalenc** [comment]
@heliolbs , todas as quatro ocorrências desse tipo de erro envolvem a expressão idiomática (_multiword expression_ ou MWE) _mayé waá_, que Avila (2021) explica desta forma:

> ● **mayé waá<sup>1</sup>** - qual // Reg. hist.: [Aguiar, [mahiuhá] 25, [mahi-uahá] 27]:  Mayé waá taá pe suiwara uxari kwá apukuitawa se igara pupé? - Qual de vocês deixou este remo dentro da minha canoa?;  Mayé waá nheenga rupí yasú 
 yayumbué? (Oliveira; Schwade, 82) - Por meio de qual língua vamos estudar?;  Amukameeẽ ana pemaã siiya se paya uxari waá-itá amunhã, mayé waá resewara taá aintá suiwara pemburi itá se resé? (O Novo Testamento em nyengatu,  João, 10:32) - Tenho-vos mostrado muitas obras procedentes de meu Pai. Por qual dessas obras me apedrejais?
● **mayé waá<sup>2</sup>**- aquele que, quem quer que:  [...] mairamé ta umunhã dabukurí, ta uparawaka nhaã kurumiwasú puranga mirĩ waá, mayé waá ta piá suí, [...]. (Leetra Indígena. n. 17, 27, adap.)  [...] quando eles faziam dabucuri, elas escolhiam o rapaz que era bonitinho, aquele que era do seu agrado, [...].;  [...] asuí mayé waá kwá utiari waá penhẽ, aé yuíri upurará i puxiwerasawa resewara. (O Novo Testamento em nyengatu, Gálatas 5:10, adap.) - [...] e quem quer que vos inquiete, ele também sofrerá por causa de sua maldade.

A regra do Udapi parece admitir apenas as etiquetas `DET` e `PRON` como núcleos governados sob a relação `det`.  No caso, a etiqueta do dependente é `ADV`.

**Comment by leoalenc** [comment]
@heliolbs , veja esta página sobre MWEs em UD: https://universaldependencies.org/u/dep/fixed.html

**Comment by leoalenc** [comment]
@heliolbs , no commit acima eu incluí `ExtPos=DET` nos quatro casos, seguindo https://universaldependencies.org/u/feat/ExtPos.html. Mesmo assim, a ferramenta continua indicando os mesmos erros. Acho que é mais um caso a apresentar no repositório da ferramenta e/ou de UD.

`udapy -s read.Conllu zone=yrl ud.MarkBugs tests=det-upos < yrl_complin-ud-test.conllu > bugs.html`

> 2024-07-30 17:08:16,325 [   INFO] execute -  ---- ROUND ----
> 2024-07-30 17:08:16,325 [   INFO] execute - Executing block read.Conllu
> 2024-07-30 17:08:16,430 [   INFO] execute - Executing block ud.MarkBugs
> 2024-07-30 17:08:16,557 [WARNING] after_process_document - ud.MarkBugs Error Overview:
>             det-upos          4
>                TOTAL          4
> 
> 2024-07-30 17:08:16,557 [   INFO] execute - Executing block write.Conllu

**Comment by heliolbs** [comment]
@leoalenc , eu não estava familiarizado com o tratamento de MWE pela UD nem com o atributo `ExtPos`. Depois das leituras, acredito ter finalmente entendido. Pelo que li na documentação, concordo que sua alteração deveria ter resolvido os quatro erros apontados. Levando em conta o código do (`ud.MarkBugs`](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/markbugs.py), fica explícito que esse atributo está sendo ignorado, o que me leva a crer que, não somente o UD_Nheengatu-CompLin, mas todos os repositórios UD que fazem uso desse atributo `ExtPos` estão sendo penalizados com esses falsos negativos. No meu entender, o erro é da ferramenta Udapi então a questão será escrita lá.

Com relação a sua sugestão de eu mencionar o meu comentário original, tenho impressão de que não seja a melhor ideia, pois o apontamento do problema real ocorreu no (seu comentário](https://github.com/CompLin/nheengatu/issues/462#issuecomment-2259131277). Vejo duas opções então: mencionar a questão #462 ou mencionar o seu comentário específico. O que seria melhor?

**Comment by leoalenc** [comment]
@heliolbs , mencione então a questão. Sobre o repositório a ser escolhido onde postar a questão, é bom escolher um que tenha "movimento", ou seja, que tenha tido ultimamente um fluxo bom de questões e resoluções. Acho que não é problema errar na escolha, as pessoas gentilmente vão propor transferir pra outro lugar se for o caso. É uma questão de dependências universais em última análise porque afeta a classificação dos bancos de árvores, levada a cabo naquele eval.log.
