### ISSUE TITLE
erros de `no-VerbForm` apontados pelo Udapi

### ISSUE THREAD

**Issue by heliolbs** [CompLin/nheengatu#464]
Dentre os seis tipos de erro apontados pela ferramenta Udapi, levantados em #402 , houve 96 ocorrências de `no-VerbForm`, todas contendo `upos` = VERB. Com exceção de dois casos de `xpos` = V e outros dois de `xpos` = A2, todas as ocorrências envolvem a `xpos` = V2. Tomando como exemplo a abordagem de inspeção do [código do bloco `ud.MarkBugs.py`](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/markbugs.py) do udapi-python em #463 , podemos inspecionar o código, em especial os três blocos abaixo, citados na ordem em que aparecem no arquivo original. O primeiro bloco mostra que a inserção do código ISO da língua no `sent_id` das árvores e também como parâmetro do comando do Udapi permite personalizar os testes:

```
Some tests may be customized for individual languages if the language code is
available as the zone id. The zone id can be provided in the sentence id after
the slash (e.g., "sent_id = s125/en" for English), or as a parameter of the
reader:

udapy -s read.Conllu zone=en ud.MarkBugs < in.conllu > marked.conllu 2> log.txt
```

O segundo bloco apresenta a obrigatoriedade do traço `VerbForm` para nós etiquetados com `upos` = VERB.

```
REQUIRED_FEATURE_FOR_UPOS = {
    'PRON': 'PronType',
    'DET': 'PronType',
    'NUM': 'NumType',
    'VERB': 'VerbForm',
}
```

O terceiro bloco mostra tanto a verificação programada como a possibilidade de exceções por meio da checagem do `zone id`. De acordo com os códigos ISO abaixo, as línguas para as quais a não obrigatoriedade de `VerbForm` já está registrada são indonésio, javanês, tagalog, hiligaynon e batad ifugao. 

```
for i_upos, i_feat in REQUIRED_FEATURE_FOR_UPOS.items():
    if upos == i_upos and not feats[i_feat]:
        # Some languages do not distinguish finite and non-finite forms of verbs.
        # The VerbForm feature is not obligatory in those languages.
        if i_feat != 'VerbForm' or not node.root.zone.split('_')[0] in {'id', 'jv', 'tl', 'hil', 'ifb'}:
            self.log(node, 'no-' + i_feat, 'upos=%s but %s feature is missing' % (upos, i_feat))
```

Infelizmente, a exceção está condicionada à falta de oposição entre formas finitas e infinitivas dos verbos na língua. Essa oposição aparece consistentemente no banco de árvores do nheengatu, logo a língua não está elegível para ser incluída na lista de exceções dessa verificação.

O que acha, @leoalenc ?

**Comment by leoalenc** [comment]
@heliolbs , creio que a questão foi resolvida, como mostrei em #402 .
