### ISSUE TITLE
erros de `finverb-mood` apontados pelo Udapi

### ISSUE THREAD

**Issue by heliolbs** [CompLin/nheengatu#465]
Dentre os seis tipos de erro apontados pela ferramenta Udapi, levantados em #402 , houve 2737 ocorrências de `finverb-mood`, o que equivale a 94,5% de todos os erros. Seguindo a abordagem das questões #463 e #464 , vamos focar na inspeção do [código do bloco `ud.MarkBugs.py`](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/markbugs.py) em vez de apenas analisar as árvores:

```
if feats['VerbForm'] == 'Fin':
    if upos not in ('VERB', 'AUX'):
        self.log(node, 'finverb-upos', 'VerbForm=Fin upos!=VERB|AUX (but %s)' % upos)
    if not feats['Mood']:
        self.log(node, 'finverb-mood', 'VerbForm=Fin but Mood feature is missing')
```

O trecho de código acima indica que o apontamento desse erro se baseia na simples verificação de presença do atributo `Mood` na coluna `feats` (segundo `if`) do token etiquetado com `upos` = VERB | AUX (primeiro `if`). Diferentemente da indicação de erro `no-VerbForm` da questão anterior, esta não admite nenhum tipo de exceção na versão atual. De modo similar, a [documentação da UD](https://universaldependencies.org/u/feat/Mood.html) também não menciona línguas isentas de expressão de modo verbal. A morfologia verbal do nheengatu não expressa a categoria modo, ao menos não por morfema, o que implicaria a falta de embasamento linguístico para o uso do atributo `Mood` para os verbos do nheengatu e a permanência desses 2737 erros. Diante desse impasse, o cumprimento dessa exigência só pode vir de uma de duas fontes: a adequação do banco de árvores ou a revisão da teoria. Foquemos na primeira opção.

Dos quatorze valores que a UD admite para o atributo `Mood`, Ávila (2021) só menciona cinco noções equivalentes a: condicional, imperativo, indicativo, irreal e optativo. O indicativo não é expresso nem por morfema nem por partícula. O condicional, o irreal e o optativo seriam expressos, respectivamente, apenas por estes grupos de partículas: _maã_, _ramé_, _amú_; _kurí_; e _maã_. Apenas o imperativo seria expresso, de modo limitado, por um morfema.

Ávila (2021, p. 656) diz que o morfema _re-_, além de ser "utilizado para a flexão número-pessoal dos verbos (da 1ª classe)", "também é utilizado no **modo imperativo**" (grifo meu). Como os outros modos são expressos na sentença por meio de partículas, a solução mais viável para esses erros poderia se basear na inclusão do atributo `Mood`, com `Ind` ou `Imp` como únicos valores nas colunas `feats` dos tokens etiquetados com `upos` = VERB | AUX.

O que acha, @leoalenc ?

**Comment by leoalenc** [comment]
> Dentre os seis tipos de erro apontados pela ferramenta Udapi, levantados em #402 , houve 2737 ocorrências de `finverb-mood`, o que equivale a 94,5% de todos os erros. Seguindo a abordagem das questões #463 e #464 , vamos focar na inspeção do [código do bloco `ud.MarkBugs.py`](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/markbugs.py) em vez de apenas analisar as árvores:
> 
> 
> 
> ```
> 
> if feats['VerbForm'] == 'Fin':
> 
>     if upos not in ('VERB', 'AUX'):
> 
>         self.log(node, 'finverb-upos', 'VerbForm=Fin upos!=VERB|AUX (but %s)' % upos)
> 
>     if not feats['Mood']:
> 
>         self.log(node, 'finverb-mood', 'VerbForm=Fin but Mood feature is missing')
> 
> ```
> 
> 
> 
> O trecho de código acima indica que o apontamento desse erro se baseia na simples verificação de presença do atributo `Mood` na coluna `feats` (segundo `if`) do token etiquetado com `upos` = VERB | AUX (primeiro `if`). Diferentemente da indicação de erro `no-VerbForm` da questão anterior, esta não admite nenhum tipo de exceção na versão atual. De modo similar, a [documentação da UD](https://universaldependencies.org/u/feat/Mood.html) também não menciona línguas isentas de expressão de modo verbal. A morfologia verbal do nheengatu não expressa a categoria modo, ao menos não por morfema, o que implicaria a falta de embasamento linguístico para o uso do atributo `Mood` para os verbos do nheengatu e a permanência desses 2737 erros. Diante desse impasse, o cumprimento dessa exigência só pode vir de uma de duas fontes: a adequação do banco de árvores ou a revisão da teoria. Foquemos na primeira opção.
> 
> 
> 
> Dos quatorze valores que a UD admite para o atributo `Mood`, Ávila (2021) só menciona cinco noções equivalentes a: condicional, imperativo, indicativo, irreal e optativo. O indicativo não é expresso nem por morfema nem por partícula. O condicional, o irreal e o optativo seriam expressos, respectivamente, apenas por estes grupos de partículas: _maã_, _ramé_, _amú_; _kurí_; e _maã_. Apenas o imperativo seria expresso, de modo limitado, por um morfema.
> 
> 
> 
> Ávila (2021, p. 656) diz que o morfema _re-_, além de ser "utilizado para a flexão número-pessoal dos verbos (da 1ª classe)", "também é utilizado no **modo imperativo**" (grifo meu). Como os outros modos são expressos na sentença por meio partículas, a solução mais viável para esses erros poderia se basear na inclusão do atributo `Mood`, com `Ind` ou `Imp`, como únicos valores nas colunas `feats` dos tokens etiquetados com `upos` = VERB | AUX.
> 
> 
> 
> O que acha, @leoalenc ?
> 
> 

@heliolbs, você está de parabéns. Apresentou a problemática de forma clara e em linguagem precisa. Com base na sua conclusão, temos, de fato, em nheengatu uma oposição entre formas flexionadas e formas não flexionadas de verbos. Parece, no momento, que a única maneira de expressar essa oposição é por meio do atributo forma verbal. Talvez seja oportuno fazer um levantamento no banco de árvores das formas de verbos sem o atributo forma verbal e pensar numa solução que envolva a inclusão desse atributo. Sem consultar os dados, suspeito que o maior número de casos envolva os chamados verbos de segunda classe ou verbos estativos conforme Cruz (2011). Seguindo a ortografia de Ávila (2021), estamos grafando o que seria o prefixo de pessoa e número separado do verbo. À primeira vista, parece estranho anotar a forma verbal como infinitiva nesse caso. Alguma ideia de como contornar esse dilema? Em último caso, podemos criar um novo valor para o atributo forma verbal.

**Comment by leoalenc** [comment]
@heliolbs , obrigado pela exposição clara do problema. Parabéns pelo encadeamento lógico das ideias 
e pela linguagem escorreita. De fato, uma simples solução seria incluir algum tipo de modo nas formas verbais. A opção básica seria o indicativo. Nas sentenças com segunda pessoa do singular expressa pelo prefixo re-, poderíamos incluir imperativo com base numa interpretação do ato de fala expresso pela sentença, se declarativo ou ordem. A propósito: Ávila registra o imperativo histórico com prefixo e-, acho que ocorre em sentenças do Hartt, algumas das quais já estão no banco de árvores. O Yauti consegue lidar com esse imperativo. Eu abri e concluí uma questão a esse respeito. O problema que o antevejo são as sentenças com modo expresso por partículas. Deveríamos simplesmente copiar o modo da partícula para o verbo? Isso me pareceria artificial. Como expressar melhor em Dependências Universais o fato de que, via de regra, o modo verbal não é expresso pela forma verbal? Talvez seja uma questão para se abrir na documentação de UD. Quer levar isso adiante? De novo, a dúvida é qual sub-repositório escolher.

**Comment by leoalenc** [comment]
@heliolbs , acho que devemos tentar paralelamente uma mudança no código da ferramenta de verificação de erros, abrindo uma questão no repositório respectivo ao mesmo tempo em que investigamos como resolver a questão caso os responsáveis pela ferramenta não concordem com a mudança.

**Comment by heliolbs** [comment]
> @heliolbs, você está de parabéns. Apresentou a problemática de forma clara e em linguagem precisa.

Obrigado, @leoalenc !

> Com base na sua conclusão, temos, de fato, em nheengatu uma oposição entre formas flexionadas e formas não flexionadas de verbos. Parece, no momento, que a única maneira de expressar essa oposição é por meio do atributo forma verbal. Talvez seja oportuno fazer um levantamento no banco de árvores das formas de verbos sem o atributo forma verbal e pensar numa solução que envolva a inclusão desse atributo. Sem consultar os dados, suspeito que o maior número de casos envolva os chamados verbos de segunda classe ou verbos estativos conforme Cruz (2011).

Criarei uma questão aqui no repositório vinculada à execução desse levantamento.

>Seguindo a ortografia de Ávila (2021), estamos grafando o que seria o prefixo de pessoa e número separado do verbo.

Eu estava sob a impressão de que estávamos seguindo Ávila (2021) ao grafar o prefixo número-pessoal **junto** do verbo. A primeira sentença do banco (`MooreFP1994:0:0:1`), por exemplo, tem a palavra _yamunhã_.

> À primeira vista, parece estranho anotar a forma verbal como infinitiva nesse caso. Alguma ideia de como contornar esse dilema? Em último caso, podemos criar um novo valor para o atributo forma verbal.

Por enquanto, não tenho nenhuma sugestão. Retorno aqui após a conclusão do levantamento e mais reflexão.

**Comment by heliolbs** [comment]
> @heliolbs , obrigado pela exposição clara do problema. Parabéns pelo encadeamento lógico das ideias e pela linguagem escorreita.

Disponha e obrigado, @leoalenc !

> De fato, uma simples solução seria incluir algum tipo de modo nas formas verbais. A opção básica seria o indicativo. Nas sentenças com segunda pessoa do singular expressa pelo prefixo re-, poderíamos incluir imperativo com base numa interpretação do ato de fala expresso pela sentença, se declarativo ou ordem.

Concorco 👍

> A propósito: Ávila registra o imperativo histórico com prefixo e-, acho que ocorre em sentenças do Hartt, algumas das quais já estão no banco de árvores. O Yauti consegue lidar com esse imperativo. Eu abri e concluí uma questão a esse respeito.

De fato, já há sentenças com `Mood=Imp` no banco, @leoalenc , mas eu não estava ciente disso. Mesmo tendo lido o verbete sobre o prefixo de imperativo histórico, faltou-me incluir essa checagem nas minhas consultas ao banco.

> O problema que o antevejo são as sentenças com modo expresso por partículas. Deveríamos simplesmente copiar o modo da partícula para o verbo? Isso me pareceria artificial.

Concordo que não parece uma solução muito boa. Precisamos de uma alternativa.

> Como expressar melhor em Dependências Universais o fato de que, via de regra, o modo verbal não é expresso pela forma verbal?

Vou investigar se algum outro banco não precisou resolver esse problema. Em caso afirmativo, podemos averiguar o aproveitamento da solução.

> Talvez seja uma questão para se abrir na documentação de UD. Quer levar isso adiante? De novo, a dúvida é qual sub-repositório escolher.

Quero sim, @leoalenc . Vou avaliar as opções de sub-repositórios.

**Comment by heliolbs** [comment]
> @heliolbs , acho que devemos tentar paralelamente uma mudança no código da ferramenta de verificação de erros, abrindo uma questão no repositório respectivo ao mesmo tempo em que investigamos como resolver a questão caso os responsáveis pela ferramenta não concordem com a mudança.

Concordo, @leoalenc . Farei isso 👍

**Comment by leoalenc** [comment]
> > @heliolbs, você está de parabéns. Apresentou a problemática de forma clara e em linguagem precisa.
> 
> Obrigado, @leoalenc !
> 
> > Seguindo a ortografia de Ávila (2021), estamos grafando o que seria o prefixo de pessoa e número separado do verbo.
> 
> Eu estava sob a impressão de que estávamos seguindo Ávila (2021) ao grafar o prefixo número-pessoal **junto** do verbo. A primeira sentença do banco (`MooreFP1994:0:0:1`), por exemplo, tem a palavra _yamunhã_.

@heliolbs , distinguem-se dois tipos básicos de verbos em nheengatu: verbos ativos ou dinâmicos (Cruz 2011), como _munhã_ ((_ixé) amunhã_, _(indé) remunhã_, _(aé) umunhã_ etc.), denominados verbos de primeira classe por Navarro (2016) e Avila (2021), e verbos inativos ou estativos (Cruz 2011), que Avila (2021) denomina verbos de segunda classe, por exemplo: _se rurí_, _ne rurí_, _surí_ etc., que Cruz (2011), entre outros, grafa  _seruri_, _neruri_ etc. Note que Cruz (2011) considera verbos estativos também itens como _puranga_ que não se flexionam, os quais Avila (2021), na esteira de Navarro (2016), classifica como adjetivos.
A propósito, esta discussão sobre formas verbais, relacionadas ao atributo `VerbForm`, pertence, na verdade, a #464, uma vez que o foco da presente _issue_ é o atributo `Mood`. _Mea culpa_, acabei postando o comentário mais acima no lugar errado.

**Comment by leoalenc** [comment]
@heliolbs , os erros deste tipo foram todos sanados, ver #402.
