### ISSUE TITLE
incluir revisor de algumas sentenças

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#476]
- [ ] revisar sentenças de #462 para inclusão de @heliolbs como revisor

>@leoalenc , eu não estava familiarizado com o tratamento de MWE pela UD nem com o atributo `ExtPos`. Depois das leituras, acredito ter finalmente entendido. Pelo que li na documentação, concordo que sua alteração deveria ter resolvido os quatro erros apontados. Levando em conta o código do (`ud.MarkBugs`](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/markbugs.py), fica explícito que esse atributo está sendo ignorado, o que me leva a crer que, não somente o UD_Nheengatu-CompLin, mas todos os repositórios UD que fazem uso desse atributo `ExtPos` estão sendo penalizados com esses falsos negativos. No meu entender, o erro é da ferramenta Udapi então a questão será escrita lá.

_Originally posted by @heliolbs in https://github.com/CompLin/nheengatu/issues/462#issuecomment-2264039554_

**Comment by heliolbs** [comment]
@leoalenc , as revisões das quatro sentenças da questão #462 estão neste [_commit_](https://github.com/heliolbs/nheengatu/commit/f0ffdb9ca160715c41d2378d6582a79d83459022). A única sugestão de alteração é a `deprel` do nó 10 ***aé*** da sentença `Avila2021:0:0:107` de `obj` para `nsubj`. Concordo com o resto das anotações.

**Comment by leoalenc** [comment]
@heliolbs , inspecionando novamente a anotação de, ocorreu-me que a atribuição da `head` do terceiro _token_ com `deprel` `conj` discrepa da orientação de https://universaldependencies.org/u/dep/conj.html. Fiz a correção necessária. Faz sentido para você?
