### ISSUE TITLE
dúvida de tradução que surgiu durante anotação

### ISSUE THREAD

**Issue by dominickmaia** [CompLin/nheengatu#498]
Hartt (1938:323) traduziu as sentenças `63` e `64` da seguinte maneira (ver última linha do exemplo), sem traduzir yurú (boca). A tradução da sentença 64 por Avila (2021) obedece o sentido da original, incluindo a palavra boca/yurú. Podemos traduzir 63 para "A mãe (dele) beijou a boca do seu filho"?

63 - imáinya opyter imymyra yurú.
63 - I manha upitera i mimbira yurú.
**63 - a mãe beijou seu filho.**

64 - ixé xapytér kuae kuñántain yurú.
64 - Ixé xapitera kwaá kunhatãi yurú.
64 - Ixé apitera kwaá kunhatãi yurú. (Hartt, 323, adap.) - Eu beijei a boca dessa menina.
**64 - dei um beijo à menina.**

**Comment by leoalenc** [comment]
> Hartt (1938:323) traduziu as sentenças `63` e `64` da seguinte maneira (ver última linha do exemplo), sem traduzir yurú (boca). 


Sem problema. Mantemos a tradução do Hartt em ortografia modernizada como valor do atributo `text_por` (obrigatório), podendo incluir uma tradução mais literal como você sugere em `text_por_alt`, mencionando DMA em `text_por_alt_translator`.
  
>A tradução da sentença 64 por Avila (2021) obedece o sentido da original, incluindo a palavra boca/yurú.

Você inclui no caso de 64 a versão do Avila como `text_sec`, `text_por_sec` etc. (ver #494 ). 

>  Podemos traduzir 63 para "A mãe (dele) beijou a boca do seu filho"?

\# text_por_alt = A mãe beijou a boca do filho.
\# text_por_alt_translator = LFdeA

O possessivo é sempre obrigatório em nheengatu com nomes necessariamente relacionais, como termos de parentesco, diferentemente de línguas como português, que, normalmente, dispensa ou mesmo repudia o possessivo nesses casos, deixando-o subentendido:

> UFG - Universidade Federal de Goiás
> https://repositorio.bc.ufg.br › bitstreams › download
> PDF
> 30 de nov. de 2020 — casos em que **as mães levam os filhos para a escola** e elas ficam nas salas de aula ou nos pátios. Page 165. 162 enquanto acontecem as aulas. 

Um estudo de corpus do português permitiria verificar ou rechaçar essa minha suposição. Compare o exemplo  (213) de Cruz (2011, p. 155) com a respectiva tradução. É uma questão sutil, mas interessante, de contraste entre a duas línguas. 

@dominickmaia , lembro que `text_por_alt` é opcional no treebank. Cabe a você definir uma política coerente a esse respeito no que tange a Hartt (1938), justificando a inclusão ou não, algo que você deve documentar na dissertação.
 
> 
> 63 - imáinya opyter imymyra yurú. 63 - I manha upitera i mimbira yurú. **63 - a mãe beijou seu filho.**
> 
> 64 - ixé xapytér kuae kuñántain yurú. 64 - Ixé xapitera kwaá kunhatãi yurú. 64 - Ixé apitera kwaá kunhatãi yurú. (Hartt, 323, adap.) - Eu beijei a boca dessa menina. **64 - dei um beijo à menina.**

@dominickmaia, via de regra, reproduzimos fielmente as traduções de Casasnovas (2006) (ver #494 ), Amorim (1928), Hartt (1938) etc.,  pois se trata de documentação importante sobre como pessoas como longa vivência na região amazônica, amplos conhecimentos do nheengatu e intensa convivência com falantes resolviam o problema de veicular em português a maneira como entendiam as sentenças em nheengatu. Veja minhas respostas acima. Sugiro formatar os atributos de metadados dessas duas sentenças ou melhor já anotá-las (inclua acima tarefa atribuída a você mesma), para que possamos fechar a questão com dois exemplos prontos resolvidos.

**Comment by leoalenc** [comment]
@dominickmaia , uma alternativa ou opção adicional para veicular um sentido mais literal é incluir glosas (ver documentação do campo MISC em UD), algo que pode ser feito pelo menos experimentalmente em algumas sentenças.

**Comment by dominickmaia** [comment]
```
# sent_id = Hartt1938:0:0:63
# text = I manha upitera i mimbira yurú.
# text_por = A mãe beijou seu filho.
# text_source = p. 323, No. 63
# text_orig = imáinya opyter imymyra yurú.
# text_por_alt = A mãe beijou a boca do filho.
# text_por_alt_translator = LFdeA
# text_annotator = Dominick Maia Alexandre
1	I	i	PRON	PRON2	Case=Gen|Number=Sing|Person=3|Poss=Yes|PronType=Prs	2	nmod:poss	_	TokenRange=0:1
2	manha	manha	NOUN	N	Number=Sing	3	nsubj	_	TokenRange=2:7
3	upitera	pitera	VERB	V	Person=3|VerbForm=Fin	0	root	_	TokenRange=8:15
4	i	i	PRON	PRON2	Case=Gen|Number=Sing|Person=3|Poss=Yes|PronType=Prs	5	nmod:poss	_	TokenRange=16:17
5	mimbira	mimbira	NOUN	N	Number=Sing	6	nmod:poss	_	TokenRange=18:25
6	yurú	yurú	NOUN	N	Number=Sing	3	obj	_	SpaceAfter=No|TokenRange=26:30
7	.	.	PUNCT	PUNCT	_	3	punct	_	SpaceAfter=No|TokenRange=30:31

# sent_id = Hartt1938:0:0:64
# text = Ixé xapitera kwaá kunhataĩ yurú.
# text_por = Dei um beijo à menina.
# text_source = p. 323, No. 64
# text_orig = ixé xapytér kuae kuñántain yurú.
# text_por_sec = Eu beijei a boca dessa menina.
# text_por_sec_source = Avila (2021)
# text_sec = Ixé apitera kwaá kunhatãi yurú. [Avila 2021]
# text_annotator = Dominick Maia Alexandre
1	Ixé	ixé	PRON	PRON	Number=Sing|Person=1|PronType=Prs	2	nsubj	_	TokenRange=0:3
2	xapitera	pitera	VERB	V	Number=Sing|Person=1|Style=Arch|VerbForm=Fin	0	root	_	ModernForm=apitera|TokenRange=4:12
3	kwaá	kwaá	DET	DEMX	Deixis=Prox|Number=Sing|PronType=Dem	4	det	_	TokenRange=13:17
4	kunhataĩ	kunhataĩ	NOUN	N	Number=Sing	5	nmod:poss	_	TokenRange=18:23
5	yurú	yurú	NOUN	N	Number=Sing	2	obj	_	SpaceAfter=No|TokenRange=24:28
6	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=28:29
```
