### ISSUE TITLE
adicionar palavras no glossário

### ISSUE THREAD

**Issue by dominickmaia** [CompLin/nheengatu#499]
- [x] adicionar palavras do arquivo `new-lemmas.txt` no dicionário do Yauti para anotação automática de novas sentenças

**Comment by leoalenc** [comment]
@dominickmaia, a maioria das novas palavras propostas naquele arquivo `new-lemmas.txt` foi incluída no léxico do Yauti. Quando terminar a revisão, aviso. Sobre a forma _rekũi_, veja https://github.com/CompLin/nheengatu/commit/e461ccac8e5211855d6dd5f84db66f8f6e75801e, relacionado a #500. Via de regra, formas irregulares de verbos não são incluídas no glossário `glossary.json` ou `glossary.txt` nem no léxico, mas criadas no âmbito do módulo `BuildDictionary` do Yauti, atualizado no referido _commit_.
