### ISSUE TITLE
dúvida sobre classificação de "isima"

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#532]
@leoalenc , na sentença `Casasnovas2006:11:30:161` "isima" parece desempenhar a função de núcleo do objeto direto do verbo "umaã".

#### s='''Aintá usika, paá, pitérupi aintá umaã, paá, isima mirĩ, mamé, paá, muíri ara Wakurawá usuwera ukiri. (p. 95, No. 39-40) Chegando lá no meio viram um lugar limpo onde todos os dias o Bacurau ia dormir. - Aintá usika, paá, pitérupi aintá umaã, paá, isima mirí, mamé, paá, muíri ara Wakurawá usuwera ukiri.'''

Ávila (2021, p. 339) prevê a acepção como substantivo:

> isima (var. sima [hist. adap.])
> 1) (adj.)  liso:  Kunhamukú-itá upukwari-putari aé amú í, ti ukwáu, maãresé isima ana i pira 
> uikú. (Amorim, 126, adap.) -  As moças quiseram amarrá-lo outra vez, não puderam, porque seu corpo já estava liso.
> 2) (adj.)  polido, reluzente, envernizado
> 3) (adj.)  [hist.] macio (Costa, 190, 233)
> 4) (adj.)  limpo, sem vegetação (fal. de um terreno, de uma região etc.)
> 5) (s.)  lugar limpo, lugar aberto (ou seja, sem cobertura vegetal grande ou densa):  [...] aintá umaã paá isima mirĩ mamé paá muíri ara wakurawá usuwera ukiri. (Casasnovas, 95, adap.) -  [...] eles viram um pequeno lugar limpo onde todos os dias o bacurau ia dormir.

Fiquei em dúvida se a minha análise da sentença em nheengatu está enviesada pela tradução da sentença em português. A análise de "isima" como substantivo núcleo do objeto direto faz sentido, professor?

A outra possibilidade de análise que me ocorreu foi a de "ukiri" como complemento oracional de "umaã". Nesse caso, fiquei em dúvida sobre a `head`e a `deprel` de "isima" e "mirĩ".

**Comment by leoalenc** [comment]
- [ ] incluir _isima_ como substantivo
