### ISSUE TITLE
anotação de "rakú" como partícula?

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#535]
Sentença `Casasnovas2006:11:32:163`:

#### s='''Umbaá rẽ ambá, anheẽ rakú indé arã/adp, unheẽ, paá, Wakurawá. (p. 96, No. 43) Ainda não terminei, eu lhe falei, disse o Bacurau. - Umbaré ambá, anheé rakú indé arã, unheé, paá, Wakurawá'''

Na sentença acima, eu anotaria  [_rakú_](https://github.com/CompLin/nheengatu/blob/609f454abf132d6bc39b36fc18dfa0ffe506369e/data/glossary.json#L5560)  como ` CERT`, seguindo a acepção de Ávila (2021, p. 653):

> rakú¹ (part.)  na verdade, é verdade que, certamente, é certo que; de fato, realmente (às vezes não se traduz):  ― Anhunté ne murakí kwá? **― Umbaá rẽ ambá, anheẽ rakú indé arã,** [...]. (Casasnovas, 96, adap.) -  ― É só isso o seu trabalho? **― Eu ainda não terminei, eu te disse, [...].**;  ― Awá taá kwá mira puxiwera umbaú waá uikú yané wariã? ― Ixé tẽ rakú, maĩ, paí. Ti ana será pekwáu ixé ne membira? (Amorim, 458, adap.) -  ― Quem é esta gente feia que esta comendo nosso uariá? ― Sou eu mesma, na verdade, mamãe, papai. Não sabem mais que eu sou tua filha?

Concorda, @leoalenc ?

**Comment by leoalenc** [comment]
@juliana-gurgel , glossário atualizado no _commit_ abaixo. Obrigado. Testei a inclusão da nova `xpos` (`NN` deve ser substituído pelos números reais; não revisei a anotação):
```python
>>> s='''Umbaá rẽ ambá, anheẽ rakú/cert indé arã/adp, unheẽ, paá, Wakurawá. (p. 96, No. 43) Ainda não terminei, eu lhe falei, disse o Bacurau. - Umbaré ambá, anheé rakú indé arã, unheé, paá, Wakurawá'''
>>> Yauti.parseExample(s,'Casasnovas2006',NN,43,NN)
# sent_id = Casasnovas2006:NN:NN:43
# text = Umbaá rẽ ambá, anheẽ rakú indé arã, unheẽ, paá, Wakurawá.
# text_eng = I'm not done yet, I told you, said Bacurau.
# text_por = Ainda não terminei, eu lhe falei, disse o Bacurau.
# text_source = p. 96, No. 43
# text_orig = Umbaré ambá, anheé rakú indé arã, unheé, paá, Wakurawá
# text_annotator = Leonel Figueiredo de Alencar
# inputline = Umbaá rẽ ambá, anheẽ rakú/cert indé arã/adp, unheẽ, paá, Wakurawá.
1	Umbaá	umbaá	PART	NEG	PartType=Neg|Polarity=Neg	3	advmod	_	TokenRange=0:5
2	rẽ	rẽ	PART	IMPF	_	3	advmod	_	TokenRange=6:8
3	ambá	mbá	VERB	V	Mood=Ind|Number=Sing|Person=1|VerbForm=Fin	0	root	_	SpaceAfter=No|TokenRange=9:13
4	,	,	PUNCT	PUNCT	_	5	punct	_	TokenRange=13:14
5	anheẽ	nheẽ	VERB	V	Mood=Ind|Number=Sing|Person=1|VerbForm=Fin	3	parataxis	_	TokenRange=15:20
6	rakú	rakú	PART	CERT	PartType=Mod	5	advmod	_	TokenRange=21:25
7	indé	indé	PRON	PRON	Number=Sing|Person=2|PronType=Prs	5	obl	_	TokenRange=26:30
8	arã	arã	ADP	ADP	AdpType=Post	7	case	_	SpaceAfter=No|TokenRange=31:34
9	,	,	PUNCT	PUNCT	_	10	punct	_	TokenRange=34:35
10	unheẽ	nheẽ	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	5	parataxis	_	SpaceAfter=No|TokenRange=36:41
11	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=41:42
12	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	10	advmod	_	SpaceAfter=No|TokenRange=43:46
13	,	,	PUNCT	PUNCT	_	14	punct	_	TokenRange=46:47
14	Wakurawá	wakurawá	NOUN	N	Number=Sing	10	vocative	_	SpaceAfter=No|TokenRange=48:56
15	.	.	PUNCT	PUNCT	_	3	punct	_	SpaceAfter=No|TokenRange=56:57

```
