### ISSUE TITLE
o termo "wakutiwa" de Casasnovas (2006)

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#542]
- [ ] @juliana-gurgel , por favor, refaça a análise de `Casasnovas2006:11:9:1401 aplicando etiqueta especial `=col` (#195 #512 #523 ) ao termo _wakutiwa_

Relaciona-se com #540 .

**Comment by juliana-gurgel** [comment]
@leoalenc , neste [commit](https://github.com/juliana-gurgel/nheengabank/commit/640435c5661d0095862b7b2dde1a5d55e425e0d9) fiz a correção da sentença `Casasnovas2006:11:9:140`.
