### ISSUE TITLE
adicionar "kiasá", variante de "kiasawa", ao glossário?

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#543]
Sentença `Casasnovas2006:11:34:165`:

> #### Rewatá kurí remuatiri ara kiasá rembaú arã ne raíra-itá irumu, unheẽ, paá, i xupé Kurasí.
> #### você vai andar juntando sujeira do ar para comer com seus filhos, falou o Sol para ele.

Ávila (2021, p. 389):
> kiasawa (var. kiasá) (s.)  sujeira, mancha, porcaria

@leoalenc , vi que "[pukusá](https://github.com/CompLin/nheengatu/blob/b5606b0092e9e400bf3106dc1640e121f352f184/data/glossary.json#L5106)", variante de "pukusawa", está no Glossário. Adicionamos "kiasá"?

**Comment by leoalenc** [comment]
- [ ] adicionamos _kiasá_
