### ISSUE TITLE
inclusão e revisão de `Hartt1938:0:0:93`

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#544]
- [x] incluir `Hartt1938:0:0:93` no treebank
- [x] refazer análise de `Hartt1938:0:0:93` (@dominickmaia )
- [x] revisar `Hartt1938:0:0:93`

**Comment by leoalenc** [comment]
@dominickmaia e @Levymelo , a forma _oyusuú_ na ortografia de Avila (2021) fica _uyusuú_> Via de regra, na adaptação ortográfica, devemos nos limitar a converter um grafema noutro, evitando suprimir grafemas, pois geralmente representam fonemas que queremos preservar em prol da fidelidade ao teor do texto original. Nesse caso, temos uma correspondência um a um entre os grafemas das duas ortografias:

o -> u
y -> y
u -> u
s -> s
u -> u
ú -> ú

```python
>>> Yauti.pp('Yawara uyusuú.')
1	Yawara	yawara	NOUN	N	Number=Sing	0	_	_	TokenRange=0:6
2	uyusuú	uyusuú	_	_	_	0	_	_	SpaceAfter=No|TokenRange=7:13
3	.	.	PUNCT	PUNCT	_	1	punct	_	SpaceAfter=No|TokenRange=13:14
```

Anotação atual:

```conllu

# sent_id = Hartt1938:0:0:93
# text = Yawara usuú.
# text_por = O cachorro se mordeu.
# text_source = p. 325, No. 93
# text_orig = yauára oyusuú.
# text_annotator = Dominick Maia Alexandre
1	Yawara	yawara	NOUN	N	Number=Sing	2	nsubj	_	TokenRange=0:6
2	usuú	suú	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	SpaceAfter=No|TokenRange=7:11
3	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=11:12
```

**Comment by dominickmaia** [comment]
Entendido @leoalenc a sentença terá a anotação refeita e adicionada ao repositório local - e neste commit - amanhã. 

@Levymelo peço ajuda para revisarmos novamente o corpus frases.txt

**Comment by Levymelo** [comment]
Estarei de prontidão para o que for necessário.

**Comment by leoalenc** [comment]
Relaciona-se com #293.

**Comment by dominickmaia** [comment]
Anotação revisada de `Hartt1938:0:0:93`, seguindo exemplo da issue #293

```
# sent_id = Hartt1938:0:0:93
# text = Yawara uyusuú.
# text_por = O cachorro se mordeu.
# text_source = p. 325, No. 93
# text_orig = yauára oyusuú.
# text_annotator = Dominick Maia Alexandre
1	Yawara	yawara	NOUN	N	Number=Sing	2	nsubj	_	TokenRange=0:6
2	uyusuú	suú	VERB	V	Mood=Ind|Person=3|VerbForm=Fin|Voice=Mid,Pass	0	root	_	SpaceAfter=No|TokenRange=7:13
3	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=13:14
```
