### ISSUE TITLE
incluir palavras desconhecidas "mirasawa", "Tupí", "Adana" e "Buburi"

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#552]
`Casasnovas2006:12:1:167`
> Kuxiíma, paá, aikwé siiya mira-itá, amú-itá ta **mirasawa** **Tupí**, amú-itá Baré.
> Antigamente existiam muitas tribos indígenas, como a dos Tupi e outra dos Baré.

`Casasnovas2006:12:3:169`
> Nhaã **Tupí** mira-itá pitérupi, paá, aikwé yepé kunhã-itá i sera waá **Adana**.
> Na tribo Tupi, havia uma índia cujo nome era ADANA.

`Casasnovas2006:12:7:173`

> Nhaã, paá, amú mira-itá pitérupi aikwé yepé kurumiwasú, ti usikié ne maã suí, sera, paá, **Buburi**.
> Numa outra tribo, havia um jovem muito valente, chamado Buburi.

Ávila (2021):

> #### mirasawa (s.)
> 1. povo, nação, etnia, clã; linhagem, raça, estirpe;
> 2. [hist] geração;
> 
> #### tupí (s.)
> (...)
> c) povo de língua tupi e indivíduo que integra esse povo: Kuxiima paá aikwé siiya mira-itá, amú-itá ta mirasawa tupí, amú-itá baré. (Casasnovas, 98, adap.) -  Antigamente havia 
> muitas pessoas, algumas eram do povo tupi, outras eram barés.;  [...] asuí umbaá yuíri aikwé nhaã tupí mira-itá kwá rupí. (Leetra Indígena. n. 17, 19, adap.)

**@leoalenc , adicionamos as palavras abaixo?**
- [x] mirasawa `N`
- [x] Tupí `PROPN`
- [x] Adanabuburi `PROPN`
- [x] Buburi `PROPN`

**Comment by leoalenc** [comment]
> `Casasnovas2006:12:1:167`
> 
> > Kuxiíma, paá, aikwé siiya mira-itá, amú-itá ta **mirasawa** **Tupí**, amú-itá Baré.
> > Antigamente existiam muitas tribos indígenas, como a dos Tupi e outra dos Baré.
> 
> `Casasnovas2006:12:3:169`
> 
> > Nhaã **Tupí** mira-itá pitérupi, paá, aikwé yepé kunhã-itá i sera waá **Adana**.
> > Na tribo Tupi, havia uma índia cujo nome era ADANA.
> 
> `Casasnovas2006:12:7:173`
> 
> > Nhaã, paá, amú mira-itá pitérupi aikwé yepé kurumiwasú, ti usikié ne maã suí, sera, paá, **Buburi**.
> > Numa outra tribo, havia um jovem muito valente, chamado Buburi.
> 
> Ávila (2021):
> 
> > #### mirasawa (s.)
> > 
> > 1. povo, nação, etnia, clã; linhagem, raça, estirpe;
> > 2. [hist] geração;
> > 
> > #### tupí (s.)
> > (...)
> > c) povo de língua tupi e indivíduo que integra esse povo: Kuxiima paá aikwé siiya mira-itá, amú-itá ta mirasawa tupí, amú-itá baré. (Casasnovas, 98, adap.) -  Antigamente havia
> > muitas pessoas, algumas eram do povo tupi, outras eram barés.;  [...] asuí umbaá yuíri aikwé nhaã tupí mira-itá kwá rupí. (Leetra Indígena. n. 17, 19, adap.)
> 
> **@leoalenc , adicionamos as palavras abaixo?**
> 
> * [x]  mirasawa `N`

Ok. 
> * [x]  Tupí `PROPN`

É substantivo comum conforme Avila (2021), com o que concordo.
> * [x]  Adana `PROPN`
> * [x]  Buburi `PROPN`

Esses dois não incluímos. Isso já está no fluxograma do @heliolbs. Veja #512 , #164  etc. Usamos /=p.

@juliana-gurgel , veja minhas respostas acima.

**Comment by leoalenc** [comment]
@juliana-gurgel , seguimos agora Avila (2021) em detrimento de Navarro (2016), grafando _kuxiima_ sem acento, fazendo o mesmo com palavras análogas. Ver #66 e #349 . O _treebank_ ainda tem inconsistências nesse quesito.

**Comment by leoalenc** [comment]
@juliana-gurgel , o glossário foi atualizado:

>**mirasawa** (_s._) - **1.** povo, nação, etnia, clã; linhagem, raça, estirpe; **2.** [hist] geração; [...] [Avila 2021]
>**tupí** (_s._) - [...] c) povo de língua tupi [Avila 2021]

**Comment by juliana-gurgel** [comment]
@leoalenc , estou utilizando o `/=p` para atribuir as etiquetas nesses casos, mas ainda achava que os `PROPN` seriam inseridos [nessa parte](https://github.com/CompLin/nheengatu/blob/db628b208960aaa0775994bbdef849c5e5b469e2/src/Nheengatagger.py#L24) do Nheengatagger.

**Comment by juliana-gurgel** [comment]
> @juliana-gurgel , seguimos agora Avila (2021) em detrimento de Navarro (2016), grafando kuxiima sem acento, fazendo o mesmo com palavras análogas. Ver https://github.com/CompLin/nheengatu/issues/66 e https://github.com/CompLin/nheengatu/issues/349 . O treebank ainda tem inconsistências nesse quesito.

Vou corrigir a sentença `Casasnovas2006:12:1:167` antes de fazer o commit, @leoalenc .

**Comment by leoalenc** [comment]
> @leoalenc , estou utilizando o `/=p` para atribuir as etiquetas nesses casos, mas, por não ter visto a issue #164, ainda achava que os `PROPN` seriam inseridos [nessa parte](https://github.com/CompLin/nheengatu/blob/db628b208960aaa0775994bbdef849c5e5b469e2/src/Nheengatagger.py#L24) do Nheengatagger.

@juliana-gurgel , sua dúvida é justificada. Na verdade, eu criei essa lista de nomes próprios no início do desenvolvimento do Yauti (na verdade, acho que na época só tinha o Nheengatagger), quando não havia ainda implementado o mecanismo das etiquetas especiais. Ver #164.
