### ISSUE TITLE
adicionar verbo "yusuantí" ao glossário?

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#553]
`Casasnovas2006:12:9:175`

> Aápe, paá, aintá, **uyusuantí**, ta uyupirú ta upurungitá.
> Ele, numa de suas pescarias, viu Adana e gostou dela.

@leoalenc , no glossário temos [_suantí_](https://github.com/CompLin/nheengatu/blob/c33b210c7a0d0a21dfdc5432cdac44f8a6ad64d0/data/glossary.json#L6812), mas não _yusuantí_.

Ávila (2021):

> #### yusuantí (v. intr. compl. posp.) 
> encontrar-se, deparar-se [com alguém: compl. com irumu; obs.: tb. pode ser empregado como forma recíproca]:  [...] sesá uyusuantí yeperesé aintá irumu. (Amorim, 390, adap.) -  [...] seus olhos depararam-se logo com eles.;  (...)

**Comment by leoalenc** [comment]
> `Casasnovas2006:12:9:175`
> 
> > Aápe, paá, aintá, **uyusuantí**, ta uyupirú ta upurungitá.
> > Ele, numa de suas pescarias, viu Adana e gostou dela.
> 
> @leoalenc , no glossário temos [_suantí_](https://github.com/CompLin/nheengatu/blob/c33b210c7a0d0a21dfdc5432cdac44f8a6ad64d0/data/glossary.json#L6812), mas não _yusuantí_.
> 
> Ávila (2021):
> 
> > #### yusuantí (v. intr. compl. posp.)
> > encontrar-se, deparar-se [com alguém: compl. com irumu; obs.: tb. pode ser empregado como forma recíproca]:  [...] sesá uyusuantí yeperesé aintá irumu. (Amorim, 390, adap.) -  [...] seus olhos depararam-se logo com eles.;  (...)

@juliana-gurgel , não precisamos incluir essa entrada no glossário. Trata-se da voz médio-passiva, ver como anotar esse tipo de forma verbal em #548 .

**Comment by juliana-gurgel** [comment]
Entendido, @leoalenc! A dúvida surgiu por conta de casos como [_mutawarí_](https://github.com/CompLin/nheengatu/blob/c33b210c7a0d0a21dfdc5432cdac44f8a6ad64d0/data/glossary.json#L3532) e [_yumutawarí_](https://github.com/CompLin/nheengatu/blob/c33b210c7a0d0a21dfdc5432cdac44f8a6ad64d0/data/glossary.json#L3537) e porque não havia visto a issue #548.
