### ISSUE TITLE
remoção de pronome espúrio de `Casasnovas2006:12:3:169`

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#557]
- [x] refazer análise de `Casasnovas2006:12:3:169`, removendo o nó 12 com pronome _i_ que inexiste no original
- [x] substituir  _kunhã-itá_, inexistente no original, pela forma _kunhatãi_  como adaptação da forma que de fato ocorre, _kunhaitãi_ 
- [x] passar _kunhatãi_ como argumento representando a forma correta para a função deflagrada por meio da etiqueta especial `=typo`, deixando em `text`  _kunhaitãi_?
- [x] incluir `inputline` com etiqueta desambiguadora da forma _sera_ "o nome dela"

```conllu
# sent_id = 
# text = Nhaã Tupí mira-itá pitérupi, paá, aikwé yepé kunhã-itá i sera waá Adana.
# text_eng = TODO
# text_por = Na tribo Tupi, havia uma índia cujo nome era ADANA.
# text_por_orig = Na tribo Tupi, havia uma índia cujo nome era ADANA,
# text_source = p. 98, No. 3
# text_orig = Nhaã Tupí miraitá pitérupi, paá, aikwé yepé kunhaitãi sera waá Adana.
# text_annotator = Juliana Lopes Gurgel
# acknowledgement = DACILAT Project, FAPESP's Process No. 2022/09158-5
1	Nhaã	nhaã	DET	DEMS	Deixis=Remt|Number=Sing|PronType=Dem	3	det	_	TokenRange=0:4
2	Tupí	tupí	NOUN	N	Number=Sing	3	nmod:poss	_	TokenRange=5:9
3	mira-itá	mira	NOUN	N	Number=Plur	4	nmod:poss	_	TokenRange=10:18
4-5	pitérupi	_	_	_	_	_	_	_	SpaceAfter=No|TokenRange=19:27
4	pitera	pitera	NOUN	N	Number=Sing	9	obl	_	_
5	upé	upé	ADP	ADP	AdpType=Post|Clitic=Yes	4	case	_	_
6	,	,	PUNCT	PUNCT	_	7	punct	_	TokenRange=27:28
7	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	9	advmod	_	SpaceAfter=No|TokenRange=29:32
8	,	,	PUNCT	PUNCT	_	7	punct	_	TokenRange=32:33
9	aikwé	aikwé	PART	EXST	PartType=Exs	0	root	_	TokenRange=34:39
10	yepé	yepé	DET	ART	Definite=Ind|PronType=Art	9	nsubj	_	TokenRange=40:44
11	kunhã-itá	kunhã	NOUN	N	Number=Plur	10	nmod	_	TokenRange=45:54
12	i	i	PRON	PRON2	Case=Gen|Number=Sing|Person=3|Poss=Yes|PronType=Prs	13	nmod:poss	_	TokenRange=55:56
13	sera	sera	NOUN	N	Number=Sing|Number[psor]=Sing|Person[psor]=3|Rel=NCont	15	nsubj	_	TokenRange=59:63
14	waá	waá	PRON	REL	Number=Sing|PronType=Rel	13	nmod:poss	_	TokenRange=62:65
15	Adana	adana	PROPN	PROPN	_	10	acl:relcl	_	SpaceAfter=No|TokenRange=66:71
16	.	.	PUNCT	PUNCT	_	9	punct	_	SpaceAfter=No|TokenRange=71:72
```
@juliana-gurgel , inexiste  no original de `Casasnovas2006:12:3:169` esse pronome _i_. Via de regra, nunca devemos inserir em `text` elementos que inexistem em `text_orig`. Veja que, em _sera_ 'o nome dela', o prefixo _s_ exerce a função de possessivo. Trata-se do prefixo relacional _s_ de não contiguidade. Ver, sobre isso, Avila (2021), Navarro (2016) e Cruz (2011).

**Comment by leoalenc** [comment]
@juliana-gurgel , em Avila (2021), temos:

> **kunhatãi** (var. **kunhatã**; **kunhataĩ**) (s.)  menina, garota, CUNHANTÃ, CUNHATÃ [...]

No glossário, por sua vez, temos:

> **kunhatãi** (_s._) - menina, garota
> **kunhataĩ** (_s._) - var. kunhatãi
> **kunhatã** (_s._) - var. kunhatãi

Dada a forma _kunhaitãi_ de Casasnovas (2006),  optaríamos em `text`, , em princípio, pela primeira variante acima, ou seja, _kunhatãi_. No entanto, parece se tratar de erro tipográfico. NO glossário de Casasnovas (2006, p. 107), consta _kunhantãi_. Você tem outras ocorrências de _kunhaitãi_ nas suas transcrições de Casasnovas (2006)? Creio que é o caso de usar `=typo` (#416 #426), embora talvez se trate de variante de pronúncia individual ou dialetal. @heliolbs , quer ajudar @juliana-gurgel a formatar a _string_ de entrada do Yauti? Isso é relevante para #521 e #512 .

**Comment by leoalenc** [comment]
@juliana-gurgel , veja que a construção _sera waá_ (algo como "que o nome dela") ocorre diversas vezes no _treebank_.

**Comment by juliana-gurgel** [comment]
> _kunhaitãi_

@leoalenc , a sentença `Casasnovas2006:12:5:171`, que ainda vou incluir no treebank, também apresenta a forma _kunhaitãi_ . Nesse caso, acredito que não se trata de erro tipográfico, mas sim um erro meu de adaptação. Podemos optar pela vatiante _kunhaitãi_?

`Casasnovas2006:12:5:171`:
> s='''Nhaã, paá kunhatãi, kwaíra suíwara urikuana awá irumu umendari arama, yepé kurumĩ-wasú kirimbawa waá, sera, paá, Kurukuí.

**Comment by juliana-gurgel** [comment]
> - [ ] refazer análise de `Casasnovas2006:12:3:169`, removendo o nó 12 com pronome _i_ que inexiste no original
> - [ ] substituir _kunhã-itá_, inexistente no original, pela forma que de fato ocorre, _kunhaitãi_, passando _kunhatãi_ como argumento representando a forma correta para a função deflagrada por meio da etiqueta especial `=typo`

@leoalenc , concluí as tarefas com [este commit](https://github.com/juliana-gurgel/nheengabank/commit/25e5a89e39af76414c8824ce9b85bb8030c6488d).

**Comment by leoalenc** [comment]
Nova análise de @juliana-gurgel:

![dependency_tree](https://github.com/user-attachments/assets/a8402b80-b55c-4a88-a846-fb9956f27724)

**Comment by leoalenc** [comment]
Na minha versão, _nhaã_ se liga a _mira-itá_ ("naquela tribo"), ao passo que a partícula de reportativo _paá_  se liga ao predicado principal, ou seja, à partícula existencial _aikwé_:

![dependency_tree](https://github.com/user-attachments/assets/243aaa26-ee6b-44c8-976f-c4745264a93f)

**Comment by leoalenc** [comment]
> > _kunhaitãi_
> 
> @leoalenc , a sentença `Casasnovas2006:12:5:171`, que ainda vou incluir no treebank, também apresenta a forma _kunhaitãi_ . Nesse caso, acredito que não se trata de erro tipográfico, mas sim um erro meu de adaptação. Podemos optar pela vatiante _kunhaitãi_?
> 
> `Casasnovas2006:12:5:171`:
> 
> > s='''Nhaã, paá kunhatãi, kwaíra suíwara urikuana awá irumu umendari arama, yepé kurumĩ-wasú kirimbawa waá, sera, paá, Kurukuí.

@juliana-gurgel , seguimos a política de procurar manter coerência com o dicionário do Avila (2021), escolhendo a forma mais próxima de uma das variantes que propõe como lema. No caso do verbete _kunhatãi_, como mostrei acima, não consta _kunhaitãi_ como variante. Poderíamos registrar essa variante de pronúncia recorrendo ao atributo Style (#398 #335). No entanto, vejo que, no segmento n° 5 da p. 98, consta mesmo  _kunhatãi_. Como _kunhaitãi_   tem aparentemente uma única ocorrência em Casasnovas (2006), vamos considerar essa forma uma caso de [_typo_](https://universaldependencies.org/u/overview/typos.html#misspelled-word). Peço para fechar a questão se estiver tudo claro.

**Comment by leoalenc** [comment]
@juliana-gurgel , veja abaixo como lidar com typos. @heliolbs , esse é um caso concreto interessante de erro de anotação e revisão para exemplificar decisões no fluxograma de #521 .

```python

>>> s='''Nhaã Tupí mira-itá pitérupi, paá, aikwé yepé/art kunhaitãi/=typo:c|kunhatãi sera waá Adana/=p.'''
>>> Yauti.pp(s)
1	Nhaã	nhaã	DET	DEMS	Deixis=Remt|Number=Sing|PronType=Dem	2	det	_	TokenRange=0:4
2	Tupí	tupí	NOUN	N	Number=Sing	3	nmod:poss	_	TokenRange=5:9
3	mira-itá	mira	NOUN	N	Number=Plur	4	nmod:poss	_	TokenRange=10:18
4-5	pitérupi	_	_	_	_	_	_	_	SpaceAfter=No|TokenRange=19:27
4	pitera	pitera	NOUN	N	Number=Sing	0	root	_	_
5	upé	upé	ADP	ADP	AdpType=Post|Clitic=Yes	4	case	_	_
6	,	,	PUNCT	PUNCT	_	4	punct	_	TokenRange=27:28
7	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	4	advmod	_	SpaceAfter=No|TokenRange=29:32
8	,	,	PUNCT	PUNCT	_	4	punct	_	TokenRange=32:33
9	aikwé	aikwé	PART	EXST	PartType=Exs	4	root	_	TokenRange=34:39
10	yepé	yepé	DET	ART	Definite=Ind|PronType=Art	11	det	_	TokenRange=40:44
11	kunhaitãi	kunhatãi	NOUN	N	Number=Sing|Typo=Yes	12	nmod:poss	_	CorrectForm=kunhatãi|TokenRange=45:54
12	sera	sera	NOUN	N	Number=Sing|Rel=Abs	12	nmod:poss	_	TokenRange=55:59
12	sera	sera	NOUN	N	Number=Sing|Number[psor]=Sing|Person[psor]=3|Rel=NCont	12	acl:relcl	_	TokenRange=57:61
13	waá	waá	PRON	REL	Number=Sing|PronType=Rel	12	nsubj	_	TokenRange=60:63
14	Adana	adana	PROPN	PROPN	_	9	nsubj	_	SpaceAfter=No|TokenRange=64:69
15	.	.	PUNCT	PUNCT	_	4	punct	_	SpaceAfter=No|TokenRange=69:70


>>> 
```

**Comment by juliana-gurgel** [comment]
> @leoalenc , a sentença Casasnovas2006:12:5:171, que ainda vou incluir no treebank, também apresenta a forma kunhaitãi . Nesse caso, acredito que não se trata de erro tipográfico, mas sim um erro meu de adaptação. Podemos optar pela vatiante _kunhaitãi_?

> @juliana-gurgel , seguimos a política de procurar manter coerência com o dicionário do Avila (2021), escolhendo a forma mais próxima de uma das variantes que propõe como lema. No caso do verbete _kunhatãi_, como mostrei acima, não consta _kunhaitãi_ como variante. Poderíamos registrar essa variante de pronúncia recorrendo ao atributo Style (#398 #335). No entanto, vejo que, no segmento n° 5 da p. 98, consta mesmo _kunhatãi_. Como _kunhaitãi_ tem aparentemente uma única ocorrência em Casasnovas (2006), vamos considerar essa forma um caso de [_typo_](https://universaldependencies.org/u/overview/typos.html#misspelled-word). Peço para reabrir a questão se houver alguma dúvida ou questionamento.

Professor @leoalenc , na minha pergunta escrevi "vatiante _kunhaitãi_", mas foi um erro tipográfico. Me referia à variante _kunhatãi_. No [commit que corrige o erro de adaptação](https://github.com/juliana-gurgel/nheengabank/commit/25e5a89e39af76414c8824ce9b85bb8030c6488d), coloquei a forma correta em `text`.

> Na minha versão, _nhaã_ se liga a _mira-itá_ ("naquela tribo"), ao passo que a partícula de reportativo _paá_ se liga ao predicado principal, ou seja, à partícula existencial _aikwé_:

Quanto ao commit que corrige a adaptação indevida, na pressa e por conta do cansaço, acabei cometendo o erro de não corrigir o `head` de _nhaã_ e de _paá_. No [primeiro commit](https://github.com/juliana-gurgel/nheengabank/commit/7ed72cb0f976864dccceeb8fff1099465a60ac23), embora tenha cometido o erro de adaptação ortográfica, fiz a ligação correta:

```
1	Nhaã	nhaã	DET	DEMS	Deixis=Remt|Number=Sing|PronType=Dem	3	det	_	TokenRange=0:4
2	Tupí	tupí	NOUN	N	Number=Sing	3	nmod:poss	_	TokenRange=5:9
3	mira-itá	mira	NOUN	N	Number=Plur	4	nmod:poss	_	TokenRange=10:18
4-5	pitérupi	_	_	_	_	_	_	_	SpaceAfter=No|TokenRange=19:27
4	pitera	pitera	NOUN	N	Number=Sing	9	obl	_	_
5	upé	upé	ADP	ADP	AdpType=Post|Clitic=Yes	4	case	_	_
6	,	,	PUNCT	PUNCT	_	7	punct	_	TokenRange=27:28
7	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	9	advmod	_	SpaceAfter=No|TokenRange=29:32
8	,	,	PUNCT	PUNCT	_	7	punct	_	TokenRange=32:33
9	aikwé	aikwé	PART	EXST	PartType=Exs	0	root	_	TokenRange=34:39
```

**Comment by leoalenc** [comment]
@juliana-gurgel, no meu exemplo acima, esqueci de desambiguar a forma _sera_. Segue reaplicação de `Yauti.pp()` com a etiqueta desambiguadora:

```python

>>> s='''Nhaã Tupí mira-itá pitérupi, paá, aikwé yepé/art kunhatã/=mf:m|kunhatãi:r|Standard sera/ncont waá Adana/=p.'''
>>> Yauti.pp(s)
1	Nhaã	nhaã	DET	DEMS	Deixis=Remt|Number=Sing|PronType=Dem	2	det	_	TokenRange=0:4
2	Tupí	tupí	NOUN	N	Number=Sing	3	nmod:poss	_	TokenRange=5:9
3	mira-itá	mira	NOUN	N	Number=Plur	4	nmod:poss	_	TokenRange=10:18
4-5	pitérupi	_	_	_	_	_	_	_	SpaceAfter=No|TokenRange=19:27
4	pitera	pitera	NOUN	N	Number=Sing	0	root	_	_
5	upé	upé	ADP	ADP	AdpType=Post|Clitic=Yes	4	case	_	_
6	,	,	PUNCT	PUNCT	_	4	punct	_	TokenRange=27:28
7	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	4	advmod	_	SpaceAfter=No|TokenRange=29:32
8	,	,	PUNCT	PUNCT	_	4	punct	_	TokenRange=32:33
9	aikwé	aikwé	PART	EXST	PartType=Exs	4	root	_	TokenRange=34:39
10	yepé	yepé	DET	ART	Definite=Ind|PronType=Art	11	det	_	TokenRange=40:44
11	kunhatã	kunhatã	NOUN	N	Number=Sing|Style=Rare	12	nmod:poss	_	StandardForm=kunhatãi|StandardLemma=kunhatãi|TokenRange=45:52
12	sera	sera	NOUN	N	Number=Sing|Number[psor]=Sing|Person[psor]=3|Rel=NCont	12	acl:relcl	_	TokenRange=53:57
13	waá	waá	PRON	REL	Number=Sing|PronType=Rel	12	nsubj	_	TokenRange=58:61
14	Adana	adana	PROPN	PROPN	_	9	nsubj	_	SpaceAfter=No|TokenRange=62:67
15	.	.	PUNCT	PUNCT	_	4	punct	_	SpaceAfter=No|TokenRange=67:68

```
