### ISSUE TITLE
amú expressando o condicional 

### ISSUE THREAD

**Issue by dominickmaia** [CompLin/nheengatu#568]
- [x] considerar inclusão da POS `PART` para amú
- [x] adicionar no glossário: `imú - var. amú`

a questão surgiu durante a anotação de [Hartt1938:0:0:175](https://github.com/dominickmaia/hartt/blob/259065a05fe4862eb96826670d45f2d145f84584/frases.txt#L769), que está presente na definição de Avila (2021, p. 43):

> amú [hist.] (var. emú [hist.]; imú [hist.]; mu [hist.]) (part.) 1) expressa o condicional [era utilizada nos dialetos do rio Solimões e do rio Amazonas, equivalendo à partícula maã do rio Negro. Obs: em interrogações com a partícula taá encontradas na literatura, a partícula amú costuma anteceder taá, enquanto a partícula maã, na fala atual do rio Negro, segue taá] (Stradelli, 319; Tastevin, 606, 619; Hartt, 331 335, 354; Rodrigues, 79, 101, 107, 181, 191, 228, 258, 259, 289, (312?), 328, 329, 331, 333, 334, 211): Se amú arikú mukawa, ayuká amú aintá. (Tastevin, 606, adap.) - Se eu tivesse um rifle, os mataria.; **Sa imú arikú setá kawĩ, aramé imú ameẽ indéu. (Hartt, 331, adap.) - Se eu tivesse bastante cachaça, então eu te daria.**; Arikú ramé amú, ameẽ amú indéu. (Hartt, 335, adap.) - Se eu tivesse, eu te daria.; Awá taá imú usika kwá rupí? (Rodrigues, 258, adap.) - Quem chegaria por aqui?; Maã mu taá amunhã? (Rodrigues, 258, adap.) - O que eu faria?; Arasú mu indé se paya ruakí, karã. (Rodrigues, 258, adap.) - Eu te levaria [para] perto do meu pai, carão. {o mesmo que: maã 1}

**Comment by dominickmaia** [comment]
pesquisando no treebank, encontrei [Casasnovas2006:10:9:128](https://github.com/CompLin/nheengatu/blob/94e614ab3be8d37e9b444144faa616cbf7a50e34/data/corpus/universal-dependencies/yrl_complin-ud-test.conllu#L24905) em que _amú_  é etiquetado como `PRON`, mas também expressa o modo condicional

**Comment by leoalenc** [comment]
@dominickmaia , obrigado por sua observação. A palavra _amú_ no exemplo de Casasnovas é mesmo um pronome, pois a partícula de condicional no rio Negro é _maã_, como explica Avila (2021):

> expressa o condicional [era utilizada nos dialetos do rio Solimões e do rio Amazonas, equivalendo à partícula _maã_ do rio Negro

**Comment by leoalenc** [comment]
@dominickmaia , glossário atualizado:

>**amú** 1 (_pron. indef._) - outro, -a
>**amú** 2 (_part. cond._) - var. maã 5
