### ISSUE TITLE
anotar exemplo 288 de Hartt (1938)

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#571]
- [x] pesquisar _ixupé_ em Avila (2021) e no _treebank_
- [x] corrigir adaptação ortográfica de _ixupé_
- [x] anotar exemplo 288 de Hartt (1938)

**Comment by dominickmaia** [comment]
@leoalenc 
- **xupé**: posposição, alomorfe de _supé_, usada após pronomes de 3p-sg, assim como _arama_ é usada após os pronomes de 1ª e 2ª pessoa. As duas formas funcionam como marcadores de dativo, correspondendo às preposições "para" ou "a" do português.
- Ekũi esupiri semiára **i xupé**.
- anotação:
```conllu
# sent_id = Hartt1938:0:0:288
# text = Ekũi esupiri semiára i xupé.
# text_por = Vá levar minha caça para ele.
# text_source = p. 340, No. 288
# text_orig = ekóin esupúr semiára ixupé.
# text_por_orig = vai levar minha caça a ele.
# text_annotator = Dominick Maia Alexandre
# inputline = Ekũi esupiri semiára i xupé.
1	Ekũi	sú	AUX	AUXFR	Mood=Imp|Number=Sing|Person=2|VerbForm=Fin	2	aux	_	TokenRange=0:4
2	esupiri	supiri	VERB	V	Mood=Imp|Number=Sing|Person=2|VerbForm=Fin	0	root	_	TokenRange=5:12
3	semiára	semiára	NOUN	N	Number=Sing|Number[psor]=Sing|Person[psor]=3|Rel=NCont	2	obj	_	TokenRange=13:20
4	i	i	PRON	PRON2	Case=Gen|Number=Sing|Person=3|PronType=Prs	2	iobj	_	TokenRange=21:22
5	xupé	xupé	ADP	ADP	AdpType=Post	4	case	_	SpaceAfter=No|TokenRange=23:27
6	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=27:28
```

**Comment by leoalenc** [comment]
@dominickmaia , perfeito. Obrigado. Apenas corrigi esta parte:

```conllu
# inputline = Ekũi esupiri semiára/ncont i/pron2 xupé. 
```

O uso das etiquetas evita precisar eliminar linhas manualmente do _output_ do Yauti. Por outro lado, é sempre bom desambiguar as palavras na entrada da ferramenta quando possível, pois certas análises acabam atrapalhando o resultado global.

**Comment by leoalenc** [comment]
Relaciona-se com #479 e #573.
