### ISSUE TITLE
dúvida sobre a classificação de uikú na sentença Casasnovas2006:12:22:188

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#572]
@leoalenc , [neste commit](https://github.com/juliana-gurgel/nheengabank/commit/dece5dd55177d7747c014e5a166c28b3ac5045aa), fiquei com dúvida sobre a classificação de _uikú_ na sentença [`Casasnovas2006:12:22:188`](https://github.com/juliana-gurgel/nheengabank/blob/dece5dd55177d7747c014e5a166c28b3ac5045aa/corpus/universal-dependencies/casasnovas.conllu#L5539). A princípio, anotei a sentença desta maneira:

```conllu
# sent_id = Casasnovas2006:12:22:188
# text = Umaã, paá, aintá mukũi, ta uikú ã waá paraná pitérupi.
# text_eng = TODO
# text_por = Viu os dois que já estavam no meio do rio.
# text_source = p. 99, No. 24
# text_orig = Umaá, paá, aintá mukũi, ta uikuã waá paraná pitérupi.
# text_annotator = Juliana Lopes Gurgel
# inputline = Umaã, paá, aintá/pron mukũi, ta/pron uikú ã waá paraná pitérupi.
1	Umaã	maã	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	SpaceAfter=No|TokenRange=0:4
2	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=4:5
3	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	1	advmod	_	SpaceAfter=No|TokenRange=6:9
4	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=9:10
5	aintá	aintá	PRON	PRON	Number=Plur|Person=3|PronType=Prs	6	det	_	TokenRange=11:16
6	mukũi	mukũi	NUM	CARD	NumType=Card	1	obj	_	SpaceAfter=No|TokenRange=17:22
7	,	,	PUNCT	PUNCT	_	9	punct	_	TokenRange=22:23
8	ta	ta	PRON	PRON	Number=Plur|Person=3|PronType=Prs	9	expl	_	TokenRange=24:26
9	uikú	ikú	AUX	COP	Mood=Ind|Person=3|VerbForm=Fin	13	cop	_	TokenRange=27:31
10	ã	ã	PART	PFV	Aspect=Perf	9	advmod	_	TokenRange=32:33
11	waá	waá	PRON	REL	Number=Sing|PronType=Rel	13	nsubj	_	TokenRange=34:37
12	paraná	paraná	NOUN	N	Number=Sing	13	nmod:poss	_	TokenRange=38:44
13-14	pitérupi	_	_	_	_	_	_	_	SpaceAfter=No|TokenRange=45:53
13	pitera	pitera	NOUN	N	Number=Sing	6	acl:relcl	_	_
14	upé	upé	ADP	ADP	AdpType=Post|Clitic=Yes	13	case	_	_
15	.	.	PUNCT	PUNCT	_	1	punct	_	SpaceAfter=No|TokenRange=53:54
```

Como esperado, surgiram os seguintes erros quando submeti o treebank ao validador:

```
[Line 5608 Sent Casasnovas2006:12:22:188 Node 9]: [L3 Syntax leaf-aux-cop] 'cop' not expected to have children (9:uikú:cop --> 8:ta:expl)
[Line 5610 Sent Casasnovas2006:12:22:188 Node 9]: [L3 Syntax leaf-aux-cop] 'cop' not expected to have children (9:uikú:cop --> 10:ã:advmod)
```

Para corrigir o erro, refiz a anotação da sentença, mas estou em dúvida se a segunda análise está correta.

**Comment by leoalenc** [comment]
> ```
> Casasnovas2006:12:22:188
> ```



> @leoalenc , [neste commit](https://github.com/juliana-gurgel/nheengabank/commit/dece5dd55177d7747c014e5a166c28b3ac5045aa), fiquei com dúvida sobre a classificação de _uikú_ na sentença [`Casasnovas2006:12:22:188`](https://github.com/juliana-gurgel/nheengabank/blob/dece5dd55177d7747c014e5a166c28b3ac5045aa/corpus/universal-dependencies/casasnovas.conllu#L5539). A princípio, anotei a sentença desta maneira:
> 
> ```
> # sent_id = Casasnovas2006:12:22:188
> # text = Umaã, paá, aintá mukũi, ta uikú ã waá paraná pitérupi.
> # text_eng = TODO
> # text_por = Viu os dois que já estavam no meio do rio.
> # text_source = p. 99, No. 24
> # text_orig = Umaá, paá, aintá mukũi, ta uikuã waá paraná pitérupi.
> # text_annotator = Juliana Lopes Gurgel
> # inputline = Umaã, paá, aintá/pron mukũi, ta/pron uikú ã waá paraná pitérupi.
> 1	Umaã	maã	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	SpaceAfter=No|TokenRange=0:4
> 2	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=4:5
> 3	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	1	advmod	_	SpaceAfter=No|TokenRange=6:9
> 4	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=9:10
> 5	aintá	aintá	PRON	PRON	Number=Plur|Person=3|PronType=Prs	6	det	_	TokenRange=11:16
> 6	mukũi	mukũi	NUM	CARD	NumType=Card	1	obj	_	SpaceAfter=No|TokenRange=17:22
> 7	,	,	PUNCT	PUNCT	_	9	punct	_	TokenRange=22:23
> 8	ta	ta	PRON	PRON	Number=Plur|Person=3|PronType=Prs	9	expl	_	TokenRange=24:26
> 9	uikú	ikú	AUX	COP	Mood=Ind|Person=3|VerbForm=Fin	13	cop	_	TokenRange=27:31
> 10	ã	ã	PART	PFV	Aspect=Perf	9	advmod	_	TokenRange=32:33
> 11	waá	waá	PRON	REL	Number=Sing|PronType=Rel	13	nsubj	_	TokenRange=34:37
> 12	paraná	paraná	NOUN	N	Number=Sing	13	nmod:poss	_	TokenRange=38:44
> 13-14	pitérupi	_	_	_	_	_	_	_	SpaceAfter=No|TokenRange=45:53
> 13	pitera	pitera	NOUN	N	Number=Sing	6	acl:relcl	_	_
> 14	upé	upé	ADP	ADP	AdpType=Post|Clitic=Yes	13	case	_	_
> 15	.	.	PUNCT	PUNCT	_	1	punct	_	SpaceAfter=No|TokenRange=53:54
> ```
> 
> Como esperado, surgiram os seguintes erros quando submeti o treebank ao validador:
> 
> ```
> [Line 5608 Sent Casasnovas2006:12:22:188 Node 9]: [L3 Syntax leaf-aux-cop] 'cop' not expected to have children (9:uikú:cop --> 8:ta:expl)
> [Line 5610 Sent Casasnovas2006:12:22:188 Node 9]: [L3 Syntax leaf-aux-cop] 'cop' not expected to have children (9:uikú:cop --> 10:ã:advmod)
> ```
> 
> Para corrigir o erro, refiz a anotação da sentença, mas estou em dúvida se a segunda análise está correta.

@juliana-gurgel , na análise de auxiliares, a teoria UD pode parecer pouco intuitiva, sobretudo quando se está acostumado com uma abordagem que privilegia mais o enfoque sintático, mesmo no quadro na gramática de dependência. O que pareceria mais natural seria analisar o pronome e a partícula como dependentes do auxiliar. No entanto, UD privilegia as palavras de conteúdo e o processamento semântico. Portanto, conforme a própria documentação de UD, cuja obediência o validador verifica, esses dois nós devem ser dependentes do verbo principal. Não há, a meu ver, como tratar _ikú_ nesse exemplo senão como cópula. Existem exemplos análogos no trebank. Por favor, refaça a anotação a partir da primeira versão.

**Comment by leoalenc** [comment]
No caso, em vez de verbo principal, temos um predicado nominal como regente do auxiliar.

**Comment by leoalenc** [comment]
> * [x]  Refazer anotação da sentença 'Casasnovas2006:12:22:188'
> 
> @leoalenc , [neste commit](https://github.com/juliana-gurgel/nheengabank/commit/a8f11fdc0cf8a3b6e7dcb5995b6ea508fd52c1d8) refiz a anotação.

@juliana-gurgel , obrigado. Incluirei a sua nova versão no _commit_ abaixo. Depois vou dar uma olhada nos detalhes, conforme #540.
