### ISSUE TITLE
como anotar as expressões "nẽ maã" e "ti maã"

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#574]
- [x] explicar a política de anotação para _nẽ maã_ ou _ti maã_
- [x] verificar `Sympson1877:0:0:680`: MWE?
- [x] revisar `Avila2021:0:0:716`
- [x] `Navarro2016:3:24:113`
- [x] `Avila2021:0:0:436`
- [x] `Cruz2011:0:0:111`
- [x] `Casasnovas2006:9:30:114` (faltava apenas `ExtPos=PRON`)
- [x] _ti maã_ em `Avila2021:0:0:220`
- [x] _ti maã_ em `Avila2021:0:0:219`: maã não é `IND`, mas `COND`
- [x] revisar `Rodrigues1890:1-1-11:84:84`: _maã_ como partícula de condicional (#568)?
- [x] comparar sentença acima com `Rodrigues1890:3-1:30:30`
- [x] corrigir `Casasnovas2006:12:7:173` (#540)

**Comment by leoalenc** [comment]
Atual análise de `Rodrigues1890:1-1-11:84:84`:

![dependency_tree](https://github.com/user-attachments/assets/66bbf4cb-6717-4254-99f4-ba5e2dcc2b2f)

**Comment by leoalenc** [comment]
Análise de `Casasnovas2006:12:7:173` antes da revisão:

![dependency_tree](https://github.com/user-attachments/assets/3c54961d-4f72-4543-9e0f-03483b41b0d6)

**Comment by leoalenc** [comment]
Análise de `Casasnovas2006:12:7:173` após a revisão:

```conllu
# sent_id = Casasnovas2006:12:7:173
# text = Nhaã, paá, amú mira-itá pitérupi aikwé yepé kurumiwasú, ti usikié nẽ maã suí, sera, paá, Buburi.
# text_eng = TODO
# text_por = Numa outra tribo, havia um jovem muito valente, chamado Buburi.
# text_source = p. 98, No. 9
# text_orig = Nhaã, paá, amú miraitá pitérupi aikwé yepé kurumĩ-wasú, ti usikié ne maã suí, sera, paá, Buburi.
# text_annotator = Juliana Lopes Gurgel
# acknowledgement = DACILAT Project, FAPESP's Process No. 2022/09158-5
# reviewer1 = Leonel Figueiredo de Alencar
1	Nhaã	nhaã	DET	DEMS	Deixis=Remt|Number=Sing|PronType=Dem	5	det	_	SpaceAfter=No|TokenRange=0:4
2	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=4:5
3	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	9	advmod	_	SpaceAfter=No|TokenRange=6:9
4	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=9:10
5	amú	amú	DET	IND	Number=Sing|PronType=Ind	6	det	_	TokenRange=11:14
6	mira-itá	mira	NOUN	N	Number=Plur	7	nmod:poss	_	TokenRange=15:23
7-8	pitérupi	_	_	_	_	_	_	_	TokenRange=24:32
7	pitera	pitera	NOUN	N	Number=Sing	9	obl	_	_
8	upé	upé	ADP	ADP	AdpType=Post|Clitic=Yes	7	case	_	_
9	aikwé	aikwé	PART	EXST	PartType=Exs	0	root	_	TokenRange=33:38
10	yepé	yepé	DET	ART	Definite=Ind|PronType=Art	11	det	_	TokenRange=39:43
11	kurumiwasú	kurumiwasú	NOUN	N	Number=Sing	9	nsubj	_	SpaceAfter=No|TokenRange=44:54
12	,	,	PUNCT	PUNCT	_	14	punct	_	TokenRange=54:55
13	ti	ti	PART	NEG	PartType=Neg|Polarity=Neg	14	advmod	_	TokenRange=56:58
14	usikié	sikié	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	9	parataxis	_	TokenRange=59:65
15	nẽ	nẽ	PART	NEG	ExtPos=PRON|PartType=Neg|Polarity=Neg	14	obl	_	TokenRange=66:68
16	maã	maã	DET	IND	PronType=Ind	15	fixed	_	TokenRange=69:72
17	suí	suí	ADP	ADP	AdpType=Post	15	case	_	SpaceAfter=No|TokenRange=73:76
18	,	,	PUNCT	PUNCT	_	23	punct	_	TokenRange=76:77
19	sera	sera	NOUN	N	Number=Sing|Number[psor]=Sing|Person[psor]=3|Rel=NCont	23	nsubj	_	SpaceAfter=No|TokenRange=80:84
20	,	,	PUNCT	PUNCT	_	21	punct	_	TokenRange=82:83
21	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	23	advmod	_	SpaceAfter=No|TokenRange=84:87
22	,	,	PUNCT	PUNCT	_	21	punct	_	TokenRange=87:88
23	Buburi	buburi	PROPN	PROPN	_	14	parataxis	_	SpaceAfter=No|TokenRange=89:95
24	.	.	PUNCT	PUNCT	_	9	punct	_	SpaceAfter=No|TokenRange=95:96
```

![dependency_tree](https://github.com/user-attachments/assets/e4718151-0a03-47ae-aa21-351894df2098)

**Comment by leoalenc** [comment]
A expressão _ti maã_ constitui MWE que funciona como a partícula de negação _ti_, especialmente quando nega a cópula zero (com sentido existencial) em predicados não verbais, como no exemplo abaixo.

```conllu

```

**Comment by leoalenc** [comment]
A expressão _nẽ maã_ constitui MWE com valor pronominal, equivalente ao indefinido _nada_ em português, como ensina Avila (2021). Talvez se pudesse tratar essa MWE como uma combinação regular da partícula _nẽ_ 'não' e do indefinido _maã_ 'algo', como nas análises corrigidas no _commit_ abaixo. Mas vamos sempre seguir Avila (2021) nesse quesito, pois parece que a expressão constitui algo idiossincrático na língua.

**Comment by leoalenc** [comment]
![dependency_tree](https://github.com/user-attachments/assets/9832716f-4bcc-4353-88e8-62fea3d1cc27)

**Comment by leoalenc** [comment]
Cruz (2011, p. 503):

>Exercendo a função de marcador de modalidade hipotética, _maã_ tem distribuição diferente daquela que apresenta como nome. Em (1029), _maã_ em primeira posição, porque é atraído pelo clítico de negação. Em (1030), _maã_ ocorre combinado a _tenki_ ‘partícula de deôntico de obrigação’ em primeira posição de rema. Em (1031), maã ocorre junto com _saá_, forma registrada por Taylor para o condicional _si_, no Içana na década de 1980.

Cruz (2011, p. 504):

>Em função de marcadador [_sic_] de modalidade hipotética, _maã_ passa a ser considerado sincronicamente como subordinador, como representado na análise justalinear, e seria, portanto, homófona ao _maã_ ‘nome genérico’.

**Comment by leoalenc** [comment]
Atual análise de `Rodrigues1890:1-1-11:84:84`, antes do _commit_ abaixo:

![dependency_tree](https://github.com/user-attachments/assets/9391ec6a-72ab-4648-83a2-43a2bf73ad3e)

**Comment by leoalenc** [comment]
`Rodrigues1890:1-1-11:84:84` após o _commit_:

![dependency_tree](https://github.com/user-attachments/assets/bd274669-d826-47ee-ad68-b7f442906388)

**Comment by leoalenc** [comment]
@juliana-gurgel , o exemplo acima é bastante útil para diversas questões, como #269 , #515 etc., especialmente quando comapramos as duas versões da anotação. Observe que a partícula de condicional funciona como uma espécie de subordinador, justificando a `deprel` `advcl`.

**Comment by juliana-gurgel** [comment]
> @juliana-gurgel , promova no grupo uma discussão sobre a nova análise de `Casasnovas2006:12:7:173` após a minha revisão.

**Discutir na reunião de 20/09/2024**:

- [ ] regente dos sinais de pontuação (ID 18 e 22)
- [ ] a exigência de pronome relativo na relação sintática `acl:relcl` (ver a documentação de UD) e diferentes estruturas sintáticas de orações com _sera_, _waá_ e _sera waá_ (discutimos as análises de `Casasnovas2006:12:7:173`, `Casasnovas2006:12:3:169` e `Navarro2016:0:0:185`)
- [ ] a confiabilidade da tradução portuguesa para análise morfossintática do nheengatu

> Quão confiável é a tradução portuguesa para análise morfossintática do nheengatu? Comparem o que de fato diz o texto nheengatu com a versão em português de Casasnovas (2006), a qual captura o sentido do original nheengatu, mas não a maneira como essa língua codifica esse sentido.

`text` e `text_por` atuais de `Casasnovas2006:12:7:173`:
```conllu
# text = Nhaã, paá, amú mira-itá pitérupi aikwé yepé kurumiwasú, ti usikié nẽ maã suí, sera, paá, Buburi.
# text_por = Numa outra tribo, havia um jovem muito valente, chamado Buburi.
```

@leoalenc, segue a minha proposta de alteração de `text_por` e de inclusão de `text_por_orig`:
```conllu
# text_por = Dizem que, no meio de outra tribo, havia um jovem que não tinha medo de nada, chamado Buburi.
# text_por_orig = Numa outra tribo, havia um jovem muito valente, chamado Buburi.
```

**Comment by leoalenc** [comment]
> > @juliana-gurgel , promova no grupo uma discussão sobre a nova análise de `Casasnovas2006:12:7:173` após a minha revisão.
> 
> **Discutir na reunião de 20/09/2024** (com @heliolbs e @dominickmaia):
> 
> * [x]  regente dos sinais de pontuação (ID 18 e 22)
> * [x]  a exigência de pronome relativo na relação sintática `acl:relcl` (ver a documentação de UD) e diferentes estruturas sintáticas de orações com _sera_, _waá_ e _sera waá_ (discutimos as análises de `Casasnovas2006:12:7:173`, `Casasnovas2006:12:3:169` e `Navarro2016:0:0:185`)
> * [x]  a confiabilidade da tradução portuguesa para análise morfossintática do nheengatu
> 
> > Quão confiável é a tradução portuguesa para análise morfossintática do nheengatu? Comparem o que de fato diz o texto nheengatu com a versão em português de Casasnovas (2006), a qual captura o sentido do original nheengatu, mas não a maneira como essa língua codifica esse sentido.
> 
> `text` e `text_por` atuais de `Casasnovas2006:12:7:173`:
> 
> ```
> # text = Nhaã, paá, amú mira-itá pitérupi aikwé yepé kurumiwasú, ti usikié nẽ maã suí, sera, paá, Buburi.
> # text_por = Numa outra tribo, havia um jovem muito valente, chamado Buburi.
> ```
> 
> Minha proposta de alteração de `text_por` e de inclusão de `text_por_orig`:
> 
> ```
> # text_por = Dizem que, no meio de outra tribo, havia um jovem que não tinha medo de nada, chamado Buburi.
> # text_por_orig = Numa outra tribo, havia um jovem muito valente, chamado Buburi.
> ```
> 
> O que acha, @leoalenc ?
> 
> * [x]  alterar `text_por` de `Casasnovas2006:12:7:173`

@juliana-gurgel , excelente! Bom trabalho. No entanto, no caso de autores como Magalhães (1876), Hartt (1938) e Casasnovas (2006), entre outros, que entendiam profundamente o nheengatu, por conta da nossa política preservacionista do texto original, vamos respeitar as traduções dadas por eles, mesmo quando não literais e bastante afastadas da estrutura do nheengatu. É preciso levar em conta que as línguas costumam expressar conteúdos análogos por meio de estruturas bastante diferentes. Por outro lado, tradução não constitui nosso foco. Em casos, incluí traduções alternativas por meio de `text_por_alt` ou `text_por_gloss`, entre outros atributos de metadados. As questões de adequação de tradução, ligadas `a linguística plaicada, transcendem a área da tipologia linguística ou da linguística _stricto sensu_, seja descritiva, teórica ou computacional. Seria algo a se discutir num prazo mais longo, dada a urgência de tantas _issues_ abertas a serem resolvidas no médio e curto prazo. 
É provável que haja muitas incongruências no _treebank_ atual a respeito da política de tradução, algo a sanarmos no futuro. Há uma grande variedade de atributos relacionados.
Sobre sua sugestão, não acho _no meio de outra tribo_ uma boa tradução alternativa, até porque não ocorre uma palavra equivalente a _tribo_ no nheengatu.  Seria mais algo como _no meio de outras gentes_. Enfim, vocês anotadores e revisores não devem se preocupar em retraduzir o texto nheengatu!

**Comment by leoalenc** [comment]
Acho que foi tudo resolvido. Deixei os metadados de  `Casasnovas2006:12:7:173` intactos, conforme argumentei acima.

**Comment by leoalenc** [comment]
@juliana-gurgel , ao chamar atenção de vocês para a tradução, eu não estava pensando em propor uma nova versão do texto em português. Mas apenas chamar atenção para um fato que anotador(e|a)s e revisor(e|a)s devem levar em conta: quando a estrutura da tradução diverge da original (isso não impede que seja uma boa tradução), precisamos ter o cuidado de não impor a estrutura sintática do português sobre a estrutura sintática do nheengatu a ser construída na anotação.
