### ISSUE TITLE
descompasso entre `text` e `text_por` em `Casasnovas2006:12:9:175`

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#577]
- [x] corrigir descompasso entre `text` e `text_por` em `Casasnovas2006:12:9:175`
- [x] verificar se esse problema se repete em outras sentenças da lenda 12 de Casasnovas (2006)

```conllu
# sent_id = Casasnovas2006:12:8:174
# text = Yepé ara, paá, nhaã Buburi uwatá, usú upinaitika, umaã Adana.
# text_eng = TODO
# text_por = Ele, numa de suas pescarias, viu Adana e gostou dela.
# text_source = p. 98, No. 10
# text_orig = Yepé ara, paá, nhaã Buburi uwatá, usú upinaitika, umaá Adana.
# text_annotator = Juliana Lopes Gurgel
# acknowledgement = DACILAT Project, FAPESP's Process No. 2022/09158-5

# sent_id = Casasnovas2006:12:9:175
# text = Aape, paá, aintá, uyusuantí, ta uyupirú ta upurungitá
# text_eng = TODO
# text_por = Ele, numa de suas pescarias, viu Adana e gostou dela.
# text_source = p. 98, No. 11
# text_orig = Aápe, paá, aintá, uyuswantí, ta uyupirú ta upurungitá
# text_annotator = Juliana Lopes Gurgel
# acknowledgement = DACILAT Project, FAPESP's Process No. 2022/09158-5
# reviewer1 = Leonel Figueiredo de Alencar
# review_status = ongoing
```

**Comment by juliana-gurgel** [comment]
> * [ ]  corrigir descompasso entre `text` e `text_por` em `Casasnovas2006:12:9:175`
> 
> * [ ]  verificar se esse problema se repete em outras sentenças da lenda 12 de Casasnovas (2006)

@leoalenc , fiz a correção de `Casasnovas2006:12:9:175` [neste commit](https://github.com/juliana-gurgel/nheengabank/commit/e036badeb27c6d65932ca1f1ea89bc7967f0f8e4). Verifiquei todas as sentenças da lenda 12 de Casasnovas (2006) e o problema não se repete.
