### ISSUE TITLE
dúvida sobre disponibilidade de etiqueta especial para anotar todos os tokens de "São Gabriel da Cachoeira"

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#581]
`Casasnovas2006:12:34:200`
Casasnovas (2006, p. 100), sentença nº 39-40:
> Iké, yané tawa upé, "**São Gabriel da Cachoeira**", panhẽ yandé yamandwari kwá kunhamukú puranga, sera waá ADANA.
> Nesta nossa cidade de São Gabriel da Cachoeira, continua viva a lembrança de ADANA, A MAIS BELA MOÇA DO RIO NEGRO.

@leoalenc, o Yauti não anota todos os _tokens_ de _São Gabriel da Cachoeira_, como vemos na imagem a seguir:

![image](https://github.com/user-attachments/assets/b8226ae1-81b1-4785-b8e5-1496367ef2a0)

Existe alguma etiqueta especial (como `/n@`) que posso utilizar na _inputline_ para fazer a anotação automática das `XPOS` e das `DEPREL` desses _tokens_?

Com base na sentença `Navarro2016:0:0:56`, eu anotaria todos os _tokens_ como `PROPN`, com `appos` na `DEPREL` de _São_ e `flat` nas `DEPREL` dos demais _tokens_. Seria correto anotar assim?

**Comment by leoalenc** [comment]
> `Casasnovas2006:12:34:200` Casasnovas (2006, p. 100), sentença nº 39-40:
> 
> > Iké, yané tawa upé, "**São Gabriel da Cachoeira**", panhẽ yandé yamandwari kwá kunhamukú puranga, sera waá ADANA.
> > Nesta nossa cidade de São Gabriel da Cachoeira, continua viva a lembrança de ADANA, A MAIS BELA MOÇA DO RIO NEGRO.
> 
> @leoalenc, o Yauti não anota todos os _tokens_ de _São Gabriel da Cachoeira_, como vemos na imagem a seguir:
> 
> ![image](https://private-user-images.githubusercontent.com/77512676/369024936-b8226ae1-81b1-4785-b8e5-1496367ef2a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjUwMDAsIm5iZiI6MTcyNjc2NDcwMCwicGF0aCI6Ii83NzUxMjY3Ni8zNjkwMjQ5MzYtYjgyMjZhZTEtODFiMS00Nzg1LWI4ZTUtMTQ5NjM2N2VmMmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE2NTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNTRhYjhkNjFlOWM3NGZkYzU0OTQzOTQ1Y2JhYzU5OTBmNDQwZDg3ZjMzMzM1ZDExMzVmMGNlNmJiMjk0NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9YLyIQOuNGqyjmoFy_H0g6l0JPJF7rfVcqpWDaaH0EM)
> 
> Existe alguma etiqueta especial (como `/n@`) que posso utilizar na _inputline_ para fazer a anotação automática das `XPOS` e das `DEPREL` desses _tokens_?
> 
> Com base na sentença `Navarro2016:0:0:56`, eu anotaria todos os _tokens_ como `PROPN`, com `appos` na `DEPREL` de _São_ e `flat` nas `DEPREL` dos demais _tokens_. Seria correto anotar assim?

@juliana-gurgel , obrigado pela oportuna pergunta.  Já foi mostrado em _issues_ anteriores como anotar nomes próprios que não estão no glossário nem em lugar nenhum do conjunto de ferramentas e recursos que compõem o Yauti, por exemplo, neste comentário do @heliolbs numa _issue_ na qual você figura como _assigned_: 

https://github.com/CompLin/nheengatu/issues/512#issuecomment-2336845406

Isso evidencia  a necessidade de acompanhar as _issues_. Você também pode usar a eficiente ferramenta de busca do GitHub para encontrar _issues_ abertas ou fechadas sobre uma determinada palavra-chave.
Sobre a deprel, é isso mesmo, conforme a documentação de UD:

https://universaldependencies.org/u/dep/flat.html

O Yauti ainda não consegue anotar todas as _deprels_ e heads corretamente nesse caso. Apenas upos e xpos etc.

**Comment by leoalenc** [comment]
@juliana-gurgel , também tratei da etiqueta especial para nomes próprios em #552.

**Comment by juliana-gurgel** [comment]
> @juliana-gurgel , obrigado pela oportuna pergunta. Já foi mostrado em _issues_ anteriores como anotar nomes próprios que não estão no glossário nem em lugar nenhum do conjunto de ferramentas e recursos que compõem o Yauti, por exemplo, neste comentário do @heliolbs numa _issue_ na qual você figura como _assigned_:

Professor @leoalenc, eu deveria ter dito que estou familiarizada com a anotação de nomes próprios utilizando `/=p`, graças à _issue_ #512, e que tenho utilizado bastante esse comando. A dúvida mesmo, que não ficou clara, era se existia uma maneira de atribuir as etiquetas morfossintáticas e a `DEPREL` ao mesmo tempo. Também tenho utilizado bastante a ferramenta de busca do GitHub e consultado o treebank antes de abrir as issues. 

Mesmo assim, muito obrigada pelas orientações, professor!

**Comment by leoalenc** [comment]
> > @juliana-gurgel , obrigado pela oportuna pergunta. Já foi mostrado em _issues_ anteriores como anotar nomes próprios que não estão no glossário nem em lugar nenhum do conjunto de ferramentas e recursos que compõem o Yauti, por exemplo, neste comentário do @heliolbs numa _issue_ na qual você figura como _assigned_:
> 
> Professor @leoalenc, eu deveria ter dito que estou familiarizada com a anotação de nomes próprios utilizando `/=p`, graças à _issue_ #512, e que tenho utilizado bastante esse comando. A dúvida mesmo, que não ficou clara, era se existia uma maneira de atribuir as etiquetas morfossintáticas e a `DEPREL` ao mesmo tempo. Também tenho utilizado bastante a ferramenta de busca do GitHub e consultado o treebank antes de abrir as issues.
> 
> Mesmo assim, muito obrigada pelas orientações, professor!

@juliana-gurgel , depois, quando vi suas outras _issues_ de hoje,  acabei entendendo, mas era tarde. Você pode usar `/=p` com todos os elementos de _São Gabriel da Cachoeira_, um por um. Ou pudesse usar `São/=adj:o|pt Gabriel/=p da/=upos:x|prep:o|pt Cachoeira/=n:o|pt, mas vi aqui que no momento o Yauti analisa automaticamente _São_ como PROPN e não quebra _da_ em _de_ e _a_ (afinal, isso é do português.) Então acho que a primeira solução é viável à luz de UD.
