### ISSUE TITLE
dúvida sobre DEPREL na sentença 'Casasnovas2006:12:12:178'

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#582]
@leoalenc , fiquei em dúvida se as `DEPREL` de _Buburi_, _mayé_, _Adana_ e _aintá_, na sentença `Casasnovas2006:12:12:178`, estão corretas. Pensei na possibilidade de analisar _Buburi_ como `appos` e _aintá_ como `nsubj`, mas me pareceu, nesse caso, que _aintá_ é mesmo `expl`. Como o senhor analisaria?

```conllu
# sent_id = Casasnovas2006:12:12:178
# text = Asuí, paá, Buburi mayé Adana, aintá usaã ta piá upé ta uyuputari.
# text_eng = TODO
# text_por = O tempo passou e os dois se apaixonaram.
# text_source = p. 99, No. 14
# text_orig = Asuí, paá, Buburi mayé Adana, aintá usaã ta piá upé ta uyuputari.
# text_annotator = Juliana Lopes Gurgel
# inputline = Asuí/advt, paá, Buburi/=p mayé/advla Adana/=p, aintá/pron usaã ta/pron2 piá upé/adp ta/pron uyuputari/=mid.
1	Asuí	asuí	ADV	ADVT	AdvType=Tim	10	advmod	_	SpaceAfter=No|TokenRange=0:4
2	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=4:5
3	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	10	advmod	_	SpaceAfter=No|TokenRange=6:9
4	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=9:10
5	Buburi	buburi	PROPN	PROPN	_	10	nsubj	_	TokenRange=11:17
6	mayé	mayé	ADV	ADVLA	AdvType=Man|PronType=Rel	10	advmod	_	TokenRange=18:22
7	Adana	adana	PROPN	PROPN	_	6	acl:relcl	_	SpaceAfter=No|TokenRange=23:28
8	,	,	PUNCT	PUNCT	_	10	punct	_	TokenRange=28:29
9	aintá	aintá	PRON	PRON	Number=Plur|Person=3|PronType=Prs	10	expl	_	TokenRange=30:35
10	usaã	saã	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	TokenRange=36:40
11	ta	ta	PRON	PRON2	Case=Gen|Number=Plur|Person=3|Poss=Yes|PronType=Prs	12	nmod:poss	_	TokenRange=41:43
12	piá	piá	NOUN	N	Number=Sing	10	obl	_	TokenRange=44:47
13	upé	upé	ADP	ADP	AdpType=Post	12	case	_	TokenRange=48:51
14	ta	ta	PRON	PRON	Number=Plur|Person=3|PronType=Prs	15	nsubj	_	TokenRange=52:54
15	uyuputari	putari	VERB	V	Mood=Ind|Person=3|VerbForm=Fin|Voice=Mid,Pass	10	ccomp	_	SpaceAfter=No|TokenRange=55:64
16	.	.	PUNCT	PUNCT	_	10	punct	_	SpaceAfter=No|TokenRange=64:65
```

**Comment by leoalenc** [comment]
@juliana-gurgel , bom trabalho! Essa construção parece estruturalmente com `Casasnovas2006:1:6:6`, em que _mayé_ tem como complemento um substantivo ou pronome, em vez de oração relativa adverbial `advcl:relcl` (veja esses outros casos). Parece que _mayé Adana_ equivaleria a "tal como Adana" ou "do mesmo modo que Adana".  
Em 7, não me parece, contudo, adequada a `deprel` `acl:relcl`, dada a natureza adverbial do relativo _mayé_.  Num primeiro momento, faria assim, assumindo um verbo implícito em "tal como Adana": 

```conllu
# sent_id = Casasnovas2006:12:12:178
# text = Asuí, paá, Buburi mayé Adana, aintá usaã ta piá upé ta uyuputari.
# text_eng = TODO
# text_por = O tempo passou e os dois se apaixonaram.
# text_source = p. 99, No. 14
# text_orig = Asuí, paá, Buburi mayé Adana, aintá usaã ta piá upé ta uyuputari.
# text_annotator = Juliana Lopes Gurgel
# inputline = Asuí/advt, paá, Buburi/=p mayé/advla Adana/=p, aintá/pron usaã ta/pron2 piá upé/adp ta/pron uyuputari/=mid.
# reviewer1 = LFdeA
1	Asuí	asuí	ADV	ADVT	AdvType=Tim	10	advmod	_	SpaceAfter=No|TokenRange=0:4
2	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=4:5
3	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	10	advmod	_	SpaceAfter=No|TokenRange=6:9
4	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=9:10
5	Buburi	buburi	PROPN	PROPN	_	10	nsubj	_	TokenRange=11:17
6	mayé	mayé	ADV	ADVLA	AdvType=Man|PronType=Rel	10	advmod	_	TokenRange=18:22
7	Adana	adana	PROPN	PROPN	_	6	advcl:relcl	_	SpaceAfter=No|TokenRange=23:28
8	,	,	PUNCT	PUNCT	_	10	punct	_	TokenRange=28:29
9	aintá	aintá	PRON	PRON	Number=Plur|Person=3|PronType=Prs	10	expl	_	TokenRange=30:35
10	usaã	saã	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	TokenRange=36:40
11	ta	ta	PRON	PRON2	Case=Gen|Number=Plur|Person=3|Poss=Yes|PronType=Prs	12	nmod:poss	_	TokenRange=41:43
12	piá	piá	NOUN	N	Number=Sing	10	obl	_	TokenRange=44:47
13	upé	upé	ADP	ADP	AdpType=Post	12	case	_	TokenRange=48:51
14	ta	ta	PRON	PRON	Number=Plur|Person=3|PronType=Prs	15	nsubj	_	TokenRange=52:54
15	uyuputari	putari	VERB	V	Mood=Ind|Person=3|VerbForm=Fin|Voice=Mid,Pass	10	ccomp	_	SpaceAfter=No|TokenRange=55:64
16	.	.	PUNCT	PUNCT	_	10	punct	_	SpaceAfter=No|TokenRange=64:65
```

**Comment by leoalenc** [comment]
A vírgula que separa o sujeito deve ligar-se ao sujeito:

```conllu
# sent_id = Casasnovas2006:12:12:178
# text = Asuí, paá, Buburi mayé Adana, aintá usaã ta piá upé ta uyuputari.
# text_eng = TODO
# text_por = O tempo passou e os dois se apaixonaram.
# text_source = p. 99, No. 14
# text_orig = Asuí, paá, Buburi mayé Adana, aintá usaã ta piá upé ta uyuputari.
# text_annotator = Juliana Lopes Gurgel
# inputline = Asuí/advt, paá, Buburi/=p mayé/advla Adana/=p, aintá/pron usaã ta/pron2 piá upé/adp ta/pron uyuputari/=mid.
# reviewer1 = LFdeA
1	Asuí	asuí	ADV	ADVT	AdvType=Tim	10	advmod	_	SpaceAfter=No|TokenRange=0:4
2	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=4:5
3	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	10	advmod	_	SpaceAfter=No|TokenRange=6:9
4	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=9:10
5	Buburi	buburi	PROPN	PROPN	_	10	nsubj	_	TokenRange=11:17
6	mayé	mayé	ADV	ADVLA	AdvType=Man|PronType=Rel	10	advmod	_	TokenRange=18:22
7	Adana	adana	PROPN	PROPN	_	6	advcl:relcl	_	SpaceAfter=No|TokenRange=23:28
8	,	,	PUNCT	PUNCT	_	5	punct	_	TokenRange=28:29
9	aintá	aintá	PRON	PRON	Number=Plur|Person=3|PronType=Prs	10	expl	_	TokenRange=30:35
10	usaã	saã	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	TokenRange=36:40
11	ta	ta	PRON	PRON2	Case=Gen|Number=Plur|Person=3|Poss=Yes|PronType=Prs	12	nmod:poss	_	TokenRange=41:43
12	piá	piá	NOUN	N	Number=Sing	10	obl	_	TokenRange=44:47
13	upé	upé	ADP	ADP	AdpType=Post	12	case	_	TokenRange=48:51
14	ta	ta	PRON	PRON	Number=Plur|Person=3|PronType=Prs	15	nsubj	_	TokenRange=52:54
15	uyuputari	putari	VERB	V	Mood=Ind|Person=3|VerbForm=Fin|Voice=Mid,Pass	10	ccomp	_	SpaceAfter=No|TokenRange=55:64
16	.	.	PUNCT	PUNCT	_	10	punct	_	SpaceAfter=No|TokenRange=64:65

```

**Comment by leoalenc** [comment]
![dependency_tree](https://github.com/user-attachments/assets/bf97f8ba-5f97-47f6-b4cb-59ea9547d05e)

**Comment by juliana-gurgel** [comment]
@leoalenc, [neste _commit_](https://github.com/juliana-gurgel/nheengabank/commit/1ae006e4d226f6fc18fe46b3b70d8071329565d2) incluí a sentença anotada.

**Comment by leoalenc** [comment]
> A vírgula que separa o sujeito deve ligar-se ao sujeito:
> 
> ```
> # sent_id = Casasnovas2006:12:12:178
> # text = Asuí, paá, Buburi mayé Adana, aintá usaã ta piá upé ta uyuputari.
> # text_eng = TODO
> # text_por = O tempo passou e os dois se apaixonaram.
> # text_source = p. 99, No. 14
> # text_orig = Asuí, paá, Buburi mayé Adana, aintá usaã ta piá upé ta uyuputari.
> # text_annotator = Juliana Lopes Gurgel
> # inputline = Asuí/advt, paá, Buburi/=p mayé/advla Adana/=p, aintá/pron usaã ta/pron2 piá upé/adp ta/pron uyuputari/=mid.
> # reviewer1 = LFdeA
> 1	Asuí	asuí	ADV	ADVT	AdvType=Tim	10	advmod	_	SpaceAfter=No|TokenRange=0:4
> 2	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=4:5
> 3	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	10	advmod	_	SpaceAfter=No|TokenRange=6:9
> 4	,	,	PUNCT	PUNCT	_	3	punct	_	TokenRange=9:10
> 5	Buburi	buburi	PROPN	PROPN	_	10	nsubj	_	TokenRange=11:17
> 6	mayé	mayé	ADV	ADVLA	AdvType=Man|PronType=Rel	10	advmod	_	TokenRange=18:22
> 7	Adana	adana	PROPN	PROPN	_	6	advcl:relcl	_	SpaceAfter=No|TokenRange=23:28
> 8	,	,	PUNCT	PUNCT	_	5	punct	_	TokenRange=28:29
> 9	aintá	aintá	PRON	PRON	Number=Plur|Person=3|PronType=Prs	10	expl	_	TokenRange=30:35
> 10	usaã	saã	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	TokenRange=36:40
> 11	ta	ta	PRON	PRON2	Case=Gen|Number=Plur|Person=3|Poss=Yes|PronType=Prs	12	nmod:poss	_	TokenRange=41:43
> 12	piá	piá	NOUN	N	Number=Sing	10	obl	_	TokenRange=44:47
> 13	upé	upé	ADP	ADP	AdpType=Post	12	case	_	TokenRange=48:51
> 14	ta	ta	PRON	PRON	Number=Plur|Person=3|PronType=Prs	15	nsubj	_	TokenRange=52:54
> 15	uyuputari	putari	VERB	V	Mood=Ind|Person=3|VerbForm=Fin|Voice=Mid,Pass	10	ccomp	_	SpaceAfter=No|TokenRange=55:64
> 16	.	.	PUNCT	PUNCT	_	10	punct	_	SpaceAfter=No|TokenRange=64:65
> ```

@juliana-gurgel , a minha alteração da `head` da vírgula do nó 8 gerou erro de validação. Sua anotação estava correta. Essa regra do validador é aparentemente mais forte do que aquela que determina que a pontuação que separa um dependente deve ligar-se a esse dependente. Portanto, restaurei este aspecto da sua anotação neste repositório.

```bash
python3 validate.py --lang=yrl --max-err=0 ~/complin/nheengatu/data/corpus/universal-dependencies/yrl_complin-ud-test.conllu
[Line 26676 Sent Casasnovas2006:12:12:178 Node 8]: [L3 Syntax punct-is-nonproj] Punctuation must not be attached non-projectively over nodes [6, 7]
Syntax errors: 1
*** FAILED *** with 1 errors

```
