### ISSUE TITLE
revisar anotação de "ti waá" em `Casasnovas2006:11:19:150`

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#588]
`Casasnovas2006:11:19:150`:

> \# text = Remaã indé, ne paya **ti waá** upaka pitupituna usikari arã rembaú arã, unheẽ, paá, waimĩ.
> \# text_por = Olha, teu pai não acorda cedo para procurar comida, dizia a velha.

Avila (2021, p. 751-752):

> NOTA GRAMATICAL²: a part. ti atrai certas posp. (p. ex., arama, esé (r, s), esewara (r, s), pukusawa) e outras part. (p. 
> ex., waá, yepé), que geralmente ocorrem então em posição que lhe é subsequente (exemplos a1, a2, a3). As partículas que têm tendência a ocupar a segunda posição em orações (p. ex., kurí, rẽ, wana, tẽ, pu, paá, será) também ocorrem frequentemente após a part. ti, quando esta inicia a oração, resultando em efeito semelhente à aludida atração (exemplo b). Essa disposição, de fato, muitas vezes ocorre mesmo em situações nas quais a part. ti não inicia a oração, sendo, por exemplo, precedida de um pron. Exemplos:  a1) Aé uyana usika arama uií . > Aé uyana ti arama usika wirandé. - Ele corre para chegar hoje. > Ele corre para não chegar amanhã.;  a2) Aintá umemúi aintá rimbiú aintá urikú resewara tatá. > Aintá ti umemúi aintá rimbiú ti resewara aintá urikú tatá. - Eles cozinham sua comida porque têm fogo. > Eles não cozinham sua comida porque não têm fogo.;  a3) Aité kwá mirá urikú waá i pirera saimbé. > Aité kwá mirá ti waá urikú i pirera saimbé. - Esta é a árvore que tem a casca áspera. > Esta é a árvore que não tem a casca áspera.;  b) Asú kurí ne irumu. > Ti kurí asú ne irumu. - Eu irei contigo. > Eu não irei contigo.

**Comment by leoalenc** [comment]
@juliana-gurgel , o que haveria  alterar? Esta é a análise atual:

![dependency_tree](https://github.com/user-attachments/assets/00a7ad87-224a-44b4-9f97-e3308dd616bc)

O texto nheengatu reza literalmente: "Vê tu teu pai que não acorda [de] madrugada para procurar [algo] para comer [...]"

**Comment by juliana-gurgel** [comment]
> @juliana-gurgel , o que haveria alterar?

Professor @leoalenc, abri a issue para estudar a possibilidade de analisar a estrutura como uma expressão fixa, mas, depois da discussão na issue #591, sanei a minha dúvida.
