### ISSUE TITLE
desdobramento de "marã" em "maã arã" na expressão "ti (ã) marã"

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#591]
- [x] implementar toquenização _marã_ em _maã arã_
- [x] toquenizar _marã_ em _maã arã_ em `Casasnovas2006:6:5:64` (#353 #589 )
- [x] revisar `Casasnovas2006:10:6:125`, separando _marã_ em em _ti arã_ (o Yauti faz isso agora) (@juliana-gurgel )
- [x] verificar outras possíveis ocorrências no _treebank_
- [x] anotar exemplo original de Hartt (1938) citado abaixo por Avila (2021) (@juliana-gurgel , @dominickmaia )
- [x] anotar exemplo de Missão Novas Tribos do Brasil (@leoalenc )

Avila (2021):

> ● ti + maã arama (~ maã arã, marama, marã) 1 (lit., para nada) - (utilizado para dizer que algo ou alguém não tem serventia:) não serve, não presta, não tem valor:  _Kwaá apigawa **ti maã arama**. (Hartt, 355) - Este homem não vale de nada._;  _[...] ti [...] yarikú apigawa umunhã arama taína yandé arama, tuyué [...] **ti ana maã arama**._ (Rodrigues, 105, adap.) - [...] não [...] temos homens para fazer crianças para nós, os velhos [...] não prestam mais.
> 
> ● ti + maã arama (~ maã arã, marama, marã) 2 (lit., para nada) - (utilizado para dizer que algo não é necessário:) não precisa, não é necessário, não há necessidade (de); não tem por que:  ― Reputari será yepé kisé remunuka arã kwá tupasama? ― Umbaá, ti maã arama. - ― Você quer uma faca para cortar essa corda? ― Não, não precisa.;  [...] kwá-itá i katú waá-itá [p. 432] ti maã arama aintá usikari umpusangasara aintá, ma kwá-itá maasiwera-itá aintá usikari aé. (O Novo Testamento em nyengatu, Lucas 5:31, adap.) - [...] os que estão sãos não precisam procurar médico, mas os enfermos procuram-no.
> 
> ● ti + maã arama (~ maã arã, marama, marã) 3 (lit., para nada) - (utilizado para dizer que algo não importa:) não importa, não faz diferença:  _Regustari ramé Jesus Cristo, **ti maã arama** masuiwara indé._ (Missão Novas Tribos do Brasil, 2016, canto 195, modif.) - Se você gosta de Jesus Cristo, não importa de onde você é.
> 
> ● ti + wana (~ wã, ana, ã) + maã arama (~ maã arã, marama, marã) (lit., para mais nada) - (utilizado para dizer que um ser ― pessoa ou animal ― está sem forças ou em péssimo estado:) sem forças, inválido, em más condições, esgotado, acabado:  Nẽ rẽ paá pitérupi manguarí usú uikú, mairamé umaã wainambí ti ã marã uyatikutikú paraname. (Casasnovas, 92, adap.) - O maguari não estava ainda nem na metade do trajeto, quando viu o beija-flor sem forças, boiando no rio.;  [...], ti ã marã tuyu, xega sesatumawasú usururú, ti ã marã, [...] nhaã sesatuma-itá maã-ta iwitera yawé, [...]. (Leetra Indígena. n. 17, 61, adap.) - [...], o velho estava inválido, sua remelona chegava a escorrer, estava inválido, [...] aquelas remelas eram como montanhas, [...].;  [...] ape paá ukaú wã, ti ã marã nhaã yakaré tuyué, [...]. (Leetra Indígena. n. 17, 77, adap.) - [...] então ele já estava embriagado, já estava sem forças aquele velho jacaré [...].

**Comment by leoalenc** [comment]
![dependency_tree](https://github.com/user-attachments/assets/341dc884-d38f-4449-b13e-4bcf3a39f7d1)

**Comment by juliana-gurgel** [comment]
> [ ] anotar exemplo original de Hartt (1938) citado abaixo por Avila (2021) (@juliana-gurgel , @dominickmaia) - @leoalenc 

```conllu
# sent_id = Avila2021:0:0:727
# text = Kwaá apigawa ti maã arama.
# text_eng = TODO
# text_por = Este homem não vale de nada.
# text_source = Hartt, 355, adap.
# text_prim = kuaá apyáua intí maé aráma.
# text_prim_por = êste homem não vale de nada.
# text_prim_por_source = Hartt (1938), p. 355, No. 501
# text_annotator = Juliana Lopes Gurgel
# inputline = Kwaá/demx apigawa/n ti maã/ind arama/adp.
1	Kwaá	kwaá	DET	DEMX	Deixis=Prox|Number=Sing|PronType=Dem	2	det	_	TokenRange=0:4
2	apigawa	apigawa	NOUN	N	Number=Sing	4	nsubj	_	TokenRange=5:12
3	ti	ti	PART	NEG	PartType=Neg|Polarity=Neg	4	advmod	_	TokenRange=13:15
4	maã	maã	DET	IND	PronType=Ind	0	root	_	TokenRange=16:19
5	arama	arama	ADP	ADP	AdpType=Post	4	case	_	SpaceAfter=No|TokenRange=20:25
6	.	.	PUNCT	PUNCT	_	4	punct	_	SpaceAfter=No|TokenRange=25:26
```

**Comment by leoalenc** [comment]
![dependency_tree](https://github.com/user-attachments/assets/9d004d22-5803-47a0-846c-7eb0e7584f44)

**Comment by juliana-gurgel** [comment]
@leoalenc , fiz a anotação da sentença de Hartt e já postei aqui, mas a @dominickmaia fará a revisão da sentença.

**Comment by leoalenc** [comment]
> > [ ] anotar exemplo original de Hartt (1938) citado abaixo por Avila (2021) (@juliana-gurgel , @dominickmaia) - @leoalenc
> 
> ```
> # sent_id = Avila2021:0:0:727
> # text = Kwaá apigawa ti maã arama.
> # text_eng = TODO
> # text_por = Este homem não vale de nada.
> # text_source = Hartt, 355, adap.
> # text_prim = kuaá apyáua intí maé aráma.
> # text_prim_por = êste homem não vale de nada.
> # text_prim_por_source = Hartt (1938), p. 355, No. 501
> # text_annotator = Juliana Lopes Gurgel
> # inputline = Kwaá/demx apigawa/n ti maã/ind arama/adp.
> 1	Kwaá	kwaá	DET	DEMX	Deixis=Prox|Number=Sing|PronType=Dem	2	det	_	TokenRange=0:4
> 2	apigawa	apigawa	NOUN	N	Number=Sing	4	nsubj	_	TokenRange=5:12
> 3	ti	ti	PART	NEG	PartType=Neg|Polarity=Neg	4	advmod	_	TokenRange=13:15
> 4	maã	maã	DET	IND	PronType=Ind	0	root	_	TokenRange=16:19
> 5	arama	arama	ADP	ADP	AdpType=Post	4	case	_	SpaceAfter=No|TokenRange=20:25
> 6	.	.	PUNCT	PUNCT	_	4	punct	_	SpaceAfter=No|TokenRange=25:26
> ```

@juliana-gurgel , parabéns pela presteza e correção da análise. Pode incluir `# reviewer1 = Leonel Figueiredo de Alencar`. Mas talvez eu não tenha sido claro: o objetivo era anotar o exemplo **original** de Hartt e não o exemplo de Avila, que, neste caso, por acaso coincide com a nossa política de adaptação do original de Hartt (texto primário relativamente ao de Avila, como você corretamente identificou). Converse com @dominickmaia para reformatar os metadados do exemplo como `Hartt1938:0:0:501`. Inclu-a como `reviewer2` se ela concordar com a anotação. Sobre nossa política atual em relação aos exemplos de Avila (2021), ver discussão em #575.

**Comment by juliana-gurgel** [comment]
> Mas talvez eu não tenha sido claro: o objetivo era anotar o exemplo **original** de Hartt e não o exemplo de Avila, que, neste caso, por acaso coincide com a nossa política de adaptação do original de Hartt (texto primário relativamente ao de Avila, como você corretamente identificou). Converse com @dominickmaia para reformatar os metadados do exemplo como `Hartt1938:0:0:501`. Inclu-a como `reviewer2` se ela concordar com a anotação.

@dominickmaia , você concorda com a minha anotação?

**Comment by dominickmaia** [comment]
> @juliana-gurgel , parabéns pela presteza e correção da análise. Pode incluir # reviewer1 = Leonel Figueiredo de Alencar. Mas talvez eu não tenha sido claro: o objetivo era anotar o exemplo original de Hartt e não o exemplo de Avila, que, neste caso, por acaso coincide com a nossa política de adaptação do original de Hartt (texto primário relativamente ao de Avila, como você corretamente identificou). Converse com @dominickmaia para reformatar os metadados do exemplo como Hartt1938:0:0:501. Inclu-a como reviewer2 se ela concordar com a anotação. Sobre nossa política atual em relação aos exemplos de Avila (2021), ver discussão em https://github.com/CompLin/nheengatu/issues/575.

> @leoalenc , eu que não entendi a instrução e não conversei primeiro com a @dominickmaia. Nas próximas vezes, faremos a anotação juntas.
> 
> @dominickmaia , você concorda com a minha anotação?

sim, concordo com a anotação. ainda hoje incluo os metadados.

@leoalenc essa sentença ficará sendo a `Hartt1938:0:0:501` ou `Avila2021:0:0:727`? porque, na verdade, estaria diferente da nossa adaptação, já que nos exemplos de Hartt não estamos contraindo a forma _intí_

**Comment by leoalenc** [comment]
> > @juliana-gurgel , parabéns pela presteza e correção da análise. Pode incluir # reviewer1 = Leonel Figueiredo de Alencar. Mas talvez eu não tenha sido claro: o objetivo era anotar o exemplo original de Hartt e não o exemplo de Avila, que, neste caso, por acaso coincide com a nossa política de adaptação do original de Hartt (texto primário relativamente ao de Avila, como você corretamente identificou). Converse com @dominickmaia para reformatar os metadados do exemplo como Hartt1938:0:0:501. Inclu-a como reviewer2 se ela concordar com a anotação. Sobre nossa política atual em relação aos exemplos de Avila (2021), ver discussão em #575.
> 
> > @leoalenc , eu que não entendi a instrução e não conversei primeiro com a @dominickmaia. Nas próximas vezes, faremos a anotação juntas.
> > @dominickmaia , você concorda com a minha anotação?
> 
> sim, concordo com a anotação. ainda hoje incluo os metadados.
> 
> @leoalenc essa sentença ficará sendo a `Hartt1938:0:0:501` ou `Avila2021:0:0:727`? porque, na verdade, estaria diferente da nossa adaptação, já que nos exemplos de Hartt não estamos contraindo a forma _intí_

Isso é importantíssimo para o fluxograma (#521 ). Veja que, segundo meu comentário em #575, visando ao melhor balanceamento do _treebank_, nosso objetivo maior agora são os exemplos originais de tudo que está disponível para consulta, logo, vamos incluir a sentença como `Hartt1938:0:0:501`, adotando a forma e lema _intí_ de Avila (2021), que é a mais próxima do original de Hartt (1938). Se o exemplo já estivesse no treebank como Avila (2021), ainda assim justificaria incluir `Hartt1938:0:0:501` por conta da discrepância entre _ti_ e _intí_. Mas para ficar clara a política: não vamos incluir `Avila2021:0:0:727`. Que se trata de um exemplo que ocorre no dicionário de Avila (2021) vai ser informado nos metadados:

```python
>>> text_sec=Yauti.mkSecTextAvila('Kwaá apigawa ti maã arama. (Hartt, 355) - Este homem não vale de nada.')
>>> text_sec
{'text_sec': 'Kwaá apigawa ti maã arama.', 'text_por_sec': 'Este homem não vale de nada.', 'text_sec_source': 'Avila (2021)', 'text_por_sec_source': 'Avila (2021)'}
>>> Yauti.ppMetadata(text_sec)
# text_sec = Kwaá apigawa ti maã arama.
# text_por_sec = Este homem não vale de nada.
# text_sec_source = Avila (2021)
# text_por_sec_source = Avila (2021)
>>> help(Yauti.parseExample)
Help on function parseExample in module AnnotateConllu:

parseExample(example, pref, textid, index, sentid, copyboard=True, annotator='Leonel Figueiredo de Alencar', check=True, outfile=False, overwrite=False, metadata={}, translate=True, inputline=True)
```
 A variável `text_sec` pode ser passada como parâmetro `metadata=text_sec` na função `parseExample`.
@dominickmaia , se nos exemplos de Hartt (1938) vocês adaptaram intí como ti, isso precisa ser corrigido. Abra _issue_ para tal neste repositório principal. Peça ajuda a @Levymelo e @juliana-gurgel .
Veja em Avila (2021):

```bash
grep -ahiwA 60 "^ti \(var" avila*.txt 
```

> **ti** (var. **intí** [hist.]; **intíu** [hist.]) (_part._)  1) não:  Aé ti umbaú pirá kiinha-ima. -  Ele não come peixe sem pimenta.;  Kwá, se manha, ti usika yandé arama. (Rodrigues, 223, adap.) -  Isto, minha mãe, não é o suficiente para nós.;  Poronominare usemu-putari uka suí, ti aikwé marupí [...]. (Amorim, 157, adap.) -   Poronominare queria sair de casa, não tinha por onde [...].;Anheẽ i xupé ti arama umunhã xibé, aramé piri aé umunhã. -  Eu disse a ela que não fizesse xibé, aí que ela fez mais.;  Ti manungara aé unheẽ (Amorim, 283, adap.) -  Ela não disse coisa alguma.;  Nhaã ti waá usendú ne nheenga reyuká (Rodrigues, 110, adap.) -  Aquele que não der ouvidos à tua ordem tu mata.;  Aité kwá kana ti waá urikú i pinimasawa, aité kwá kana piranga waá. (Payema, 16, adap.) -  Esta é a cana que não tem pinta, esta é a cana vermelha.2) sem [expressando modo, como na construção portuguesa sem + v. no infinitivo]:  Aé uwatá ti umaã sundé kití. -  Ele anda sem olhar para a frente.;  Aintá umaã yepé puranga reté ipeka upitá ií árupi, usú paraná pitera kití, ariré uyuíri sembiiwa kití ti uyumururú. (Amorim, 195, adap.) -  Eles achavam muito bonito o pato ficar em cima da água, ir para o meio do rio, depois voltar para a beirada sem se molhar. ● ti maã1 - não (v. maã3) ● ti maã2 - não hã, não tem (v. maã3) ● ti sa maã ou umbaá sa maã - não é como se; não é que; na verdade não; de forma alguma, em nenhuma hipótese, nunca [trata-se de uma forma de negação enfãtica, utilizada para contrapor duas ideias ou fatos opostos, do tipo: não é X, mas é Y; ou não é como se fosse X, pois é Y; ou não é de forma alguma X, pois é Y etc. Entretanto, a ideia ou fato que se contrapõe à negação pode ser omitida] (v. maã1) ● ti será? - (expressão utilizada ao fim de uma oração, geralmente afirmativa, para solicitar a confirmação do que foi dito. Muitas vezes tem função expletiva:) não é? não é mesmo? não é verdade?:  Puranga mirĩ nhaã yawara, ti será? - É bonitinho aquele cachorro, não é? ● NOTA GRAMATICAL¹: a part. ti ocorre em negações verbais ou de predicados nominais, não sendo frequente sua ocorrência de forma isolada como expressão de negação ou recusa, funções desempenhadas, por exemplo, pela locução ti maã ou pelo advérbio umbaá. Na literatura antiga, no entanto, há alguns poucos exemplos da part. ti desempenhando essa função:  ― I tawá ana será naná, yautí? Yautí usuaxara: ― Yá! Ti rẽ mikura, [...]. (Magalhães, 207, adap.) - ― Já estão amarelos os abacaxis, jabuti? O jabuti respondeu: ― Qual! Ainda não mucura, [...]. ● NOTA GRAMATICAL²: a part. ti atrai certas posp. (p. ex., arama, esé (r, s), esewara (r, s), pukusawa) e outras part. (p. ex., waá, yepé), que geralmente ocorrem então em posição que lhe é subsequente (exemplos a1, a2, a3). As partículas que têm tendência a ocupar a segunda posição em orações (p. ex., kurí, rẽ, wana, tẽ, pu, paá, será) também ocorrem frequentemente após a part. ti, quando esta inicia a oração, resultando em efeito semelhente à aludida atração (exemplo b). Essa disposição, de fato, muitas vezes ocorre mesmo em situações nas quais a part. ti não inicia a oração, sendo, por exemplo, precedida de um 752pron. Exemplos:  a1) Aé uyana usika arama uií . > Aé uyana ti arama usika wirandé. - Ele corre para chegar hoje. > Ele corre para não chegar amanhã.;  a2) Aintá umemúi aintá rimbiú aintá urikú resewara tatá. > Aintá ti umemúi aintá rimbiú ti resewara aintá urikú tatá. - Eles cozinham sua comida porque têm fogo. > Eles não cozinham sua comida porque não têm fogo.;  a3) Aité kwá mirá urikú waá i pirera saimbé. > Aité kwá mirá ti waá urikú i pirera saimbé. - Esta é a árvore que tem a casca áspera. > Esta é a árvore que não tem a casca áspera.;  b) Asú kurí ne irumu. > Ti kurí asú ne irumu. - Eu irei contigo. > Eu não irei contigo. ■ Reg. hist.: [Costa [ti], 209; Tastevin [ɨnti, ti], 622, 671; Coudreau, [inti] 465, 466, 467, [ti] 465; Dias, [nitio] 563, [intio] 570; Seixas [intio], 21; Rondon [ti], 118; Hartt [intí], 319; Magalhães, [inti, intí] 43, 48, 190, 200, 216, 238, [ti, tí] 46, 48, 190, [tio] 200, 272; Rodrigues, [inti] 29, 63, 223, 224, 237, [intio] 29, [ti] 67, 105, 107, 108, 109, 110, 139, 217, 270, 321; Amorim, [nti] 25, 26, 29, 283, 378, [ntyo] 37, 216, 283, 444, [nty] 157, 217, 299, 332, 335; Aguiar, [inti] 61, ['ti] 63, 83; Stradelli, [inti] 256, 381, [nti, intio] 256, [ti] 499; Studart, [inté] 35, [inti] 36] ● (do tupi n'i tybi [na + i + tyb + -i])

**Comment by dominickmaia** [comment]
@leoalenc perfeito, era oq eu estava pensando mesmo... e não, nunca adaptamos intí como ti:

> @leoalenc essa sentença ficará sendo a Hartt1938:0:0:501 ou Avila2021:0:0:727? porque, na verdade, estaria diferente da nossa adaptação, já que nos exemplos de Hartt **não** estamos contraindo a forma intí

ver [aqui](https://github.com/dominickmaia/hartt/blob/c71bb1258861d6ae76afe16955e801221ae3a47f/frases.txt#L2195), inclusive está faltando a adaptação do Avila, mas vou incluir

**Comment by dominickmaia** [comment]
@leoalenc 

```conllu
# sent_id = Hartt1938:0:0:501
# text = Kwaá apigawa intí maã arama.
# text_por = Este homem não vale de nada.
# text_source = p. 355, No. 501
# text_orig = kuaá apyáua intí maé aráma.
# text_annotator = Juliana Lopes Gurgel
# inputline = Kwaá/demx apigawa/n intí maã/ind arama/adp.
# reviewer1 = Leonel Figueiredo de Alencar
# reviewer2 = Dominick Maia Alexandre
1	Kwaá	kwaá	DET	DEMX	Deixis=Prox|Number=Sing|PronType=Dem	2	det	_	TokenRange=0:4
2	apigawa	apigawa	NOUN	N	Number=Sing	4	nsubj	_	TokenRange=5:12
3	intí	intí	PART	NEG	PartType=Neg|Polarity=Neg	4	advmod	_	TokenRange=13:17
4	maã	maã	DET	IND	PronType=Ind	0	root	_	TokenRange=18:21
5	arama	arama	ADP	ADP	AdpType=Post	4	case	_	SpaceAfter=No|TokenRange=22:27
6	.	.	PUNCT	PUNCT	_	4	punct	_	SpaceAfter=No|TokenRange=27:28
```

**Comment by leoalenc** [comment]
> @leoalenc 
> 
> 
> 
> ```conllu
> 
> # sent_id = Hartt1938:0:0:501
> 
> # text = Kwaá apigawa intí maã arama.
> 
> # text_por = Este homem não vale de nada.
> 
> # text_source = p. 355, No. 501
> 
> # text_orig = kuaá apyáua intí maé aráma.
> 
> # text_annotator = Juliana Lopes Gurgel
> 
> # inputline = Kwaá/demx apigawa/n intí maã/ind arama/adp.
> 
> # reviewer1 = Leonel Figueiredo de Alencar
> 
> # reviewer2 = Dominick Maia Alexandre
> 
> 1	Kwaá	kwaá	DET	DEMX	Deixis=Prox|Number=Sing|PronType=Dem	2	det	_	TokenRange=0:4
> 
> 2	apigawa	apigawa	NOUN	N	Number=Sing	4	nsubj	_	TokenRange=5:12
> 
> 3	intí	intí	PART	NEG	PartType=Neg|Polarity=Neg	4	advmod	_	TokenRange=13:17
> 
> 4	maã	maã	DET	IND	PronType=Ind	0	root	_	TokenRange=18:21
> 
> 5	arama	arama	ADP	ADP	AdpType=Post	4	case	_	SpaceAfter=No|TokenRange=22:27
> 
> 6	.	.	PUNCT	PUNCT	_	4	punct	_	SpaceAfter=No|TokenRange=27:28
> 
> ```

@dominickmaia , excelente! Faltaram apenas os atributos relacionados ao exemplo de Ávila, ou seja, text_sec etc., conforme especifiquei no meu comentário acima. Mas pode deixar que eu incluo isso. Esse é um aspecto, por sinal, relevante para a elaboração do seu fluxograma. É importante Que nós estabeleçamos essa conexão com o dicionário de Ávila. Isso é relevante tanto para os usuários do _treebank_ de modo geral, que podem consultar os verbetes onde o exemplo ocorre no dicionário, como para nós mesmos, que podemos comparar mais facilmente a nossa análise com a de Avila, verificando se seguimos ou nos afastamos do dicionarista. Também podemos imaginar aplicações de processamento de linguagem natural que façam uso dessa conexão. Outra questão diz respeito à metodologia e mesmo à ética do trabalho científico. Avila (2021) apresenta o estado da arte na descrição lexical e gramatical do nheengatu. De modo geral, em ciência, devemos partir do estado da arte, mantendo ou modificando determinados aspectos, apresentando, naturalmente, justificativas para tal. Por isso, devemos reconhecer a consulta ao exemplo de Ávila, que deve constituir sempre k o ponto de partida das nossas análises. Esse é um aspecto crucial pra você incluir no seu fluxograma, envolvendo as seguintes decisões: 

1. O exemplo existe no dicionário de Ávila?
2. Caso negativo, incluímos o exemplo como 
`Hartt1938`. Caso afirmativo, esse exemplo já consta do nosso banco de árvores?
3. Caso negativo, incluímos o exemplo como 
`Hartt1938`. Caso afirmativo, a nossa adaptação mais conservadora coincide com a de Ávila?
4. Caso afirmativo, não incluímos duplicata desse exemplo no banco de árvores, apenas inserindo
text_prim, text_prim_source e, se necessário, text_por_prim. Caso negativo, incluímos o exemplo com prefixo `Hartt1938`

**Comment by juliana-gurgel** [comment]
> - [X] revisar `Casasnovas2006:10:6:125`

@leoalenc, em `Casasnovas2006:10:6:125`, a forma _marã_ ainda não está tokenizada em _maã arã_.

> toquenizar marã em maã arã

Professor, a tokenização será feita em todas as ocorrências de _marã_, independentemente de fazerem ou não parte da expressão _ti (ã) marã_?

**Comment by leoalenc** [comment]
> Casasnovas2006:10:6:125

@juliana-gurgel , oportuna pergunta. Sim, no caso da expreesão idiomática segundo Avila (2021),  a qual estamos anotando como sequência normal de palavras, conforme UD, por exemplo em `Casasnovas2006:10:6:125`, precisamos separar. Pode fazer isso?

**Comment by juliana-gurgel** [comment]
> @juliana-gurgel , oportuna pergunta. Sim, no caso da expreesão idiomática segundo Avila (2021), a qual estamos anotando como sequência normal de palavras, conforme UD, por exemplo em `Casasnovas2006:10:6:125`, precisamos separar. Pode fazer isso - @leoalenc 

Refazer anotação de sentenças de Casasnovas (2006) com _marã_:
- [ ] Casasnovas2006:1:4:4
- [X] Casasnovas2006:6:5:64
- [ ] Casasnovas2006:10:6:125 (ver issue #600 )

**Comment by leoalenc** [comment]
@juliana-gurgel , _marã_ só deve ser desmembrado na expressão idiomática, mas não quando funciona como pronome interrogativo. Veja que o dicionário de Ávila apresenta o lema _marã_ também como pronome interrogativo.

**Comment by juliana-gurgel** [comment]
> @juliana-gurgel , aguardo solução da tarefa relacionada a `Casasnovas2006:10:6:125` (vide supra). Falta apenas isso para fechar esta _issue_. - @leoalenc

Tarefa concluída com [este _commit_](https://github.com/juliana-gurgel/nheengabank/commit/daf5fac3772636a3ee4a9f6230457b9a1ff79a7a).

**Comment by leoalenc** [comment]
@juliana-gurgel , veja que na sequência _usú uikú_, o primeiro é verbo principal, enquanto o segundo constitui auxiliar.

```conllu
# sent_id = Casasnovas2006:10:6:125
# text = Nẽ rẽ paá, pitérupi manguarí usú uikú mairamé umaã, wainambí ti ã marã uyatikutikú paraname.
# text_eng = TODO
# text_por = O maguari estava ainda metade do trajeto quando viu o beija-flor quase morrendo na água afogado.
# text_source = p. 92, No. 6-7
# text_orig = Nere paá, pitérupi mangwarí usú uikú mairamé umaã, wainambí tiã marã uyatikutikú paraname.
# text_annotator = Juliana Lopes Gurgel
# text_sec = Nẽ rẽ paá pitérupi manguarí usú uikú, mairamé umaã wainambí ti ã marã uyatikutikú paraname.
# text_por_orig_sec = O maguari não estava ainda nem na metade do trajeto, quando viu o beija-flor sem forças, boiando no rio.
# text_sec_source = Avila (2021)
# text_por_orig_sec_source = Avila (2021)
# acknowledgement = DACILAT Project, FAPESP's Process No. 2022/09158-5
# inputline = Nẽ/neg rẽ paá, pitérupi manguarí usú uikú mairamé/sconjr umaã, wainambí ti ã marã uyatikutikú/=red:l|4:a|t:u|t paraname.
# reviewer1 = LFdeA
1	Nẽ	nẽ	PART	NEG	PartType=Neg|Polarity=Neg	8	advmod	_	TokenRange=0:2
2	rẽ	rẽ	PART	IMPF	_	8	advmod	_	TokenRange=3:5
3	paá	paá	PART	RPRT	Evident=Nfh|PartType=Mod	8	advmod	_	SpaceAfter=No|TokenRange=6:9
4	,	,	PUNCT	PUNCT	_	8	punct	_	TokenRange=9:10
5-6	pitérupi	_	_	_	_	_	_	_	TokenRange=11:19
5	pitera	pitera	NOUN	N	Number=Sing	8	obl	_	_
6	upé	upé	ADP	ADP	AdpType=Post|Clitic=Yes	5	case	_	_
7	manguarí	manguarí	NOUN	N	Number=Sing	8	nsubj	_	TokenRange=20:28
8	usú	sú	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	TokenRange=29:32
9	uikú	ikú	AUX	AUXFS	Mood=Ind|Person=3|VerbForm=Fin	8	aux	_	TokenRange=33:37
10	mairamé	mairamé	SCONJ	SCONJR	_	11	mark	_	TokenRange=38:45
11	umaã	maã	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	8	advcl	_	SpaceAfter=No|TokenRange=46:50
12	,	,	PUNCT	PUNCT	_	18	punct	_	TokenRange=50:51
13	wainambí	wainambí	NOUN	N	Number=Sing	18	nsubj	_	TokenRange=52:60
14	ti	ti	PART	NEG	PartType=Neg|Polarity=Neg	18	advmod	_	TokenRange=61:63
15	ã	ã	PART	PFV	Aspect=Perf	18	advmod	_	TokenRange=64:65
16-17	marã	_	_	_	_	_	_	_	TokenRange=73:77
16	maã	maã	PRON	IND	PronType=Ind	18	obl	_	_
17	arã	arã	ADP	ADP	AdpType=Post|Clitic=Yes	16	case	_	_
18	uyatikutikú	yatikú	VERB	V	Mood=Ind|Person=3|Red=Yes|VerbForm=Fin	11	ccomp	_	TokenRange=78:89
19-20	paraname	_	_	_	_	_	_	_	SpaceAfter=No|TokenRange=90:98
19	paranã	paranã	NOUN	N	Number=Sing	18	obl	_	_
20	me	upé	ADP	ADP	AdpType=Post|Clitic=Yes	19	case	_	_
21	.	.	PUNCT	PUNCT	_	8	punct	_	SpaceAfter=No|TokenRange=98:99

```

**Comment by leoalenc** [comment]
@juliana-gurgel,  percebi que que você usou o atributo `text_por_orig_sec`, que, como comentei noutra ocasião, representa um paradoxo, pois uma fonte não pode ser original e secundária ao mesmo tempo.
