### ISSUE TITLE
`obl` ou `iobj` como `deprel` de complementos adposicionados de "putari" não-oracional?

### ISSUE THREAD

**Issue by heliolbs** [CompLin/nheengatu#593]
Ao analisar a distribuição dos atributos `reviewer`, `reviewer1` e `reviewer2` no _treebank_, notei que `Navarro2016:3:7:96` tem `reviewer2`, mas não tem `reviewer1`. Antes de sugerir essa correção, revisei a sentença para aproveitar o _commit_. Fiquei na dúvida quanto à atribuição de `iobj` como `deprel` do nó adposicionado complemento de ***putari*** não oracional, então comparei com outras ocorrências similares. 

Sentença | `deprel` do nó adposicionado | Sintagma
:--: | :--: | :--:
`Navarro2016:0:0:74` | `obl` | ***Maria supé***
`Navarro2016:3:7:96` | `iobj` | ***se mimbira supé***
`Navarro2016:3:12:101` | `iobj` | ***ne mena supé***
`Navarro2016:3:24:113` | `iobj` | ***indé arama***

Das mais de 90 ocorrências de ***putari*** no _treebank_, apenas essas quatro seguem o padrão de `Navarro2016:3:7:96`. O nó adposicionado das quatro recebeu `deprel` `iobj` com exceção de `Navarro2016:0:0:74`, que recebeu `obl`. A exceção tem embasamento ou seria melhor padronizar a anotação?

O seguinte [_commit_](https://github.com/heliolbs/nheengatu/commit/cb8dcae801ed1e1e17e3c85d17b37e6d4aca0a00) mostra minha revisão de duas das sentenças acima que só tinham uma revisão e acompanha também as outras duas (que já têm duas revisões) para facilitar a comparação entre elas.

**Comment by leoalenc** [comment]
Corrigida a questão envolvendo `reviewer2`. Parece não haver mais erros desse tipo (ver infra). @heliolbs , essa seria ótima questão para um validador. Veja que alguns atributos de metadados precisam de outros. Comecei a modelar isso em `Metadata.py`.

```python
>>> sents=Yauti.extractConlluSents(Yauti.TREEBANK_PATH)
>>> len(sents)
1824
>>> for sent in sents:
	reviewers=[]
	for k,v in sent.metadata.items():
		if k.startswith('reviewer'):
			reviewers.append(k)
	if 'reviewer2' in reviewers and not 'reviewer1' in reviewers:
		print(sent.metadata['sent_id'])

		
>>> for sent in sents:
	reviewers=[]
	for k,v in sent.metadata.items():
		if k.startswith('reviewer'):
			reviewers.append(k)
	if 'reviewer3' in reviewers and not 'reviewer2' in reviewers:
		print(sent.metadata['sent_id'])

		
>>> 
```

**Comment by leoalenc** [comment]
@heliolbs , é mesmo `iobj`, certo?

```conllu
# sent_id = Navarro2016:0:0:74
# text = Maã taá indé reputari Maria supé?
# text_eng = What do you want for Mary?
# text_por = Que você quer para Maria?
# text_source = Lesson 2, p. 18
# text_annotator = DMA
# reviewer1 = Leonel Fiqueiredo de Alencar
# reviewer2 = Hélio Leonam Barroso Silva
1	Maã	maã	PRON	INT	PronType=Int	4	obj	_	TokenRange=0:3
2	taá	taá	PART	CQ	PartType=Int	4	advmod	_	TokenRange=4:7
3	indé	indé	PRON	PRON	Number=Sing|Person=2|PronType=Prs	4	nsubj	_	TokenRange=8:12
4	reputari	putari	VERB	V	Mood=Ind|Number=Sing|Person=2|VerbForm=Fin	0	root	_	TokenRange=13:21
5	Maria	maria	PROPN	PROPN	_	4	iobj	_	TokenRange=22:27
6	supé	supé	ADP	ADP	AdpType=Post	5	case	_	SpaceAfter=No|TokenRange=28:32
7	?	?	PUNCT	PUNCT	_	4	punct	_	SpaceAfter=No|TokenRange=32:33

```

**Comment by heliolbs** [comment]
> Corrigida a questão envolvendo `reviewer2`. Parece não haver mais erros desse tipo (ver infra).

Perfeito, @leoalenc . De fato, só essa sentença tinha esse problema.

> @heliolbs , essa seria ótima questão para um validador. Veja que alguns atributos de metadados precisam de outros. Comecei a modelar isso em `Metadata.py`.

Sim, esse é um tipo de verificação que deve fazer parte das funcionalidades de um verificador. Estou com uns protótipos de funções para checar aspectos do gênero, mas percebo agora que o melhor a ser feito seria concentrar tudo a respeito de metadados no módulo `Metadata.py`. Vou propor algumas delas, por meio de _commits_ no meu repositório, para serem incluídas nesse módulo. A primeira delas será a que mencionei neste [comentário](https://github.com/CompLin/nheengatu/issues/587#issuecomment-2377399491).

**Comment by heliolbs** [comment]
> @heliolbs , é mesmo `iobj`, certo?

Sim, @leoalenc .
