### ISSUE TITLE
reduplicação no verbo "uyatikutikú" em 'Casasnovas2006:10:6:125'

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#600]
`Casasnovas2006:10:6:125`
```conllu
# text = Nẽ rẽ paá, pitérupi manguarí usú uikú mairamé umaã, wainambí ti ã marã uyatikutikú paraname.
# text_por = O maguari estava ainda metade do trajeto quando viu o beija-flor quase morrendo na água afogado.
# text_source = p. 92, No. 6-7
# text_orig = Nere paá, pitérupi mangwarí usú uikú mairamé umaã, wainambí tiã marã uyatikutikú paraname.
```

Professor @leoalenc, quando fiz a anotação da sentença `Casasnovas2006:10:6:125`, por falta de uma solução melhor na ocasião, considerei a forma _uyatikutikú_ como mais uma palavra desconhecida que seria incluída no glossário, considerando que está lematizada em Ávila (2021):

> yatikutikú (v. intr.)
> 1) pender, ficar pendurado
> 2) boiar, flutuar:  Nẽ rẽ paá pitérupi manguarí usú uikú, mairamé umaã wainambí ti ã marã uyatikutikú paraname. (Casasnovas, 92, adap.) -  O maguari não estava ainda nem na metade do trajeto, quando viu o beija-flor sem forças, boiando no rio.
> ◆ [redupl. de yatikú] 

Ao voltar a essa sentença para gerar a anotação com a forma _marã_ tokenizada em _maã arã_ (issue #591), procurei por outra solução para lidar com esse caso de reduplicação em _uyatikutikú_ e encontrei [esta função](https://github.com/CompLin/nheengatu/blob/79da82040acdb1c54562f7600eb94d76365cd591/src/AnnotateConllu.py#L2008) no `AnnotateConllu` e a etiqueta especial `=red:l|4` utilizada na anotação da sentença `Cruz2011:0:0:119`.

Para entender o funcionamento da função `handlePartialRedup`, testei gerar a anotação extraindo diferentes quantidades de segmentos da palavra (de 0 a 7). Depois de alguns testes, percebi que a função não lida com reduplicações onde a parte repetida está no final da palavra.  Também fiquei me perguntando se, mesmo que extraísse a parte final, a função conseguiria "adivinhar" o _lemma_ correto sem o acento agudo de _yatikú_ que, na forma reduplicada, foi transferido para o último _u_.

Como proceder neste caso?

Relaciona-se a #521 , #512 , #578 .

**Comment by heliolbs** [comment]
Questão muito interessante, @juliana-gurgel . Neste [comentário](https://github.com/CompLin/nheengatu/issues/512#issuecomment-2338016161) de #512 , @leoalenc comentou minha análise de um caso de reduplicação e me delegou algumas tarefas que deixei pendentes. Tentei aplicar o Yauti ao termo em questão da sua sentença e esbarrei nos mesmos problemas que você. Analisando a função que você citou, vemos que a terceira linha do corpo de `handlePartialRedup` toma como lema o final da forma reduplicada:

`lemma=entry['lemma'][length:]`

Para tomar como lema o início da forma reduplicada, a sintaxe deveria ser algo como:

`lemma=entry['lemma'][:length]`

Estou retomando as tarefas pendentes sobre o assunto para ver o que Cruz (2011) fala a respeito desses casos. Caso haja embasamento, talvez seja necessário que essa função seja mais complexa. Retorno em breve.

**Comment by leoalenc** [comment]
@juliana-gurgel , parece-me que, conforme Cruz (2011, p. 81), essa reduplicação seria irregular, pois não segue o modelo produtivo da reduplicação parcial:

>Em Nheengatú, há apenas um processo produtivo de reduplicação morfológica, restrito a bases verbais (v. 7.2). Trata-se da cópia do pé métrico acentuado da base verbal. Como vimos em 2.6, embora o padrão acentual seja lexical, o ritmo é iâmbico, ou seja, os pés métricos são formados da direita para esquerda com proeminência à direita.

Ou seja, _yuká_ 'matar' reduplica-se como _yukayuká_ 'matar repetidamente' (Cruz, 2011, p. 82) ou _yuká-yuká_ como prefere Avila (2021, p. 707) (parece haver alguma inconsistência no dicionário a respeito desse uso do hífen): 

>_Apigawa usika, unheẽ: ― Awá-ta **uyuká-yuká** kwá mikura-itá? Umutirika aé pé suí, usú ana._ (Magalhães, 244, adap.) - O homem chegou e disse: ― Quem andou matando essas mucuras? Arredou-a do caminho e foi-se.

Por outro lado, de _munuka_ 'cortar' deriva _munumunuka_ 'cortar repetidamente' (Cruz, 2011, p. 82. Implementei no Yauti os processos reduplicativos regulares (ou produtivos):

```python

>>> Yauti.pp('Kurumĩ upetepeteka/=red:l|4 yawara.')

```
```conllu
1	Kurumĩ	kurumĩ	NOUN	N	Number=Sing	2	nsubj	_	TokenRange=0:6
2	upetepeteka	peteka	VERB	V	Mood=Ind|Person=3|Red=Yes|VerbForm=Fin	0	root	_	TokenRange=7:18
3	yawara	yawara	NOUN	N	Number=Sing	2	obj	_	SpaceAfter=No|TokenRange=19:25
4	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=25:26

```
```conllu
>>> Yauti.pp('Kurumĩ uyukayuká/=red:l|4:a|t yawara.')
```
```conllu
1	Kurumĩ	kurumĩ	NOUN	N	Number=Sing	2	nsubj	_	TokenRange=0:6
2	uyukayuká	yuká	VERB	V	Mood=Ind|Person=3|Red=Yes|VerbForm=Fin	0	root	_	TokenRange=7:16
3	yawara	yawara	NOUN	N	Number=Sing	2	obj	_	SpaceAfter=No|TokenRange=17:23
4	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=23:24

```python
>>> Yauti.pp('Kurumĩ umunumunuka/=red:l|4:a|f pakúa.')
```
```conllu
1	Kurumĩ	kurumĩ	NOUN	N	Number=Sing	2	nsubj	_	TokenRange=0:6
2	umunumunuka	munuka	VERB	V	Mood=Ind|Person=3|Red=Yes|VerbForm=Fin	0	root	_	TokenRange=7:18
3	pakúa	pakúa	NOUN	N	Number=Sing	2	obj	_	SpaceAfter=No|TokenRange=19:24
4	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=24:25
```
```python
>>> Yauti.pp('Kurumĩ uyuká-yuká buya.')
```
```conllu
1	Kurumĩ	kurumĩ	NOUN	N	Number=Sing	2	nsubj	_	TokenRange=0:6
2	uyuká-yuká	yuká	VERB	V	Mood=Ind|Person=3|Red=Yes|VerbForm=Fin	0	root	_	TokenRange=7:17
3	buya	buya	NOUN	N	Number=Sing	2	obj	_	SpaceAfter=No|TokenRange=18:22
4	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=22:23

```

**Comment by heliolbs** [comment]
@leoalenc , quando ocorrerem reduplicações não produtivas, uma vez que são raras, os anotadores e revisores humanos devem adaptar manualmente, correto?

**Comment by leoalenc** [comment]
@juliana-gurgel , observe que não está clara a ideia de repetição nesse caso de reduplicação. Avila (2021,  863-864):

>**yatikú** (_v. intr._)  **1)** pender, estar pendurado, estar suspenso; pendurar-se, suspender-se:  Aape paá urubú usú sakakwera merupí, mairamé umaã wirawasú, uyatikú uikú mirá resé. (Casasnovas, 67, adap.) -   Aí, dizem, o urubu foi atrás dele devagar, quando viu o gavião, ele estava pendurado no pau.;  Reruri se mirapara uyatikú uikú waá uka itapúa kití. (Stradelli, 374, adap.) -   Traz o meu arco que está pendurado no prego da casa. **2)** boiar, flutuar:  Aiwã paá uyuuka aité nhaã uyatikú waá paraná árupi mirĩ, pirá-itá samburá paá ta umbeú tuyu-itá, [...]. (Leetra Indígena. n. 17, 65, adap.) -  Então ele pegou aquela pequena [planta] que flutua sobre o rio, o samburá dos peixes, dizem os velhos, [...].;  [...] umaité, akwawa, manungara buxu kwera nhaã uyatikú waá paraná árupi, [...]. (Muniz, 77) -  [...] ele pensou, eu acho, que eram as vísceras de algo aquilo que estava boiando sobre o rio, [...].;  Yandé será yakwáu yasitatá uwari iwaka suí, uyatikú uri uikú ií ara rupí kuíri! (Amorim, 359, adap.) -  Acaso nós sabemos se uma estrela caiu do céu, vem agora flutuando por cima da água! {o mesmo que: wiwí 3} ■ Reg. hist.: [Tastevin [yaticú], 679; Amorim [iatiku], 359; Stradelli [iaticũ], 200, 374] ● (do tupi îasekó) 

No entanto, como o verbo parece não dinâmico apesar da natureza conjugacional de primeira classe (Avila, 2021, p. 127), podemos especular que a reduplicação expressaria duratividade do estado ou processo.
Creio que não deve ser prioridade analisar tais casos irregulares por meio de uma regra, algo até paradoxal. Podemos, portanto, tranquilamente lematizar o verbo como  _yatikutikú_, que vou incluir no glossário. É um caso análogo a _kurumiwasú_ do ponto de vista semântico, ver meu artigo Alencar (2024b).

- [ ] incluir _yatikutikú_ no glossário

**Comment by leoalenc** [comment]
> @leoalenc , quando ocorrerem reduplicações não produtivas, uma vez que são raras, os anotadores e revisores humanos devem adaptar manualmente, correto?

@heliolbs , como no caso de todo processo derivacional não produtivo, o procedimento recomendado é não anotar o processo, recorrendo à inclusão no glossário e léxico do lema correspondente de Avila (2021). 
@heliolbs e @juliana-gurgel , fechei a questão com a conclusão da tarefa que formulei. Se @heliolbs julgar que deva haver mudanças no código do Yauti, pode abrir _issue_ a respeito. 
Vejam o que ocorre quando aplicamos a regra sobre o exemplo:

```python
>>> s='''Nẽ/neg rẽ paá, pitérupi manguarí usú uikú mairamé/sconjr umaã, wainambí ti ã marã uyatikutikú/=red:l|4:a|t paraname.'''
>>> Yauti.pp(s)
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#42>", line 1, in <module>
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3254, in pp
    print(parseSentence(s).serialize())
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3004, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2569, in mkConlluSentence
    new=handlePartialRedup(form,length,xpos='V',orig=orig, orig_form=orig_form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2012, in handlePartialRedup
    handleOrig(new,lemma,orig, orig_form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1965, in handleOrig
    _isInLexicon(lemma)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1953, in _isInLexicon
    raise Exception(f"Lemma '{lemma}' not found in the lexicon")
Exception: Lemma 'kutikú' not found in the lexicon
```
Ou seja, a regra obviamente trata _yati_ como prefixo reduplicativo, gerando a base inexistente _kutikú_, assim como lematiza _umunumunuka_ como _munuka_.
Haveria muito que melhorar nesse tratamento que dei à reduplicação, uma solução prática. Para tanto, seria necessária uma investigação profunda do mecanismo desse processo derivacional em nheengatu e a utilização de metodologia consagrada em morfologia computacional.

**Comment by leoalenc** [comment]
@heliolbs e @juliana-gurgel , baseei minha conclusão na minha interpretação, que pode ter sido superficial , da abordagem de Aline da Cruz. Mas não descarto que essa formação possa ser morfologicamente 
regular à luz da teoria dela. Algo que talvez vocês queiram investigar.

**Comment by leoalenc** [comment]
@juliana-gurgel , estou reabrindo a _issue_, conforme https://github.com/CompLin/nheengatu/issues/601#issuecomment-2392457121. Agradeço-lhe por ter trazido essa questão à baila.

**Comment by leoalenc** [comment]
@juliana-gurgel , feche por favor esta issue quando fizer revisão da sentença.

**Comment by leoalenc** [comment]
Segundo Cruz (2011, p. 302), _yatiku_ (_yatikú_) é verbo na voz média, _ya-_ constituindo "vestígio" do morfema _je_- do tupinambá.

**Comment by juliana-gurgel** [comment]
> @juliana-gurgel , feche por favor esta issue quando fizer revisão da sentença.

Revisão feita [neste _commit_](https://github.com/juliana-gurgel/nheengabank/commit/daf5fac3772636a3ee4a9f6230457b9a1ff79a7a).
