### ISSUE TITLE
revisão Casasnovas2006:12:23:189 e Avila2021:0:0:511 + dúvida

### ISSUE THREAD

**Issue by dominickmaia** [CompLin/nheengatu#613]
[não modifiquei nada nas 2 sentenças](https://github.com/juliana-gurgel/nheengabank/commit/f80b4f2ac7b6aedd02107a84d6c572f91ba26fd3), que estão iguais, mas fiquei com uma dúvida: estranhei _rakwera_ ser `obj` de _usú_. já que _akwera_ pode ser adposição, faria sentido então colocar _rakwera_ como `ADP` e `case`, em vez de `NOUN`, e _aintá_ como `obl` (atrás deles) ou fica incoerente ? @heliolbs 

Avila, 2021, p. 228: 
> akakwera (r, s) (var. akwé (r, s); akwera (r, s) ) (posp.) 1) atrás de; no encalço de

Avila, 2021, p. 686:
> 3) (nominaliza complementos circunstanciais, dando ideia de causa, modo, tempo etc.) [o complemento nominalizado pode ter função de substantivo ou função adverbial (v. a nota gramatical )]: a) (com cononatação de causa): [...] amú upuri ukara kití usikiesawa. (Rodrigues, 45, adap.) - [...] outro pulou para fora de medo.; Kwá mira, taité, urirí upuãmu usikiesá. (Casasnovas, 85) - O homem, coitado, ficou de pé tremendo de medo.; Ape paá wakurawá upitá surí, surisawa paá umunhã yepé dabukurí. (Comunidade Indígena Anamuím, 23, adap.) - Então o bacurau ficou feliz, de tanta felicidade fez um dabucuri.; b) (com cononatação de modo): Nhaã apigawa uyuíri, usú ana suka kití usikiesawa. (Rodrigues, 40, adap.) - Aquele homem voltou, foi-se para casa com medo.; I piaiwasawa paá, upisika igara usú arã aintá rakwera. (Casasnovas, 99) - Estando zangado, pegou a canoa para ir atrás deles.;

**Comment by dominickmaia** [comment]
contribui com #599

**Comment by heliolbs** [comment]
@dominickmaia , também concordo com a anotação original com exceção do ponto que você levantou. Não sei qual acepção de ***rakwera*** utilizar. Também me parece fazer mais sentido posposição, mas há outras ocorrências dessa palavra como substantivo no banco de árvores. Cruz (2011) trata do termo como "substantivo relativo". Precisarei de mais tempo para analisar essa questão.

**Comment by heliolbs** [comment]
Com o código abaixo, vi que apenas três sentenças têm ***rakwera*** com `deprel` `obj`, sendo que duas delas são referências cruzadas uma da outra:

```
import Yauti
sents = Yauti.extractConlluSents(Yauti.TREEBANK_PATH)

for sent in sents:
	verb = sent.filter(lemma='sú', upos='VERB')
	for v in verb:
		branches = sent.filter(head=v['id'])
		for b in branches:
			try:
				if b['deprel'] == 'obj':
					print(sent.metadata['sent_id'])
			except KeyError:
				pass

			
Avila2021:0:0:511
Casasnovas2006:5:8:56
Casasnovas2006:12:23:189
```

Ou seja, é muito raro esse termo receber essa  `deprel`, o que não quer dizer que esteja errado.

**Comment by heliolbs** [comment]
Em comparação, o seguinte código mostra que há 99 ocorrências do verbo ***sú*** como `head` de um `obl`.

```
obl = []
for sent in sents:
	verb = sent.filter(lemma='sú', upos='VERB')
	for v in verb:
		branches = sent.filter(head=v['id'])
		for b in branches:
			try:
				if b['deprel'] == 'obl':
					obl.append(sent.metadata['sent_id'])
			except KeyError:
				pass

			
len(obl)
99
```
Ou seja, é muito mais frequente o verbo ***sú*** ter um `obl` do que um `obj`.

**Comment by leoalenc** [comment]
@heliolbs e @dominickmaia , obrigado por chamar atenção a esse erro. De fato, trata-se de `adp`, embora exista o termo também como substantivo, segundo Avila (2021):

>akakwera ({t}, r, s) (var. akwera (r, s)1) (s.)  parte posterior, traseira; retaguarda [...]
