### ISSUE TITLE
revisão Casasnovas2006:10:11:130 e Avila2021:7:2:48

### ISSUE THREAD

**Issue by dominickmaia** [CompLin/nheengatu#615]
@heliolbs havia apenas 1 diferença entre as anotações, na qual concordo com a escolha feita em `Avila2021:7:2:48`. Assim, [mudei a `deprel` de _waá_](https://github.com/juliana-gurgel/nheengabank/commit/ed72095db4742f6d90e7a3d44eb576dd1849efea) em `Casasnovas2006:10:11:130 `de `nsubj` para `obl`, entendendo que o relativo se liga ao verbo _sú_ e indica o local/destino ao qual o sujeito chegou.

**Comment by dominickmaia** [comment]
contribui com #599

**Comment by heliolbs** [comment]
@dominickmaia , concordo com a anotação original e com sua substituição da `deprel` do nó ***waá*** de `nsubj` para `obl`. Registrei neste [_commit_](https://github.com/juliana-gurgel/nheengabank/commit/8e54f3cee84fe8d7a75cd7caa15c6ba39afe534e) a inclusão do atributo `reviewer2` e a substituição da sigla dos anotadores pelos nomes por extenso.

**Comment by leoalenc** [comment]
Por ter `text` idêntico ao da duplicata com prefixo `Avila2021`, @heliolbs e @dominickmaia , `Casasnovas2006:10:11:130` havia sido deletada faz algum tempo do _treebank_.
