### ISSUE TITLE
corrigir valor do `sent_id` de `Hart1938:0:0:91`

### ISSUE THREAD

**Issue by heliolbs** [CompLin/nheengatu#618]
Relaciona-se com #411 :

- [x] adicionar o "t" ausente no valor do atributo `sent_id` de `Hart1938:0:0:91`

**Comment by leoalenc** [comment]
Obrigado, @heliolbs , mais uma coisa importantíssima para verificação automático por meio de um validador, a ser integrado no nosso _workflow_.
