### ISSUE TITLE
revisar sentenças 'Casasnovas2006' anotadas por @leoalenc

### ISSUE THREAD

**Issue by juliana-gurgel** [CompLin/nheengatu#619]
- [x] Casasnovas2006:0:0:16
- [x] Casasnovas2006:0:0:17
- [x] Casasnovas2006:0:0:18
- [x] Casasnovas2006:0:0:19
- [x] Casasnovas2006:0:0:20
- [x] Casasnovas2006:0:0:21
- [x] Casasnovas2006:0:0:22
- [x] Casasnovas2006:0:0:23
- [x] Casasnovas2006:7:1:1
- [x] Casasnovas2006:7:2:2
- [x] Casasnovas2006:7:3:3
- [x] Casasnovas2006:7:4:4
- [x] Casasnovas2006:7:5:5
- [x] Casasnovas2006:7:6:6
- [x] Casasnovas2006:7:7:7
- [x] Casasnovas2006:7:8:8
- [x] Casasnovas2006:7:9:9
- [x] Casasnovas2006:7:10:10
- [x] Casasnovas2006:7:11:11
- [x] Casasnovas2006:7:12:12
- [x] Casasnovas2006:7:13:13
- [x] Casasnovas2006:7:14:14
- [x] Casasnovas2006:7:15:15

**Comment by juliana-gurgel** [comment]
[Neste _commit_](https://github.com/juliana-gurgel/nheengabank/commit/f3d02d09bc480f4b7ee92e49b34f05248c786926), das 8 sentenças revisadas, sugeri as alterações listadas abaixo, @leoalenc.

Em `Casasnovas2006:0:0:17`:
- Desambiguar `Mood`  de _remeẽ_ (`Mood=Imp`)

Em `Casasnovas2006:0:0:21`:
- Alterar `deprel` de _kwá_, `ID` `6`, de `advmod` para `obl`
- Alterar `deprel` de _aité_ de `nsubj` para `det`

Em `Casasnovas2006:0:0:23`:
- Alterar `head` de _usika_ de `4` para `2`
- Alterar `deprel` de _usika_ de `acl:relcl` para `obl`
- Alterar `head` de _waá_ de `2` para `3`
- Alterar `head` de _yaú_ de `3` para `2`

**Comment by juliana-gurgel** [comment]
Sugestões [deste _commit_](https://github.com/juliana-gurgel/nheengabank/commit/72a75496e9c30a2ae322e1bce8f5fef3834b0b32):

Em `Casasnovas2006:7:4:4`:
- Alterar `head` de _iwí_ de `6` para `11`

Tarefas:

- [ ] [Juliana]  `Casasnovas2006:0:0:20`: analisar não projetividade (ver [dissertação](https://www.diva-portal.org/smash/get/diva2:1711719/FULLTEXT01.pdf)).
- [ ] [Juliana] `Casasnovas2006:7:6:6`: analisar não projetividade (ver [dissertação](https://www.diva-portal.org/smash/get/diva2:1711719/FULLTEXT01.pdf)).
- [ ] [Juliana] `Casasnovas2006:7:8:8`: verificar classificação de _tenhuntu_ como adjetivo em Avila (2021, p.748).
- [ ] [Juliana] `Casasnovas2006:7:9:9`: analisar não projetividade (ver [dissertação](https://www.diva-portal.org/smash/get/diva2:1711719/FULLTEXT01.pdf)).

**Comment by juliana-gurgel** [comment]
Sugestões [deste _commit_](https://github.com/juliana-gurgel/nheengabank/commit/901f7dfb52e3c123a63f8e89386aee943742ee82), que conclui a revisão da Lenda  7 de Casasnovas (2006):

Em `Casasnovas2006:7:11:11`:
- Alterar `deprel` de _aintá_ de `iobj` para `obj`

Tarefas:

- [ ] [Juliana]  `Casasnovas2006:7:13:13`: analisar não projetividade (ver [dissertação](https://www.diva-portal.org/smash/get/diva2:1711719/FULLTEXT01.pdf)).

**Comment by juliana-gurgel** [comment]
Professor @leoalenc, o senhor poderia analisar as minhas sugestões de revisão?

**Comment by leoalenc** [comment]
@juliana-gurgel , muito obrigado pelas oportunas sugestões de correção. Em `Casasnovas2006:0:0:21`, parece-me que temos uma estrutura de deslocamento do sujeito à periferia esquerda da sentença, algo semelhante a este exemplo da [documentação](https://universaldependencies.org/en/dep/dislocated.html):

>The new Pakistani general , he 's just been elected .

**Comment by leoalenc** [comment]
@juliana-gurgel , esta é minha análise atual (eu corrigirei o regente da oração subordinada final para o verbo principal):

![dependency_tree](https://github.com/user-attachments/assets/e79f5d18-6bdf-4ac1-9ec7-03ef32a7a800)

Trata-se de construção difícil, pois parece que o relativo é usado como espécie de conjunção integrante, _complementizer_ "complementador" na gramática gerativa. Esse uso do relativo parece decalque do português _que_ enquanto conjunção integrante. Não encontrei abonação análoga em Avila (2021). No padrão rio-negrino, teríamos a seguinte estrutura de complementação verbal sem conjunção subordinativa:

>Yandé yasarú **usika pe manha**, yaú arã pupunha yukisé.

Os únicos exemplos que encontrei até o momento do referido uso do relativo estão em Aguiar (1898). Ver #379.

**Comment by leoalenc** [comment]
```bash
validate.py --lang=yrl --max-err=0 ~/complin/nheengatu/data/corpus/universal-dependencies/yrl_complin-ud-test.conllu

```
[Line 27731 Sent Casasnovas2006:0:0:23 Node 4]: [L3 Syntax rel-upos-mark] 'mark' should not be 'PRON'
Syntax errors: 1
*** FAILED *** with 1 errors


```

**Comment by leoalenc** [comment]
Análise revisada:

![dependency_tree](https://github.com/user-attachments/assets/7fe50083-e14c-4e59-b3f3-72897c59c41b)

**Comment by leoalenc** [comment]
@juliana-gurgel , em `Casasnovas2006:7:11:11`, precisamos mesmo analisar o nó 9 como `iobj`, pois, do contrário, teríamos um _bug_ do Udapi, conforme #460 .

**Comment by leoalenc** [comment]
@juliana-gurgel , como amanhã é o último dia para push no dev de UD, de modo a integrar v2.15, vou ter de concluir agora a análise dessas suas revisões. Você pode abrir outra _issue_ com as tarefas pendentes nos casos que você marcou como `ongoing`? O GitHub apenas enxerga tarefas que constam do primeiro comentário de uma _issue_.
