### ISSUE TITLE
novas entradas no glossário para análise de exemplos de Hartt (1938)

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#652]
- [x] incluir novas entradas no glossário para análise de exemplos de Hartt (1938)
- [x] _tikã_ como substantivo, @dominickmaia ? 

@dominickmaia em https://github.com/dominickmaia/hartt/issues/17#issue-2674002050:

> Neste _[commit](https://github.com/dominickmaia/hartt/commit/15be4b81ea22528d06c93583b8d623ff37627f36)_, adicionei 28 sentenças anotadas, havendo 16 sentenças que contém 1 ou mais formas no IMP
> 
> @leoalenc , por favor, adicionar no glossário:
> 
> - [x] tapayuna (s.) - pessoa preta
> - [x] murumurú (s.) - caicumana, uma espécie de palmeira espinhosa
> - [x] tikã (s.) - var. tikanga
> - [x] tikã (v.) - var. tikanga
> - [x] igarupawa (s.) - var. garapawa
> - [x] apikawa (s.) - var.  wapikawa
> - [x] anirá (s.) - var. andirá
> - [x] wirané (adv. temp.) - var. wirandé
> - [x] muxama (v.) - enfiar, encordar
> - [x] mundé (s.) - armadilha de caça
> - [x] muyawáu (v.) - deixar fugir, deixar escapar
> - [x] muyawawa (v.) - var. muyawáu

@dominickmaia , vou incluir estas entradas no próximo _commit_, alterando `tikã (s.) - var. tikanga` para `tikã (a.) - var. tikanga`, conforme Avila (2021). Concorda?

**Comment by dominickmaia** [comment]
@leoalenc concordo, é adjetivo mesmo, foi mais um erro meu
