### ISSUE TITLE
anotar e revisar sentenças de Hartt (1938) usando etiquetas especiais

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#657]
- [x] Forma verbal não flexionada:

> 120 - paraná yumuñan oiko.
> 120 - _Paraná **yumunhã** uikú._ \# adaptação de Leonel
> 120 - Paraná uyumunhã uikú. (Hartt, 328, adap.) - O rio está enchendo.
> 120 - O rio está enchendo.

```python
>>> import Metadata
>>> metadata=Metadata.mkTextModernizer('leo','text')
>>> metadata
{'text_modernizer': 'Leonel Figueiredo de Alencar'}
>>> Yauti.ppMetadata(metadata)
# text_modernizer = Leonel Figueiredo de Alencar
>>> 
```

- [x] pronome de segunda classe como objeto direto e verbo sem flexão

> 191 - aé seriyár ixé ñún.
> 191 - Aé se xari ixé nhũ. \# adaptação de Leonel
> 191 - Aé uxari ixé nhũ. (Hartt, 333, adap.) - Ele me deixou sozinho.
> 191 - Ele me deixou sozinho.

- [x] voz médio-passiva (#548 ):

> 209 - xasó xayumumunéu.
> 209 - Xasú xayumuamundéu. \# forma adaptada para anotar e incluir no treebank
> 209 - Asú ayumuamundéu. (Hartt, 334, adap.) - Vou me vestir.
> 209 - Vou me vestir.

- [x] forma não padrão _xayakapi_ em vez de _xayakapika_

> 206 - xasó xayakapy seáua.
> 206 - Xasú xayakapi se awa. \# forma adaptada para anotar e incluir no treebank
> 206 - Asú ayakapika se awa. (Hartt, 334, adap.) - Vou pentear meus cabelos.
> 206 - Vou pentear meus cabelos.

- [x] infinitivo como imperativo (#496 ) e forma não padrão _kapi_ em vez de _ayakapika_

> 207 - saiá kapy ranhé seáua.
> 207 - Xari kapi ranhẽ se áwa. # adaptação de Leonel, ver Avila (2021): ■ Reg. hist.: [Costa [xari], 213; Stradelli [xiare, xiári] 199, [xare] 521; Dias, [chari] 557, [echiare] 562, [xiare] 574; Coudreau, [oxari] 469; Tastevin [xiári], 676; Rondon [chari], 118; Hartt, [xiár] 324, 326, 363, [ruyar [reyar]] 388; Magalhães [xári], 125, 178, 181, 193, 198, 203, 208, 213, 273, 274; Rodrigues, [chare] 63, 90, 101, 110, 283, 319, 320, 321, [chiare] 89, 124, 167, 196, 239, 247, 248, [chiara] 233; [ceare] 304, [ceiara] 308, [chara] 316, 333; Amorim, [xare] 26, [seare] 28, 33, 34, 213, 341, [xeare] 30, 31, 34, 248] ● (do tupi seîar [s- + eîar (s)])
> 207 - NA
> 207 - Deixa-me pentear meus cabelos.

- [x] revisar 206 (@leoalenc )
- [x] revisar 207 (@leoalenc )
- [x] revisar 209 (@leoalenc )

**Comment by dominickmaia** [comment]
> infinitivo como imperativo (https://github.com/CompLin/nheengatu/issues/496 ) e forma não padrão kapi em vez de ayakapika
> 207 - saiá kapy ranhé seáua.
> 207 - Xari kapi ranhẽ se áwa. # adaptação de Leonel, ver Avila (2021): ■ Reg. hist.: [Costa [xari], 213; Stradelli [xiare, xiári] 199, [xare] 521; Dias, [chari] 557, [echiare] 562, [xiare] 574; Coudreau, [oxari] 469; Tastevin [xiári], 676; Rondon [chari], 118; Hartt, [xiár] 324, 326, 363, [ruyar [reyar]] 388; Magalhães [xári], 125, 178, 181, 193, 198, 203, 208, 213, 273, 274; Rodrigues, [chare] 63, 90, 101, 110, 283, 319, 320, 321, [chiare] 89, 124, 167, 196, 239, 247, 248, [chiara] 233; [ceare] 304, [ceiara] 308, [chara] 316, 333; Amorim, [xare] 26, [seare] 28, 33, 34, 213, 341, [xeare] 30, 31, 34, 248] ● (do tupi seîar [s- + eîar (s)])
> 207 - NA
> 207 - Deixa-me pentear meus cabelos.

@leoalenc , aqui acho que foi mais uma falta de atenção da minha parte durante a adaptação, o verbo seria kapiri, certo?

> kapiri (v. tr. e intr.) CARPIR, capinar: Asú akapiri se kupixawa, yaitiwa reté uikú. (Hartt, 353, adap.) - Vou capinar minha roça, está muito cerrada.; Sasiára paá apigawa-itá upitá, maãresé aintá usú umusaka maniáka uí arama, aintá ukapiri kupixawa-itá, aintá umungiri taína-itá kunhã yawé. (Amorim, 435, adap.) - Os homens, contam, ficaram tristes porque iam arrancar mandioca para farinha, capinavam as roças, faziam dormir as crianças como mulher.; Asú akapiri. (Studart, 35, adap.) - Vou capinar. ■ Reg. hist.: [Costa [capiri], 182; Tastevin [capiri], 613; Dias [capire], 573; Seixas [caápiri], 12; Amorim [kapiire], 435; **Hartt [kapy],** 353; Studart [capiri], 35] ● (do tupi kapir)

**Comment by leoalenc** [comment]
> > infinitivo como imperativo (https://github.com/CompLin/nheengatu/issues/496 ) e forma não padrão kapi em vez de ayakapika
> 
> > 207 - saiá kapy ranhé seáua.
> 
> > 207 - Xari kapi ranhẽ se áwa. # adaptação de Leonel, ver Avila (2021): ■ Reg. hist.: [Costa [xari], 213; Stradelli [xiare, xiári] 199, [xare] 521; Dias, [chari] 557, [echiare] 562, [xiare] 574; Coudreau, [oxari] 469; Tastevin [xiári], 676; Rondon [chari], 118; Hartt, [xiár] 324, 326, 363, [ruyar [reyar]] 388; Magalhães [xári], 125, 178, 181, 193, 198, 203, 208, 213, 273, 274; Rodrigues, [chare] 63, 90, 101, 110, 283, 319, 320, 321, [chiare] 89, 124, 167, 196, 239, 247, 248, [chiara] 233; [ceare] 304, [ceiara] 308, [chara] 316, 333; Amorim, [xare] 26, [seare] 28, 33, 34, 213, 341, [xeare] 30, 31, 34, 248] ● (do tupi seîar [s- + eîar (s)])
> 
> > 207 - NA
> 
> > 207 - Deixa-me pentear meus cabelos.
> 
> 
> 
> @leoalenc , aqui acho que foi mais uma falta de atenção da minha parte durante a adaptação, o verbo seria kapiri, certo?
> 
> 
> 
> > kapiri (v. tr. e intr.) CARPIR, capinar: Asú akapiri se kupixawa, yaitiwa reté uikú. (Hartt, 353, adap.) - Vou capinar minha roça, está muito cerrada.; Sasiára paá apigawa-itá upitá, maãresé aintá usú umusaka maniáka uí arama, aintá ukapiri kupixawa-itá, aintá umungiri taína-itá kunhã yawé. (Amorim, 435, adap.) - Os homens, contam, ficaram tristes porque iam arrancar mandioca para farinha, capinavam as roças, faziam dormir as crianças como mulher.; Asú akapiri. (Studart, 35, adap.) - Vou capinar. ■ Reg. hist.: [Costa [capiri], 182; Tastevin [capiri], 613; Dias [capire], 573; Seixas [caápiri], 12; Amorim [kapiire], 435; **Hartt [kapy],** 353; Studart [capiri], 35] ● (do tupi kapir)
> 
> 

@dominickmaia , de fato, você tem razão: é o mesmo verbo que "capinar", apesar de Ávila (2021) não consignar essa acepção no seu dicionário. Então nesse caso a adaptação seria mesmo _kapiri_, sem necessidade de etiqueta especial pra lidar com esse lema especificamente. Mas você vai precisar de etiqueta especial especial pra anotar o uso do infinitivo em vez da forma flexionada _akapiri_.

**Comment by leoalenc** [comment]
@dominickmaia , é importante anotar também o exemplo 475.

**Comment by leoalenc** [comment]
@dominickmaia , consultando aqui o dicionário de língua geral de Prazeres (1891), constatei na página 204 
a forma _capic_ "pentear "
mencionada por Ávila (2021). Então me inclino a usar a etiqueta
 especial para forma moderna =mf em vez de =typo.

**Comment by dominickmaia** [comment]
@leoalenc neste _[commit](https://github.com/dominickmaia/hartt/commit/b554ac2a1cce58d9da6019fd2f01cae6dc2ff50f)_, adicionei as sentenças 120 e 191, mas ainda não consegui usar as etiquetas especiais nos verbos _xayakapi_, _kapi_ e _xayumuamundéu_. Tentei usar a etiqueta =mf, mas, quando funcionou, não incluiu _tags_ nem _features_, somente o Style=Arch. Para o verbo pentear, deu esse erro:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#12>", line 1, in <module>
  File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 3891, in parseExampleHartt
    return _parseExample(sents,copyboard=copyboard,annotator=annotator,check=check,outfile=outfile, overwrite=overwrite,metadata=metadata,translate=translate)
  File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 2846, in _parseExample
    tokenlist=_handleSents(sents,annotator,metadata)
  File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 2745, in _handleSents
    tokenlist=parseSentence(text)
  File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 3014, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 2612, in mkConlluSentence
    modern_token=mkConlluToken(modern_form,modern_entries[0])
IndexError: list index out of range
```

usei `/=mf:m|mundéu:h|v:x|v` e não funcionou, mas acho que _yumuamundéu_ e _muamundéu_ deveriam ser incluídos no léxico, talvez?

**Comment by leoalenc** [comment]
> @leoalenc neste _[commit](https://github.com/dominickmaia/hartt/commit/b554ac2a1cce58d9da6019fd2f01cae6dc2ff50f)_, adicionei as sentenças 120 e 191, mas ainda não consegui usar as etiquetas especiais nos verbos _xayakapi_, _kapi_ e _xayumuamundéu_. Tentei usar a etiqueta =mf, mas, quando funcionou, não incluiu _tags_ nem _features_, somente o Style=Arch. Para o verbo pentear, deu esse erro:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
>     exec(code, self.locals)
>   File "<pyshell#12>", line 1, in <module>
>   File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 3891, in parseExampleHartt
>     return _parseExample(sents,copyboard=copyboard,annotator=annotator,check=check,outfile=outfile, overwrite=overwrite,metadata=metadata,translate=translate)
>   File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 2846, in _parseExample
>     tokenlist=_handleSents(sents,annotator,metadata)
>   File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 2745, in _handleSents
>     tokenlist=parseSentence(text)
>   File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 3014, in parseSentence
>     tk=mkConlluSentence(tokens)
>   File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 2612, in mkConlluSentence
>     modern_token=mkConlluToken(modern_form,modern_entries[0])
> IndexError: list index out of range
> ```
> 
> usei `/=mf:m|mundéu:h|v:x|v` e não funcionou, mas acho que _yumuamundéu_ e _muamundéu_ deveriam ser incluídos no léxico, talvez?

@dominickmaia , quando for reproduzir erro, inclua necessariamente o comando que você executou para eu poder descobrir a causa. Do contrário, geralmente, não vou conseguir descobrir.

**Comment by leoalenc** [comment]
Avila (2021):

>**yakapika** **1)** (_v. tr._)  pentear:  Asú ayakapika se awa. (Hartt, 334, adap.) -  Vou pentear meus cabelos. **2)** (_v. intr._)  pentear-se:  Nhaã-itá paá ta uyakapikantu ta uikú ta uwapika, [...]. (Leetra Indígena. n. 17, 29, adap.) -  Elas só estavam se penteando, sentadas, [...]. ■ Reg. hist.: [Costa [iacapica], 189, 238; Seixas [capique], 8; Tastevin [yacapɨca], 677; Stradelli, [iacapyca] 268, [iacapuca] 367; Hartt [yakapy], 334] ● (da LGA do séc. 18 îekapyk (VPB, 102) ou îeakapyk (DPL, 217) ou îakapyk (DPL, 217) ou kapyk (DPB, 84261); provavelmente do tupi îakãabyky [i + akanga + abyky] ou îeakãabyky [îe- + akanga + abyky])  ◈ muakapika [hist.] (v. tr.) pentear;  ◈ yuyakapika (v. intr.) pentear-se; ser penteado

**Comment by leoalenc** [comment]
> > @leoalenc neste _[commit](https://github.com/dominickmaia/hartt/commit/b554ac2a1cce58d9da6019fd2f01cae6dc2ff50f)_, adicionei as sentenças 120 e 191, mas ainda não consegui usar as etiquetas especiais nos verbos _xayakapi_, _kapi_ e _xayumuamundéu_. Tentei usar a etiqueta =mf, mas, quando funcionou, não incluiu _tags_ nem _features_, somente o Style=Arch. Para o verbo pentear, deu esse erro:
> > ```
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
> >     exec(code, self.locals)
> >   File "<pyshell#12>", line 1, in <module>
> >   File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 3891, in parseExampleHartt
> >     return _parseExample(sents,copyboard=copyboard,annotator=annotator,check=check,outfile=outfile, overwrite=overwrite,metadata=metadata,translate=translate)
> >   File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 2846, in _parseExample
> >     tokenlist=_handleSents(sents,annotator,metadata)
> >   File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 2745, in _handleSents
> >     tokenlist=parseSentence(text)
> >   File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 3014, in parseSentence
> >     tk=mkConlluSentence(tokens)
> >   File "/home/usuario/complin/nheengatu/src/AnnotateConllu.py", line 2612, in mkConlluSentence
> >     modern_token=mkConlluToken(modern_form,modern_entries[0])
> > IndexError: list index out of range
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > usei `/=mf:m|mundéu:h|v:x|v` e não funcionou, mas acho que _yumuamundéu_ e _muamundéu_ deveriam ser incluídos no léxico, talvez?
> 
@dominickmaia , sim, _yumuamundéu_ e _muamundéu_ devem ser incluídas de qualquer forma.

**Comment by leoalenc** [comment]
@dominickmaia , no próximo _commit_, você encontrará as revisões de https://github.com/dominickmaia/hartt/commit/b554ac2a1cce58d9da6019fd2f01cae6dc2ff50f. A solução atual para a forma _seriyár_ , que Avila (2021) adaptou como _uxari_, está longe de satisfatória. Conforme Avila (2021), _xari_ deriva da forma verbal tupi _seîar_, constituída, por sua vez, de _s- + eîar_, ou seja, a flexão prefixal de terceira pessoa _s-_ e a raiz _eîar_ 'deixar', conforme os verbetes respectivos do dicionário de tupi antigo do professor Eduardo de Almeida Navarro. Trata-se, portanto, de forma tupinambá, no entanto, com desvio em relação ao que registra o referido dicionário, com inserção de um /r/. Depois vou abrir uma _issue_ para tratar desse problema especificamente.

**Comment by leoalenc** [comment]
```python
>>> s='''Aé seriyár/=v:o|tpn:s|seîar ixé nhũ.'''
>>> Yauti.pp(s)
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#463>", line 1, in <module>
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3264, in pp
    while(i < len(namelist)):
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3027, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2545, in mkConlluSentence
    new=mkVerb(form,orig=orig,orig_form=orig_form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1975, in mkVerb
    lemma=entry['lemma']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by leoalenc** [comment]
@dominickmaia , aqui está a versão final, levando em conta a análise por meio de `ccomp` ,que você corretamente aplicou no seu _commit_:

```conllu
# sent_id = Hartt1938:0:0:191
# text = Aé seriyár ixé nhũ.
# text_por = Ele me deixou sozinho.
# text_source = p. 333, No. 191
# text_orig = aé seriyár ixé ñún.
# text_eng = TODO
# text_modernizer = Leonel Figueiredo de Alencar
# text_orig_transcriber = Antônio Levy Melo Nogueira
# text_por_modernizer = Antônio Levy Melo Nogueira
# text_sec = Aé uxari ixé nhũ.
# text_por_sec = Ele me deixou sozinho.
# text_sec_source = Avila (2021)
# text_por_sec_source = Avila (2021)
# inputline = Aé/pron seriyár/=typo:c|uxari ixé nhũ.
# text_annotator = Dominick Maia Alexandre
# reviewer1 = Leonel Figueiredo de Alencar
# comment = https://github.com/CompLin/nheengatu/issues/657#issuecomment-2509029348
1	Aé	aé	PRON	PRON	Number=Sing|Person=3|PronType=Prs	2	nsubj	_	TokenRange=0:2
2	seriyár	xari	VERB	V	Mood=Ind|Person=3|Typo=Yes|VerbForm=Fin	0	root	_	CorrectForm=uxari|TokenRange=3:10
3	ixé	ixé	PRON	PRON	Number=Sing|Person=1|PronType=Prs	4	nsubj	_	TokenRange=11:14
4	nhũ	nhũ	ADV	ADV	_	2	ccomp	_	SpaceAfter=No|TokenRange=15:18
5	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=18:19
```
![dependency_tree](https://github.com/user-attachments/assets/35a1b438-f5bc-41c6-9862-d23daa22815a)

**Comment by dominickmaia** [comment]
obrigada, professor @leoalenc 

_commitei_ as sentenças 209, 206 e 207 [aqui](https://github.com/dominickmaia/hartt/commit/116e77caa7fda1a93cf736bca4a93282053126fc) e usei a etiqueta `=typo`, como foi recomendado

**Comment by leoalenc** [comment]
@dominickmaia , veja #548 e https://github.com/CompLin/nheengatu/issues/661#issuecomment-2508130229.

**Comment by leoalenc** [comment]
@dominickmaia , para anotar `Hartt1938:0:0:209`, era preciso levar em conta #662 .

**Comment by leoalenc** [comment]
Questão concluída com https://github.com/CompLin/nheengatu/commit/a6f6d3b60a3fa92b58c8b3950d1d0a6364c7c2e4.
