### ISSUE TITLE
etiquetas especiais para novos verbos

### ISSUE THREAD

**Issue by dominickmaia** [CompLin/nheengatu#660]
@leoalenc  como usar as etiquetas especiais para formas históricas e para formas históricas cujas correspondentes modernas ainda não estão incluídas no léxico?

se relaciona com #657

**Comment by leoalenc** [comment]
> @leoalenc como usar as etiquetas especiais para formas históricas e para formas históricas cujas correspondentes modernas ainda não estão incluídas no léxico?
> 
> se relaciona com #657

@dominickmaia , pode dar exemplos concretos?

**Comment by dominickmaia** [comment]
> @dominickmaia , pode dar exemplos concretos?

@leoalenc 209, 206 e 207 de Hartt

> 209 - xasó xayumumunéu.
> 209 - Xasú **xayumuamundéu**. # forma adaptada para anotar e incluir no treebank
> 209 - Asú ayumuamundéu. (Hartt, 334, adap.) - Vou me vestir.
> 209 - Vou me vestir.
> 
> 206 - xasó xayakapy seáua.
> 206 - Xasú **xayakapi** se awa. # forma adaptada para anotar e incluir no treebank
> 206 - Asú ayakapika se awa. (Hartt, 334, adap.) - Vou pentear meus cabelos.
> 206 - Vou pentear meus cabelos.
> 
> 207 - saiá kapy ranhé seáua.
> 207 - Xari **kapi** ranhẽ se áwa. # adaptação de Leonel
> 207 - NA
> 207 - Deixa-me pentear meus cabelos.

**Comment by leoalenc** [comment]
@dominickmaia , veja https://github.com/CompLin/nheengatu/issues/663#issue-2705854706. Acho que pode fechar a questão.
