### ISSUE TITLE
variantes do verbo "sikindawa" de Hartt (1938)

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#668]
- [x] utilizar _sikiná_ em `Hartt1938:0:0:15`? (@leoalenc )
- [x] anotar o exemplo 16
- [x] fazer levantamento em Hartt (1938) das outras sentenças com variantes do verbo _sikindawa_ 
- [x] anotar essas sentenças

**Comment by leoalenc** [comment]
@dominickmaia , se Avila (2021) lematiza as variantes **_sinkindá_** e **_sikináu_**, decorrentes dos processos fonológicos de monotongação e assimilação de /d/ a /n/, respectivamente, então podemos lematizar _sykená_ de Hartt (1938) como **_sikiná_**, que podemos postular resultou da aplicação dos dois processos referidos.

Avila (2021, p. 701-702):

>**sikindawa** (var. **sikináu** [hist.]; **sikindá**; **sikindáu** [hist. adap.]) (_v. tr._)  **1)** fechar; tapar, tampar, cobrir, vendar; abrigar:  Aramé mikura usikindawa yautí iwikwara upé. (Magalhães, 205, adap.) -  Então a mucura fechou o jabuti num buraco no chão.;  Mairamé amana uri nhaã tapuru-itá uyana paraná kití, usikindawa katú aé. (Amorim, 30, adap.) -  Quando veio chuva esses tapurus correram para o rio a ponto de cobri-lo.;  Resikindawa nhaã ukena-mirĩ. (Magalhães, 205, adap.) -  Feche aquela janela.;  Asuí aintá usikindawa i suí sesá, aintá unheẽ i xupé: ― Rembeú kuíri awá taá unupá indé. (O Novo Testamento em nyengatu, Lucas 22:64) -  E eles vendaram-lhe os olhos, dizendo-lhe: ― Diga agora quem é que te golpeou. {o mesmo que: kindawa, musikindawa 1} **2)** obstruir; interditar (a passagem por):3) [obso.] dobrar (p. ex., panos, ropas etc.)  ■ Reg. hist.: [Costa [cekindaua], 183; Dias [iusequenáu], 561; Coudreau [cikindáua], 469; Seixas [sequenáo], 54; Tastevin [sɨkɨnau], 664; Stradelli, [cekindau], 221, 344; Rondon [ciquindaua], 118; Hartt [sekyná], 320; Magalhães, [cikɨnaú] 104, [cikináu] 165, [cɨkɨnáu] 205, 210, [cɨkináu] 206; Amorim, [sekedau] 28, [sekendau] 30, 154, 289, [sekendá] 119, [sekendaua] 315; Aguiar [iu-cêkënau], 81; Studart [cicunan], 35; Sympson [sequenáu], 66] ● (do tupi sokendab [s- + okendab (s)])

**Comment by dominickmaia** [comment]
@leoalenc entendi, vou refazer agora

**Comment by leoalenc** [comment]
@dominickmaia , você tem razão. Não há em Hartt (1938) outros exemplos com o verbo _sykená_. Sobre a anotação, compare https://github.com/CompLin/nheengatu/commit/1317779ca53bfc078de426817ef2ecef9d244153 com https://github.com/CompLin/nheengatu/commit/0bb0e7a85e2e5b83522eced22c65a59ae9ec1c5c. Veja que estamos anotando o complemento nominal da construção genitiva do nheengatu, análoga à do inglês tirando o _'s_ saxão, como `nmod:poss`, seguindo a teoria de UD. Por sinal, o Yauti anotou isso corretamente.

```python
>>> s='''16 - ekoin esykená ñaá kauasú yurú.
16 - Ekũi esikiná nhaã kawasú yurú.
16 - NA
16 - Vai tampar a boca do balde.'''
>>> Yauti.parseExampleHartt(s,320,annotator=Yauti.PEOPLE['dom'])
# sent_id = Hartt1938:0:0:16
```
```conllu
# text = Ekũi esikiná nhaã kawasú yurú.
# text_por = Vai tampar a boca do balde.
# text_source = p. 320, No. 16
# text_orig = ekoin esykená ñaá kauasú yurú.
# text_eng = TODO
# text_orig_transcriber = Antônio Levy Melo Nogueira
# text_por_modernizer = Antônio Levy Melo Nogueira
# inputline = Ekũi esikiná nhaã kawasú yurú.
# text_annotator = Dominick Maia Alexandre
1	Ekũi	sú	AUX	AUXFR	Mood=Imp|Number=Sing|Person=2|VerbForm=Fin	2	aux	_	TokenRange=0:4
2	esikiná	sikiná	VERB	V	Mood=Imp|Number=Sing|Person=2|VerbForm=Fin	0	root	_	TokenRange=5:12
3	nhaã	nhaã	DET	DEMS	Deixis=Remt|Number=Sing|PronType=Dem	4	det	_	TokenRange=13:17
4	kawasú	kawasú	NOUN	N	Number=Sing	5	nmod:poss	_	TokenRange=18:24
5	yurú	yurú	NOUN	N	Number=Sing	2	obj	_	SpaceAfter=No|TokenRange=25:29
6	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=29:30
```

**Comment by leoalenc** [comment]
@dominickmaia , se quisermos incluir a tradução, que deve ser revisada pelo anotador nesse caso:

```python
>>> Yauti.parseExampleHartt(s,320,annotator=Yauti.PEOPLE['dom'],translate=True)
```
```conllu
# sent_id = Hartt1938:0:0:16
# text = Ekũi esikiná nhaã kawasú yurú.
# text_por = Vai tampar a boca do balde.
# text_source = p. 320, No. 16
# text_orig = ekoin esykená ñaá kauasú yurú.
# text_eng = Go cover the mouth of the bucket.
# text_orig_transcriber = Antônio Levy Melo Nogueira
# text_por_modernizer = Antônio Levy Melo Nogueira
# inputline = Ekũi esikiná nhaã kawasú yurú.
# text_annotator = Dominick Maia Alexandre
1	Ekũi	sú	AUX	AUXFR	Mood=Imp|Number=Sing|Person=2|VerbForm=Fin	2	aux	_	TokenRange=0:4
2	esikiná	sikiná	VERB	V	Mood=Imp|Number=Sing|Person=2|VerbForm=Fin	0	root	_	TokenRange=5:12
3	nhaã	nhaã	DET	DEMS	Deixis=Remt|Number=Sing|PronType=Dem	4	det	_	TokenRange=13:17
4	kawasú	kawasú	NOUN	N	Number=Sing	5	nmod:poss	_	TokenRange=18:24
5	yurú	yurú	NOUN	N	Number=Sing	2	obj	_	SpaceAfter=No|TokenRange=25:29
6	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=29:30

```

**Comment by leoalenc** [comment]
@dominickmaia , reabro a issue porque constatei que não foi utilizada a função `Yauti.parseExampleHartt`, como recomendável:

```python
>>> Yauti.parseExampleHartt(s,320,annotator=Yauti.PEOPLE['dom'],translate=True)
```
```conllu
# sent_id = Hartt1938:0:0:15
# text = Xasikiná ukena.
# text_por = Eu fecho a janela.
# text_source = p. 320, No. 15
# text_orig = xasykená okéna.
# text_eng = I close the window.
# text_orig_transcriber = Antônio Levy Melo Nogueira
# text_por_modernizer = Antônio Levy Melo Nogueira
# text_sec = Asikindá ukena.
# text_por_sec = Eu fecho a janela.
# text_sec_source = Avila (2021)
# text_por_sec_source = Avila (2021)
# inputline = Xasikiná ukena.
# text_annotator = Dominick Maia Alexandre
1	Xasikiná	sikiná	VERB	V	Mood=Ind|Number=Sing|Person=1|Style=Arch|VerbForm=Fin	0	root	_	ModernForm=Asikiná|TokenRange=0:8
2	ukena	ukena	NOUN	N	Number=Sing|Rel=Abs	1	obj	_	SpaceAfter=No|TokenRange=9:14
3	.	.	PUNCT	PUNCT	_	1	punct	_	SpaceAfter=No|TokenRange=14:15


```
