### ISSUE TITLE
anotar originais de exemplos do verbete "membeka" de Avila (2021)

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#670]
- [x] anotar  os originais de alguns dos exemplos do verbete _membeka_ de Avila (2021)
- [x] anotar exemplos de Payema citados por Avila (2021) com prefixo `Avila2021` (original de Payema no momento indisponível)
- [x] anotar o exemplo original de Hartt (1938) (@dominickmaia )

Avila (2021):

>**membeka** (var. **memeka** [hist.]) **1)** (_adj._)  MEMBECA, mole, molenga, brando, tenro, sem consistência; macio, fofo; bambo, frouxo, vacilante, sem firmeza:  _**Membeka** pawa paá i pira, taína yakira yawé._ (Amorim, 361, adap.) -  Contam que o corpo dele era todo mole, como criança nova.;  _Ape pemusantá pe pú pitúa waá-itá, pemukirimbawa pe rinipiá **membeka** waá-itá._ (O Novo Testamento em nyengatu, Hebreus 12:12, adap.) -  Portanto, enrijeçam as suas mãos enfraquecidas e fortaleçam os seus joelhos vacilantes. **2)** (_adj._)  (ser, estar ou ficar) paralizado, paralítico, sem domínio dos movimentos (do corpo) **3)** (_v. 2ª cl._)  (ser, estar ou ficar) mole, molenga, brando, tenro, sem consistência, MEMBECA; macio, fofo; bambo, frouxo, vacilante, sem firmeza:  mirití: _[...] yapuú panakú upé u waturá yamuyapumi arama paraname, i **membeka** arama [...]._ (Payema, 26, adap.) -  buriti: [...] recolhemos no panacu ou no aturá para mergulharmos no rio, para que amoleçam [...].;  _Iwá i **membeka** reté. (Hartt, 322, adap.) -  A fruta é muito mole._ **4)** (_v. 2ª cl._)  (ser, estar ou ficar) paralizado, paralítico, sem domínio dos movimentos (do corpo):  _Umukaturu yepé i **membeka** waá i pira._ (O Novo Testamento em nyengatu, Mateus 9:1 [título acrescido]) -  Ele curou um paralítico.;  _Kwá purakí upisika ximiára umundisá irumu, uxari i **membeka** ximiára._ (Payema, 70) -  O poraquê apanha sua presa com sua descarga elétrica, ele deixa a presa paralisada. ■ Reg. hist.: [Seixas [membéca, memêca], 27; Costa [membeca], 196, 217; Stradelli [membeca, memeca], 411; Dias [membec], 568; Hartt [membék], 322; Tastevin [memeka, memɨka], 631; Amorim, [membeka] 153, 361, [membyka] 215] ● (do tupi membek)

**Comment by dominickmaia** [comment]
@leoalenc  `Avila2021:0:0:729` e `Hartt1938:0:0:44 `[aqui](https://github.com/dominickmaia/hartt/commit/b0b470ef3e0037b061acb69eba7ad929d553cab0)

**Comment by leoalenc** [comment]
> @leoalenc `Avila2021:0:0:729` e `Hartt1938:0:0:44 `[aqui](https://github.com/dominickmaia/hartt/commit/b0b470ef3e0037b061acb69eba7ad929d553cab0)

@dominickmaia , esta sentença já constava do treebank e de `hartt-ud.conllu` com o mesmo `sent_id`. Você executou o validador em `hartt-ud.conllu`? Esse programa acusa sentenças como mesmo `sent_id`. Por outro lado, a adaptação ortográfica mais próxima da forma _imembék_ de Hartt (1938) é _i membeka_, como você fizera na primeira versão, e não _i memeka_.
